a10networks/a10-octavia

AUTHORS, ChangeLog, a10_octavia/common/data_models.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/migration/alembic_migrations/versions/ed9c523cf8ee_adding_ha_features.py, a10_octavia/db/models.py, a10_octavia/db/repositories.py, a10_octavia/db/vthunder.py
Added status column in vThunder DB, to make sure amphora status is active while creating new LB on amphora. This helps in stability of DB status
=> [STACK-459] Added status column in DB

AUTHORS, ChangeLog, a10_octavia/cmd/a10_house_keeper.py, a10_octavia/cmd/a10_octavia_worker.py, a10_octavia/common/a10constants.py, a10_octavia/common/data_models.py, a10_octavia/controller/housekeeping/house_keeping.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/migration/alembic_migrations/versions/ed9c523cf8ee_adding_ha_features.py, a10_octavia/db/models.py, a10_octavia/db/repositories.py, a10_octavia/db/vthunder.py, a10_octavia/install/a10-house-keeper, a10_octavia/install/a10-house-keeper.service, a10_octavia/install/install_service.sh
Implementation of octavia housekeeper for A10 driver
contains
1. Spare amphora bootup feature
2. DB cleanup process
3. Custom a10-house-keeper service(In future to be merged with a10-controller-worker)
=> [STACK-495]house keeper for a10-ocatvia

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/vthunder.py
During resolving conflicts, the changes related import got overridden. Fixing them in this PR.
=> hm import fixes on priority

a10_octavia/controller/worker/flows/vthunder_flows.py
[STACK-602](https://a10networks.atlassian.net/browse/STACK-602)
=> PEP8 for controller worker flows

a10_octavia/api/drivers/driver.py, a10_octavia/cmd/service.py, a10_octavia/cmd/vthunder_heartbeat_udp.py, a10_octavia/common/config_types.py, a10_octavia/common/exceptions.py, a10_octavia/common/openstack_mappings.py, a10_octavia/common/utils.py
[STACK-607](https://a10networks.atlassian.net/browse/STACK-607)
=> PEP8 for api, cmd and common

a10_octavia/a10_config.py, a10_octavia/controller/healthmanager/a10_health_manager.py
[STACK-606](https://a10networks.atlassian.net/browse/STACK-606)
=> Pep8 for controller worker

a10_octavia/db/api.py, a10_octavia/db/base_models.py, a10_octavia/db/migration/alembic_migrations/2d0bd8e6648f_updates.py, a10_octavia/db/migration/alembic_migrations/versions/ed9c523cf8ee_adding_ha_features.py, a10_octavia/db/migration/cli.py, a10_octavia/db/model_base.py, a10_octavia/db/models.py, a10_octavia/db/models_old.py, a10_octavia/db/repositories.py, a10_octavia/db/vthunder.py
[STACK-638](https://a10networks.atlassian.net/browse/STACK-638)
=> PEP8 for db module

README.md, a10_octavia/common/openstack_mappings.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Updated README
- Changes are in compatible with stein branch of octavia.
- `openstack loadbalancer create ...` - successful
[STACK-721](https://a10networks.atlassian.net/browse/STACK-656)
=> STACK-721: (PATCH) : Stein Rebase correction

README.md
Adds sections for: 
- Health-manager service
- Housekeeper service
- HA related configs
=> STACK-743: Updated README.md for better understanding

a10_octavia/common/a10constants.py, a10_octavia/common/config_options.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
```
[vthunder]
port = 443
protocol = 'https'
```
[STACK-780](https://a10networks.atlassian.net/browse/STACK-780)
[STACK-781](https://a10networks.atlassian.net/browse/STACK-781)
=> Resolved rebase issues and modified the create vlan graph flow

AUTHORS, ChangeLog, README.md, a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py
=> STACK-806 : Refactored compute tasks

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/handler_virtual_server.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/base.py, a10_octavia/tests/unit/controller/worker/tasks/test_handler_virtual_server.py
- Delete task for handler virtual server tasks
- Unit tests
[STACK-581](https://a10networks.atlassian.net/browse/STACK-784)
=> Stack 784 - Revert tasks for handler virtual server

a10_octavia/controller/worker/tasks/handler_server.py, a10_octavia/tests/unit/controller/worker/tasks/test_handler_server.py
**Non-Customer Highlights**
- Added revert functions to handler_server task.
- Added unit tests for the reverts of handler_task.
**Closes**
STACK-790
=> STACK-790 : Revert tasks for handler_server

requirements.txt, test-requirements.txt
Do not merge until Travis is working as expected.
[STACK-891](https://a10networks.atlassian.net/browse/STACK-891)
[STACK-895](https://a10networks.atlassian.net/browse/STACK-895)
[STACK-897](https://a10networks.atlassian.net/browse/STACK-897)
=> PR for STACK-889

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py
**RESOLVES**
[STACK-892](https://a10networks.atlassian.net/browse/STACK-892)
=> [STACK-892] Removed excess reboot for VIP network

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py
**affects**
[STACK-1054](https://a10networks.atlassian.net/browse/STACK-1054)
=> Corrected rack flow dependencies

a10_octavia/contrib/scripts/a10_setup_vlan
Creating a new pull request for the same script. Closed the earlier PR as rebase to a different branch had a lot of conflicts.
=> STACK-1097 pointing the script to feature/trunking branch

a10_octavia/common/openstack_mappings.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
Testing Done:
1) Add HTTP listener and check for template_http added in conf file gets added.
2) Delete HTTP listener added.
3) Add TERMINATED_HTTPS listener and check for template_http added in conf file gets added.
4) Delete TERMINATED_HTTPS listener added.
5) Add HTTPS listener and check TCP virtual port is created.
6) Delete HTTPS listener added.
7) Add TCP listener and check TCP virtual port is created.
8) Delete TCP listener added.
=> STACK-1059 add http templates for HTTPS virtual ports

a10_octavia/common/data_models.py
- Created an `Interface` datamodel 
- Created a `DataNetworkMap` datamodel to accept above interfaces.
[STACK-1299](https://a10networks.atlassian.net/browse/STACK-1299)
[STACK-1301](https://a10networks.atlassian.net/browse/STACK-1301)
- Create an `Interface` data model and `DeviceNetworkMap` to store config value inside its objects.
None
- None
- None
=> [STACK-1299, 1301] : Added Interface and DeviceNetworkMap datamodels

README.md
Updated README.md with the information related to the configuration of interface_vlan_map in the hardware thunder section of a10-octavia.conf file.
https://a10networks.atlassian.net/browse/STACK-1310
=> STACK-1310 README update with interface_vlan_map information

README.md
Added description for aVCS cluster configuration for VRRP-VE configuration.
- [STACK-1311](https://a10networks.atlassian.net/browse/STACK-1311)
None
None
None
None
=> Stack 1311: Added ReadME for VRRP-VE 

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py
Need proper raises for LB create/update/delete flows
Adjust flow sequence is needed 
##NOTE
This PR does not carry code refactor of **vthunder_tasks.py** file.
High
https://a10networks.atlassian.net/browse/STACK-1425
Followed planned doc for refactoring the code
Create a LB, update a LB and delete a LB on rack device
Create a LB, update a LB and delete a LB on vThunder device
Create a LB, update a LB and delete a LB on rack device on HA vThunder setup
=> Stack 1425 - Review and correct flow & tasks for Load Balancer

a10_octavia/controller/worker/tasks/vthunder_tasks.py
Severity Level:  Critical
L3v partitions don't have direct ownership of ethernet interface. This leads to no ethernet interfaces being reported thus causing failure during tagging.
[STACK-1490](https://a10networks.atlassian.net/browse/STACK-1490)
Add a hardcoded switch to the shared partition and then back to the current partition. 
N/A
N/A
The following configuration file was used for testing. An HA deployment was tested against to ensure there wasn't any issues when swapping partitions across device contexts as well.
```
devices = [
{
"project_id": "4426bfb28d81417e8bb0747af919cb31",
"ip_address":"10.0.0.105",
"password":"password",
"device_name":"thunder_1",
"partition_name": "PartitionD",
"device_1": {
"vcs_device_id": 1, …
```
=> [STACK-1490]: Can't tag ethernet interface when in a l3v partition

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
Facing issue while setting no_dest_nat and autosnat configured together
High, Critical
https://a10networks.atlassian.net/browse/STACK-1505
Created a custom exception with proper error message
Added a check to throw exception properly .
Create Listener with proper config 
update listener with proper config
Create Listener without proper config 
Create Listener without proper config 
https://teams.microsoft.com/l/file/0D78BE78-C80E-4047-84BB-DD9A631DC2E2?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FGeneral%2FDevTests%2FSTACK-1476.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:44c2ee5a73ec44a1a6962a86c1c06442@thread.tacv2&groupId …
=> [STACK-1505] Added autosnat and no_dest_nat exception check

README.md
- Severity Level : **Critical**
- README correction for VLAN configuration
https://a10networks.atlassian.net/browse/STACK-1522
None
None
None
None
=> [README][STACK-1522] Corrected sample VLAN configuration for hardware thunder

a10_octavia/common/a10constants.py, a10_octavia/common/data_models.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/db/migration/alembic_migrations/versions/05b1446c7f20_add_subnet_id_column_to_vrid_table.py, a10_octavia/db/models.py
=> [STACK-1558] First PR to setup branch

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py, requirements.txt, tox.ini
Severity: Low
Travis was down for a bit. Code was merged during that time which had uncaught errors. All issues found were minor and fell into one of the following categories: versioning issue, unit test not updated, or pep8 issue.
[STACK-1623](https://a10networks.atlassian.net/browse/STACK-1623)
N/A
N/A
N/A
N/A
=> [STACK-1623] Fix issues merged when Travis was down

a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_service_group_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
Made corrections to reflect addition of member protocol count and pep8 needs
=> [STACK-1622] Make corrections to unit tests and fix styling

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
=> Added assignment to status

a10_octavia/contrib/scripts/a10_setup_provider_flat_poc, a10_octavia/doc/tutorial.md
=> Installation and Deployment Tutorial

a10_octavia/common/utils.py
If Bug Fix:
https://a10networks.atlassian.net/browse/STACK-1685
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre>
- Required: List edge cases tested against in unit tests 
- Required: …
=> [STACK-1685] Modified ve_ip config changes in utils validations

a10_octavia/controller/worker/tasks/a10_network_tasks.py
failed to delete a member with error: Failed to handle json field "ip-address"
Severity Level - Critical
https://a10networks.atlassian.net/browse/STACK-1676
Added partition support for following functions:
1. DeleteVRIDPort
2. DeleteMultipleVRIDPort
1. Try to delete member from a partition configured project.
=> [Stack 1676] failed to delete a member with error: Failed to handle json field "ip-address"

a10_octavia/api/drivers/driver.py, a10_octavia/api/drivers/flavor_schema.py, a10_octavia/common/config_options.py, a10_octavia/controller/queue/endpoint.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
POC code for flavor support
https://a10networks.atlassian.net/browse/STACK-1713
TASK 1: Override api driver for flavor functions
TASK 2:  Written basic flavor jsonschema to handle regex , tcp template and http template
TASK 3:  Written DB task to fetch flavor object from flavor and flavor profile table
TASK 4: Written logic [NON SCALING yet]to handle templates above
PART A: template support
openstack loadbalancer flavorprofile create --name listener_templates --provider a10 --flavor-data '{"listener":{"tcp_template": "template_ax_tcp", "http_template":"template_ax_http"}}'
openstack loadbalancer flavor create --name listener_templates --flavorprofile listener_templates --description  "Flavor to attach TCP or HTTP template to listener"
openstack loadbalancer create --vip-subnet-id …
=> POC code Flavor support 

AUTHORS, ChangeLog, a10_octavia/api/drivers/flavor_schema.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py
Various updates to add flavor logic
[STACK-1772] - https://a10networks.atlassian.net/browse/STACK-1772
[STACK-1774] - https://a10networks.atlassian.net/browse/STACK-1774
- Added utility function to parse config
- Added flavor logic to virtual server tasks
- Started refactor of virtual port task
- Added recursive lookup of flavor id to db task
- Refactored schema to closer match an json api formatting
**** Need to transform `-` to `_` so `template-tcp` -> `template_tcp` so that it can be passed as a kwarg to the acos-client library
**** Need to be sure that name expressions override regular flavor options. And that regular flavor options override config options
N/A
- Required but not accomplished in this PR
N/A
[STACK-1772]: https://a10networks.atlassian.net/browse/STACK-1772
[STACK-1774]: …
=> [STACK-1772/4]Flavors utility refactor, virtual server flavors, and flow update 

a10_octavia/api/drivers/flavor_schema.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_service_group_tasks.py
flavor and name-expr logic to service-gourp and server
STACK-1801 Add name-expr and flavor logic to service group tasks
STACK-1802 Refactor name-exrp and flavor logic for server tasks to use utility function
```
--------------------------------------------------
Flavor schema - server name-expressions
--------------------------------------------------
- flavor
{"server": {"name-expressions": [{"regex": "-limited-", "json": {"conn-limit":65535, "conn-resume": 5000}}]}}
{"server": {"conn-limit":8, "conn-resume": 7}}
- commands
openstack loadbalancer flavorprofile create --name fp_srv_regex1 --provider a10 --flavor-data '{"server": {"name-expressions": [{"regex": "-limited-", "json": …
```
=> Feature/flavor support - flavor and name-expr logic to service-gourp and server

a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_server_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> virtual-server flavor support

a10_octavia/controller/worker/flows/a10_health_monitor_flows.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_health_monitor_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_service_group_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> flavor support for slb objects set command

a10_octavia/controller/worker/tasks/virtual_server_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> fix for arbitrary arguments for axapi to acos-client

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/l7policy_tasks.py, a10_octavia/controller/worker/tasks/l7rule_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> STACK-1847 Add support for arbitrary arguments for axapi to acos-client

a10_octavia/api/drivers/driver.py, a10_octavia/api/drivers/flavor_schema.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> provide better help info for a10 flavor

a10_octavia/api/drivers/driver.py, a10_octavia/api/drivers/flavor_schema.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> update code from source branch

a10_octavia/api/drivers/flavor_schema.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> fix help message error

a10_octavia/api/drivers/driver.py, a10_octavia/common/config_options.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> fix for review comments

a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> listener pool selection

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/nat_pool_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_nat_pool_tasks.py
For given nat-pool flavor, NAT pool will be created on Thunder when loadbalancer is created.
https://a10networks.atlassian.net/browse/STACK-1899
https://a10networks.atlassian.net/browse/STACK-1901
- When nat-pool flavor is passed while creating a loadbalancer: 
- if the specified nat-pool with the same range does not exists on thunder, the nat-pool given in the flavor gets created.
- if the specified nat-pool with the same range exists on thunder, the nat-pool will not get created on thunder as it already 
exists.
- if the specified nat-pool with the different range exists on thunder, an error will be raised with a message as "The nat-pool 
already exists on thunder".
- Given a nat-pool flavor, when a loadbalancer is created, the nat-pool will get created on thunder if the same nat-pool …
=> [STACK-1899][STACK-1901]: Nat-pool creation for given nat-pool flavor

a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/unit/common/test_utils.py
Please refer PR 
https://github.com/a10networks/a10-octavia/pull/250
=> Patch for stable/stein for STACK-1893, 1894

a10_octavia/controller/worker/tasks/nat_pool_tasks.py
It includes fix for the review comments which are related to nat-pool creation/deletion
- Modified create api call for nat-pool creation by adding `**natpool_flavor_list[i]` and `**natpool_flavor` to it for kwargs
- Removed unwanted `continue`
- Added revert for nat-pool creation
=> feature/snat: Fix for review comments specific to nat-pool creation/deletion

a10_octavia/controller/worker/tasks/nat_pool_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_nat_pool_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> feature/snat: Review fixes

a10_octavia/cmd/a10_house_keeper.py, a10_octavia/controller/housekeeping/house_keeping.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> Review comments/feature/write mem

a10_octavia/cmd/a10_house_keeper.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
while addressing https://github.com/a10networks/a10-octavia/pull/286/files
=> Fixed minor travis issue for branch feature/write_memory_enhancement

a10_octavia/controller/worker/tasks/vthunder_tasks.py
Addressed Review Comments for https://github.com/a10networks/a10-octavia/pull/286
=> Review comments on feature/write_memory_enhancement

a10_octavia/controller/worker/flows/a10_member_flows.py
- Issue Description: In member delete subnet during pool deletion, we didn't add NAT pool related task in it.
https://a10networks.atlassian.net/browse/STACK-2050
Like member deletion, we add NAT pool related task to pool deletion member delete flow.
<pre>
<b>
{ 
"nat-pool":{ 
"pool-name":"pool1", 
"start-address":"192.168.90.201", 
"end-address":"192.168.90.210", 
"netmask":"/24", 
"gateway":"192.168.90.1" 
}, 
"nat-pool-list":[ 
{ 
"pool-name":"pool2", 
"start-address":"192.168.90.211", 
"end-address":"192.168.90.220", 
"netmask":"/24", 
"gateway":"192.168.90.1" 
}, 
{ 
"pool-name":"pool3", 
"start-address":"192.168.90.221", 
"end-address":"192.168.90.230", 
"netmask":"/24", 
"gateway":"192.168.90.1" 
} 
],
"virtual-port": {
“name-expressions": [
{
"regex": …
=> [Bug] [STACK-2050] ip nat pool data was not released if deleted pool directly

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
Issue Description: While creating upd listener, tcp rule was adding in security group for corresponding udp listener.
- https://a10networks.atlassian.net/browse/STACK-2228
In listenerCreate task, listerener.protocol change to lowercase. Due to which a condition fails in UpdateVIP==>allowed_address_pairs.py file.
so updated the listener.protocol  back to upper case at the end of listenerCreate task.
1) Create loadbalancer, tcp, listener, and upd listener.
```
openstack loadbalancer create --vip-subnet-id vip_subnet --name lb11
openstack loadbalancer listener create --protocol HTTP --protocol-port 8080 --name l161 lb11
openstack loadbalancer listener create --protocol UDP --protocol-port 53 --name l163 lb11
```
Logs:
```
Apr 09 05:04:27 adeeb a10-octavia-worker[30615]: …
```
=> [STACK-2228]: code update for adding udp rule in security group

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
=> Added code for adding ips in allowed address pair

a10_octavia/db/migration/alembic_migrations/versions/9bfc38df2582_updated_vrid_table_to_use_a_uuid_for_.py
DB was not 
- Upgrade: Added removal of auto-increment from upgrade
- Downgrade: Added re-addition of auto-increment during downgrade 
N/A
N/A
`alembic upgrade head`
`alembic downgrade cfce01f4010d`
=> [STACK-2321] DB upgrade issue

a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py
- Issue Description: For a10-neutron-lbaas the server name is of the format "_53489_10_0_12_167_neutron" and for a10-octavia it is of the format "53489_10_0_12_167"
https://a10networks.atlassian.net/browse/STACK-2523
- Added a method `_get_server_name()` for getting correct server_name.
- Added a call to get the server_name before performing an update or a delete in case of members.
- Confirm _get_server_name() can return correct server_name format in case of a10-octavia member creation
- Confirm _get_server_name() can return correct server_name format in case of a10-nlbaas member creation
- Confirm _get_server_name() raises NotFound if not found
Tested member creation, updation and deletion in case of a10-octavia after doing these code changes.
=> [STACK-2523]: Backward compatibility for server name

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Severity Level : High
- Issue Description: Performing a cascade deletion via Octavia fails when an AFLEX (l7rule) rule references a pool.
- https://a10networks.atlassian.net/browse/STACK-2677
- Updated the code to delete the l7policies first
1) Create lb and other objects
```
openstack loadbalancer create --name vs2 --vip-subnet-id private-b-subnet
openstack loadbalancer create --name vs1 --vip-subnet-id private-a-subnet
openstack loadbalancer listener create --name l2 v2 --protocol http --protocol-port 80
openstack loadbalancer pool create --name p2 --protocol http --lb-algorithm LEAST_CONNECTIONS --session-persistence type=HTTP_COOKIE --listener l2
openstack loadbalancer member create --address 11.0.0.64 --subnet-id private-b-subnet --protocol-port 4 --name m1 p2
openstack …
```
=> [STACK-2677]: [BUG][cascade delete] AFLEX rule using pool is not deleted before pool

a10_octavia/common/utils.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> Stack 2575

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py
If Bug Fix:
<pre>
</pre>
<pre>
devices=[
{
},
}]
</pre> …
=> fix merge issue

a10_octavia/controller/worker/tasks/server_tasks.py
If Bug Fix:
In a10-octavia, it use child project_id to create slb server name. But in neutron-lbaas it use parent project_id.
So, with use_parent_partition after migration a10-octavia can't find the slb server on thunder.
https://a10networks.atlassian.net/browse/STACK-2647
When use_parent_partition is configured, use try to use parent project_id to find slb server first. If not, use child project_id instead.
<pre>
#vrid=7
#vrid_floating_ip = ".126"
#vrid_floating_ip = "dhcp"
use_parent_partition=True
[vthunder]
#l2dsr_support = True
[listener] …
=> [STACK-2647] Fix use_parent_partition issue after migration

a10_octavia/controller/worker/tasks/virtual_server_tasks.py
- Issue Description: Character length limit is 63 for virtual-servers
- https://a10networks.atlassian.net/browse/STACK-2762
- Added a warning if the description limit exceeds the character limit.
- Trim the description length to 61 characters. So that after adding double quotes ("") , it does not exceeds 63 characters.
1) Create lb with no description
```
openstack loadbalancer create --name v2 --vip-subnet-id private-a-subnet
Logs:
Aug 13 05:07:52 victoria a10-octavia-worker[2536233]: INFO octavia.controller.worker.v1.tasks.database_tasks [-] Mark ACTIVE in DB for load balancer id: 11710b3e-2ef6-479f-bcb2-33ae381640db
Aug 13 05:07:52 victoria a10-octavia-worker[2536233]: INFO a10_octavia.controller.worker.tasks.vthunder_tasks [-] Performing write memory for thunder …
```
=> [STACK-2762]: Trim the description length of virtual server to 61 characters

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
- Issue Description: Connection Limit Config Error
Merge this fix in release/v1_3_2
Please look PR #495 for more details.
- https://a10networks.atlassian.net/browse/STACK-2765
- N/A
- N/A
- N/A 
- N/A
=> [STACK-2765]: Raised exception if connection limit is out of bound and merge it release/v1_3_2

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/repositories.py
- Issue Description :[vthunder][l2dsr_support & slb_no_snat_support] only work when creating vthunders
- Merge this fix in release/v1_3_2
- Please look PR #493 for more details
- https://a10networks.atlassian.net/browse/STACK-2620
- N/A
- N/A
- N/A
- N/A
=> [STACK-2620]: Updating allowed address pair while running set command for loadbalancer/member and merge it to release/v1_3_2

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
Incorporated review comments of PR https://github.com/a10networks/a10-octavia/pull/514
- Added code changes as per the review request
- Added unittests for updated and newly added tasks
=> [STACK-2811]: Incorporated review comments.

a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
Refactored `TagInterfaceForMember` task and `_add_vrid_to_list()` in case of member_batch_update
=> [STACK-2811]: Refactored some code related to member_batch_update feature

README.md
Merge stable/victoria changes to master
N/A
Merge stable/victoria changes to master
<pre>
<b>N/A</b>
</pre>
N/A
N/A
=> Merge stable/victoria changes to master

a10_octavia/api/drivers/driver.py, a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/server_tasks.py
We're testing victoria in order to enable a feature unavailable in the stein version of octavia. We need these features and fixes to be available in victoria as well. I've been testing with these cherry-picked commits in the lab and everything seems to work as expected.
=> Merge stein changes into victoria

a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py
- Severity Level  High
Porting STACK-3171 to master branch for victoria
https://github.com/a10networks/a10-octavia/pull/560
https://a10networks.atlassian.net/browse/STACK-3171
[- Required: Overview of approach taken to solve the problem
- Optional: List of tasks completed w/ links ](https://github.com/a10networks/a10-octavia/pull/560)
<pre>
<b>N/A</b>
</pre>
https://github.com/a10networks/a10-octavia/pull/560
https://github.com/a10networks/a10-octavia/pull/560
=> [STACK-3171] Health Monitor on target server ports

a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py
Merge master to stable/victoria For:
- STACK-3171
automation test report: http://10.64.3.124/JobListDetail.tcl?OCTAVIA3_062222203751_ytsai_stability_test
https://a10networks.atlassian.net/browse/STACK-3171
https://a10networks.atlassian.net/browse/STACK-3171
https://github.com/a10networks/a10-octavia/pull/560
<pre>
<b>N/A</b>
</pre>
https://github.com/a10networks/a10-octavia/pull/560
https://github.com/a10networks/a10-octavia/pull/560
=> Merge master to stable/victoria for STACK-3171

a10_octavia/common/utils.py
- Severity : Critical
- Issue Description: [IPv6 support][vThunder flows] Failed to create IPv4 loadbalancer.
https://a10networks.atlassian.net/browse/STACK-3627
- Checked IP belongs to subnet or not in case of IPv6 only as for IPv4 we are using dhcp
- In case of more than 1 amp_boot_networks specified in conf file, If its respctive IP is present in **subnet_ipv6_addresses**  dict then will use that otherwise will make that interface as IPv4
Commented result on this ticket:
[- Required: List of steps to manually test feature or fix ](https://a10networks.atlassian.net/browse/STACK-3627)
=> [STACK-3627][IPv6 support][vThunder flows] Failed to create IPv4 loadbalancer.

a10_octavia/controller/worker/tasks/vthunder_tasks.py
If Bug Fix:
- Severity Level :High
- Issue Description:[Rack flow] Failed to create load balancer with rack flow 
[**This is optional if you are an external contributor**
- Required: Add links to tickets closed here](https://a10networks.atlassian.net/browse/STACK-3645)
- Added subnet version 4 in   **get_net_info_from_cidr()** which was missing.
http://10.64.3.124/JobListDetail.tcl?OCTAVIA2_050223235815_Sana.Agalawane_master,master
=> [STACK-3645][Rack flow] Failed to create load balancer with rack flow 

a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
https://review.opendev.org/c/openstack/octavia/+/831051
=> add notifications for zed release
