a10_octavia/db/migration/cli.py, setup.cfg
Updated setup.cfg to point to a10-octavia DB migration script
Shameless copying of octavia.db.migration.cli module - added our copyright statement due to changes made, not sure correct way to handle that.
=> Updated setup.cfg to use our DB migration tool

README.md
High Priority - Needed to remove plugin creation part on priority, this might result in issues while installing our plugin.
=> [STACK-418] Removal of plugin creation part

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_network_tasks.py
- Delete flow for loadbalancer added 
- Unit Tests added for applicable network tasks.
[STACK-581](https://a10networks.atlassian.net/browse/STACK-581)
[STACK-589](https://a10networks.atlassian.net/browse/STACK-589)
[STACK-590](https://a10networks.atlassian.net/browse/STACK-590)
[STACK-842](https://a10networks.atlassian.net/browse/STACK-842)
=> STACK-581 : [VLAN] Delete flows for load balancer

a10_octavia/contrib/scripts/a10_setup_provider_vlan_poc
1) This script takes following arguments:
OPTIONS:
--help                     prints this message
--setup-provider-vlan      sets up provider ovs bridge br-vlanp, neutron vlan config and
openstack vlan networks.
make sure to delete all non devstack entities created by user
in openstack before running this command. 
--teardown-provider-vlan   tears down the openstack vlan networks, ovs bridge settings and
removes neutron vlan config.
make sure to delete all vlan entities created by user
in openstack before running this command.
2) After running the above script with argument --setup-provider-vlan argument one can run the following command to create a vThunder instance outside of openstack. Make sure to run it from the directory where vthunder qcow2 is present.
virt-install -n vThunder-1 …
=> STACK-1110 script to create and teardown provider poc vlan networking

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
**Issue**
https://a10networks.atlassian.net/browse/STACK-1061
**Test Cases**
We can create 5 types of listener
Enable no_dest_nat in [listener] section of a10-octavia.conf
Create HTTP listener - should get created without no-dest-nat enabled
Create HTTPS listener - should get created without no-dest-nat enabled
Create TERMINATED_HTTP listener - should get created without no-dest-nat enabled
Create TCP listener - should get created with no-dest-nat enabled
Create UDP listener - should get created with no-dest-nat enabled
**functional changes**
Add a condition that checks if no-dest-nat is enabled, if protocol is not in TCP or UDP, disable the no-dest-nat argument.
**Non-functional changes**
Added a comment flag so can we can add more filters
As I can see more filters are supposed to be …
=> [STACK-1061] Added no-dest-nat check filter

README.md, a10_octavia/common/config_options.py
- Now customer can add global configuration inside namespace [a10_global] section in `/etc/a10/a10-octavia.conf` as follows. 
```
[a10_global]
<user_defined_flags> = <random_value>
```
- Added section in README for `[a10_global]`. Though, currently doesn't have any options set.
[STACK-1165](https://a10networks.atlassian.net/browse/STACK-1165)
=> STACK-1165: Default a10-octavia.conf section

a10_octavia/common/config_options.py, a10_octavia/common/data_models.py, a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/decorators.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/migration/alembic_migrations/versions/b02c78488551_updating_vthunders_table_with_new_column.py, a10_octavia/db/migration/alembic_migrations/versions/ed9c523cf8ee_adding_ha_features.py, a10_octavia/db/models.py, a10_octavia/tests/unit/common/test_utils.py
- Adding `hierarchical_multitenancy` to db and models. 
- Added alembic revision script.
- Adding `enable_hierarchical_multitenancy` config support in `[a10_global]` settings.
- Supported for `enable_hierarchical_multitenancy` in `CreateRackVThunderEntry()` and added `revert()`.
- Refactored utils.py to add partition name length validation in config.
- Modified `partition` -> `partition_name` in db as well as configuration
- Added UTs for testing `common/utils.py`
```
[a10_global]
enable_hierarchical_multitenancy = False
devices=[
{
"project_id": "d215d1a6f7d44057922bfc6433b1dcbf", 
"username" : "admin", 
"password" : "devops123",
"ip_address" : "10.43.12.122", 
"partition_name" : "development", 
}]
``` …
=> STACK-1138 : Implement Hierarchical Multitenancy Feature for racked hardware

a10_octavia/common/config_options.py, a10_octavia/common/defaults.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/etc/example_config.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
Tested with use_rcv_hop_for_resp config option True, False, 0, 1 and Other.
=> STACK-1092 and STACK-1091 changes to support use-rcv-for-resp

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Added Database task to update `vthunders` table with `Port` info like `vrid_port_id` and `vrid_floating_ip`
[STACK-1210](https://a10networks.atlassian.net/browse/STACK-1210)
- This task is supposed to get executed if config flag `vrid_floating_ip` is not `None`. Hence this task will update `vthunders` table with `vrid` info, if fetched `port` is not `None`.
- N/A
a) If `port` is None         :  `vthunders` table is not updated
b) If `port` is not None  :  `vthunders` table is updated with `vrid_port_id` and `vrid_floating_ip` 
- Added UTs to test above mentioned TCs. No manual testing done yet.
=> STACK-1210 : Create CreateVRRPEntry task in database tasks

a10_octavia/common/data_models.py, a10_octavia/db/migration/alembic_migrations/versions/58437bd431b9_added_vrid_port_id_and_vrid_floating_ip.py, a10_octavia/db/models.py
- Modified `VThunder` data model to have `vrid_port_id` and `vrid_floating_ip`
- Also Included alembic revision to update `vthunders` table to add 2 new columns for  `vrid_port_id` and `vrid_floating_ip`
[STACK-1225](https://a10networks.atlassian.net/browse/STACK-1225)
[STACK-1226](https://a10networks.atlassian.net/browse/STACK-1226)
- Updated `Vthunder` class and data model to include this feature.
- Added Alembic script to add new columns to `vthunders` table.
None
- None
- `sudo pip install -e .`
- `sudo systemctl restart a10-con*`
- Run `alembic upgrade head` in `a10-octavia/a10_octavia/db/migration` to update your db
- open mysql
- Run `desc vthunders;` and you will find new columns - `vrid_port_id` and `vrid_floating_ip` added.
=> Stack 1225, 1226: Update VThunder model with VRRP info, alembic revision for db

a10_octavia/common/config_options.py
- `a10_global` now accepts `vrid_floating_ip `  as option
- `vrid_floating_ip`  accepts both string `dhcp` or  IP addresses as value
[STACK-1211](https://a10networks.atlassian.net/browse/STACK-1211)
[STACK-1213](https://a10networks.atlassian.net/browse/STACK-1213)
- oslo_config does not have a provision of supporting both string and IP addresses
<pre>
<b>vrid_floating_ip 
</b>
</pre>
<pre>
[a10_global]
vrid_floating_ip = "dhcp"
or 
vrid_floating_ip = "10.10.10.12"
</pre>
<b>vrrp_floating_ip </b>
a) if `vrrp_floating_ip`  is random string not matching regex -  **Service fails.**
b) if `vrrp_floating_ip`  is dhcp -  **Service starts.**
c) if `vrrp_floating_ip`  is invalid IPv4 address   **Service fails.**
d) if `vrrp_floating_ip`  is a valid IPv4 address   **Service starts.**
a) Edit …
=> STACK-1213, STACK-1211 - Added vrid_floating_ip option in a10_global

a10_octavia/common/utils.py, a10_octavia/tests/unit/common/test_utils.py
The utility function to patches partial IPv4 suffix with subnet provided.
If the IPV4 suffix contains the complete valid IP then returns the suffix provided.
Otherwise returns the patched IP if it is valid, else returns None.
https://a10networks.atlassian.net/browse/STACK-1233
1) For validating the Partial IP provided in the config check the return value of patch_ipv4_suffix(config_partial_ip, '10.0.0.0') to be not None.
2) To patch the partial IP with neutron subnet and validate it, use the return value of patch_ipv4_suffix(config_partial_ip, subnet)
1) Positive test cases with Partial IP strings '10', '.10', '11.10', '11.0.11.10'.
2) Negative test cases with Partial IP strings '325', 'abc.cef', '11.10.0.11.10', '10.abc.11.10'.
1) Tested with STACK-1146 changes.
2) Added …
=> STACK-1233 Add utility func to patch partial IP octets

README.md, a10_octavia/common/config_options.py, a10_octavia/common/config_types.py, a10_octavia/common/utils.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/tests/unit/common/test_utils.py
- **Severity Level (Low)**
- **Issue:** Refactor config file with following changes:
a) Make sure all configs are lower case
b) Change `rack_vthunder` to `hardware_thunder`
c) Remove l7policy and l7rule opts, as it is not needed.
[STACK-1132](https://a10networks.atlassian.net/browse/STACK-1132)
a) Updated `README` with lower case configs, also added some more `a10_global` configs
b) Removed L7 Policy and L7 Rule Opts.
c) Removed `rack` from modified variable, method name.
<pre>
devices=[{
}]
</pre>
a) Configuration should accept `[hardware_thunder]` as valid section 
b) Existing UTs should pass.
c) README updates are valid and are visible …
=> Stack-1132: Config file refactor

a10_octavia/common/utils.py, a10_octavia/tests/unit/common/test_utils.py
Added a few IPV4 utility functions.
1) To get subnet_ip and netmask from CIDR
2) To check whether the IP lies in the subnet range
3) Merge the (partial) host IP provider with the network IP of CIDR
https://a10networks.atlassian.net/browse/STACK-1215
Used python socket library which accesses BSD socket interface to write the utilities as suggested by Hunter.
Unit tests updated with positive and negative testcases.
1. Tested with STACK-1146 changes.
2. Added "interface_vlan_map" config to rack_vthunder device config.  
"interface_vlan_map": {  
"1": {
"11": {"use_dhcp": False, "ve_ip_address": "20"},
"12": {"ve_ip_address": ".10"},
"13": {"use_dhcp": True}
}
}
3. Created VIP on VLAN 11 subnet and Members on VLAN 12 and 13 subnets.
=> STACK-1215 Few IPV4 utility functions

a10_octavia/common/exceptions.py, a10_octavia/common/utils.py, a10_octavia/network/data_models.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
Refactored neutron driver
Added create and delete port to a10-octavia-neutron driver
Merged together code for trunking + VRID + auto ve/vlan branches - code credits - @hthompson-a10  @ssrinivasan-a10 
[STACK-1253](https://a10networks.atlassian.net/browse/STACK-1253)
[STACK-1244](https://a10networks.atlassian.net/browse/STACK-1244)
Used allowedaddresspair as parent driver to write custom a10-octavia-neutron driver so that we can enhance the functionalities supported by the neutron driver.
Added create and delete port functions, used feature/trunking branch to add trunking solutions to the master.
- Booted a vThunder with normal approach
- Booted a vThunder with rack approach
- Created a port for VRID member creation 
- Deleted a port for VRID member deletion
- Create a LB, check network …
=> STACK-1253 and STACK-1244 - Refactor and unison a10-octavia-neutron driver

a10_octavia/contrib/scripts/a10_setup_provider_vlan_poc
1) The client and server instances launched in openstack VLAN subnets do not have external connectivity.
2) There are two different DHCP running for single VLAN subnet, one neutron DHCP for openstack instances and other for VMs outside openstack present in the same VLAN. Check if outside VMs can use the neutron DHCP.
3) Four VLANs are required for simultaneously sending traffic to two partitions with 2 arm mode.
https://a10networks.atlassian.net/browse/STACK-1285
1) Made the openstack VLAN networks external and added the SNAT rules on the host device for the external access from the instances launched in openstack VLAN subnets.
2) We cannot use neutron DHCP server for VMs outside openstack as the neutron DHCP server configuration is hardcoded to be static and not …
=> STACK-1285 Added 4 VLANs and fixed external access issues

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
Resolve format issue in virtual_port_tasks.py for F523
If Bug Fix:
Severity Level - Low
Description - Resolved formatting error due to string format 
https://a10networks.atlassian.net/browse/STACK-1292
created a listener with proper settings
Created a listener without proper setting(Reproduced - out of range error)
- In config [Listener] section, adjust 'conn_limit' and create listener on active SLB.
=> [STACK-1292] Resolved flake8 issue with string format F528 - code credit @afrinchakure

a10_octavia/controller/worker/flows/a10_health_monitor_flows.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py
- Severity Level : **Low**
- We don't use the listener port to create and update the health monitor port. We just use the hardcoding from acos-client.
[STACK-1273](https://a10networks.atlassian.net/browse/STACK-1273)
- Added param `port` taken from `listeners[0].protocol_port` to `hm.create` and `hm.update` method.
a) Add a LB, a LISTENER and a POOL
```
openstack loadbalancer create --vip-subnet-id 6cf85683-6f16-4bf6-8570-18e114e44f90 --name SLB1
openstack loadbalancer listener create SLB1 --name L1 --protocol HTTP --protocol-port 8001
openstack loadbalancer pool create --protocol HTTP --lb-algorithm SOURCE_IP --listener L1 --name P1
```
b) Add a HM associated with that POOL.
i) for create
`openstack loadbalancer healthmonitor create --name HM1 --delay 5 --timeout 3 --max-retries 3 --type …
=> STACK-1273: Added support to use listener port to create and update hm port

a10_octavia/common/data_models.py, a10_octavia/tests/unit/common/test_utils.py
- Made the existing `VThunder` datamodel a generic `Thunder`. Have `HardwareThunder` and `VThunder` inherit from it.
- Added device_network_map into HardwareThunder.
[STACK-1315](https://a10networks.atlassian.net/browse/STACK-1315)
[STACK-1316](https://a10networks.atlassian.net/browse/STACK-1316)
- Convert existing `VThunder` datamodel to `Thunder` and create two extra datamodels like `HardwareThunder`  and `VThunder` inheriting the above `Thunder`.
- Add  `device_network_map` param in `HardwareThunder` model.
- Also modified the UT related to accessing this new `HardwareThunder` instead of existing `VThunder`
None
- Check if using new HardwareThunder data_model usage doesn't break the existing UTs.
- None
=> [Stack 1315, 1316] : Convert VThunder dm into generic and make HardwareThunder dm inherit.

a10_octavia/common/data_models.py, a10_octavia/common/exceptions.py, a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Modify utility for validating the json struct in `utils.py` and return `DeviceNetworkMap` data model as value
- Refactor `tag_interfaces` method to use new `interface_network_map`.
- Create a utility function to parse the json and return a network map dict with project_id is key and DeviceNetworkMap data model as value
[STACK-1300](https://a10networks.atlassian.net/browse/STACK-1300)
[STACK-1302](https://a10networks.atlassian.net/browse/STACK-1302)
[STACK-1324](https://a10networks.atlassian.net/browse/STACK-1324)
- Modified utils.py to parse `interface_vlan_map` from `[hardware_thunder]` 's `devices` config.
- Added validations for throwing error where ever, invalid config is provided.
- Using parsed data and converting it to respective data_models(`Interface` and `DeviceNetworkMap`) …
=> [STACK-1300, 1302, 1324]: Refactored `interface_vlan_map` config section

a10_octavia/common/utils.py, a10_octavia/contrib/scripts/a10_setup_provider_vlan_poc, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/decorators.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/common/test_config_types.py, a10_octavia/tests/unit/common/test_utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
Modification to handle trunk_interfaces in config
https://a10networks.atlassian.net/browse/STACK-1303
https://a10networks.atlassian.net/browse/STACK-1306
Modify tag_interfaces and tag_interface to handle trunk_interfaces in config and call axapi to
create vlan with tagged_trunks.
<pre>
devices=[
{
<b>
"device_1": {
"ethernet_interfaces": [{
"interface_num": 3,
"vlan_map": [
{"vlan_id": 13, "ve_ip": ".10"}
]
}],
"trunk_interfaces": [{
"interface_num": 1,
"vlan_map": [
{"vlan_id": 11, "ve_ip": ".10"},
{"vlan_id": 12, "ve_ip": ".10"}
]
}],
}
}
</b>
},
}]
</pre>
Updated unit tests for addition of trunk_interfaces.
Used …
=> [STACK-1303, 1306]: VE VLAN Trunking Support

a10_octavia/tests/unit/common/test_utils.py
- Add UTs for utils methods - `validate_interface_vlan_map` and `convert_interface_to_data_model`.
[STACK-1327](https://a10networks.atlassian.net/browse/STACK-1327)
- Covered all test cases for `validate_interface_vlan_map` and `convert_interface_to_data_model`.
None
- Added UTs for both valid and invalid configs for `interface_vlan_map` entries.
- `sudo tox -e py3 test_utils.py`
=> [STACK-1327] UTs of utils for newly added interface_vlan_map config param

a10_octavia/common/config_options.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
- Added `vrid` setting in global config section.
[STACK-1227](https://a10networks.atlassian.net/browse/STACK-1227)
- Added `vrid` in `a10_global` section with datatype as Integer and default value `0`
- Checked if there is any hardcoding for the same in existing code.
- Fixed existing UTs to accept global `vrid` during `update` calls
<pre>
[a10_global]
<b>vrid = 1</b>
</pre>
- If global vrid is provided, the floating ip is updated in that vrid.
- If no global setting is provided, then the previous vrid.vrid is updated or else vrid is taken as `0` 
a) Set `vrid` value in `a10-octavia.conf`  under `[a10_global]` section
b) Put pdb in `a10_octavia_worker.py`
c) While debugging, check value of `CONF.a10_global.vrid`, if it matches with the set one.
=> STACK-1227: Add support for vrid setting in global config section 

a10_octavia/common/config_options.py
AutoSnat feature was by default enabled as it was favorable for vThunders but now with rack devices it may create issue, so setting up default False is required
https://a10networks.atlassian.net/browse/STACK-1328
Setting up autosnat default value to False in common/config_options.py
Following setting in a10_octavia.conf
- check when autosnat is set to True
- check when autosnat is set to False
- check when autosnat is missing 
- Created an SLB. Create 3 ports each with above test cases - SUCCESS
=> Switched default value of autosnat to false

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
There is no check if the VLAN can be deleted in revert of the TagInterface* tasks. This could lead to VLAN in use by VIP or Member could get deleted, and VIP or Member becoming unreachable.
https://a10networks.atlassian.net/browse/STACK-1352
https://a10networks.atlassian.net/browse/STACK-1383
is_vlan_deletable check added to the revert functions.
Induce error in TagInterfaceForLB and TagInterfaceForMember tasks by adding raise in the code.
1) With raise at the end of TagInterfaceForLB task. Create LB.
1a) Check revert gets called.
1b) After TagInterfaceForLB task failure check LB in ERROR state.
1c) Check VLAN and neutron port are not created.
1c) When the LB is in ERROR state delete the LB and check it works fine.
2) With raise at the end of TagInterfaceForMember …
=> STACK-1352, STACK-1383 Fix revert TagInterface tasks

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
Updated virtual port name to use the listener's ID
If Bug Fix:
- Severity Level = High
- Listener ID isn't used in Thunder configuration
https://a10networks.atlassian.net/browse/STACK-1323
- Removed  "load balancer's ID appended with a port id" assigned to the name attribute of the listener.
- Updated name parameter of the virtual port to newly created listener ID.
- Required: Created multiple listeners with different port IDs
- Required: List of steps to manually test feature or fix 
step-1: created one SLB
step-2: created multiple listeners.
step-3: Verified listener ID is being used for listener name
=> STACK-1323 Updated virtual port to use listener's ID

a10_octavia/common/config_options.py, a10_octavia/common/data_models.py, a10_octavia/common/exceptions.py, a10_octavia/common/utils.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/decorators.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/common/test_utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
a) In the VRRP-A High Availability & aVCS environment if one of the device in the cluster goes down then the configuration changes are handled gracefully without erring out. When the other device of the cluster comes up, the configurations to the device that came up can be pushed through update calls.
b) DCHP -> Static & Static -> DHCP config changes fail. Neutron ports are created, updated and deleted according to config.
https://a10networks.atlassian.net/browse/STACK-1375
https://a10networks.atlassian.net/browse/STACK-1376
https://a10networks.atlassian.net/browse/STACK-1377
[STACK-1347](https://a10networks.atlassian.net/browse/STACK-1347)
[STACK-1349](https://a10networks.atlassian.net/browse/STACK-1349)
a)A new task SetupDeviceNetworkMap is introduced to setup device_network_map in …
=> STACK-1375, STACK-1376, STACK-1377 Changes from PP sessions with team

a10_octavia/controller/worker/controller_worker.py
- Severity Level : Critical
- Delete a pool that has a member inside, will succeed in Octavia. But on Thunder, the server(member) is still there.
[STACK-1321](https://a10networks.atlassian.net/browse/STACK-1321)
- When pool is deleted, the child members are deleted before that. 
- Added `delete_member` flow inside `delete_pool` flow of `controller_worker` module.
None
- When pool is deleted via openstack cli command, the members are also deleted from vthunder.
- `openstack loadbalancer pool delete pool1`
- Check vthunder, all the child members (servers) are deleted.
=> [Bug][STACK-1321]: Member isn't removed from Thunder if delete a pool from Octavia

a10_octavia/controller/worker/flows/a10_health_monitor_flows.py, a10_octavia/controller/worker/flows/a10_l7policy_flows.py, a10_octavia/controller/worker/flows/a10_l7rule_flows.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
Writes device memory at the end of each flow
https://github.com/a10networks/acos-client/pull/281
[STACK-1314](https://a10networks.atlassian.net/browse/STACK-1314)
- Write to the shared partition calls client
- Write to a given partition calls client with partition name
- Execute against each flow
- Check that taking down the active doesn't affect write memory of the standby
- Check that taking down the standby doesn't affect write memory of the active
- Ensure that in active-standby mode memory is saved on both devices
=> STACK-1314: Add write mem to end of flows

a10_octavia/controller/worker/tasks/vthunder_tasks.py
The aVCS config is not working with single device setup due to missing network device map check.
https://a10networks.atlassian.net/browse/STACK-1402
Added a condition that checks that device network map is provided.
Environment in which both single and clustered setup co-exists.
Project1 must be aVCS configured and project2 must be a single rack device.
Create LB in both projects, both gets created successfully.
Created a project, associated proper users.
In config added a device as rack device for project.
For other project, in config added a aVCS cluster floating IP and configuration.
Booted LBs in both project.
=> Stack 1402 - VE/VLAN branch not working with single device

a10_octavia/common/a10constants.py, a10_octavia/common/data_models.py, a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/decorators.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
Severity Level:  Critical
Cannot delete load balancers placed in error state as calls were being made to `vthunder` object when it could be of type `None`.
A second bug was uncovered during testing this fix involving the write memory partition. The `if vthunder.partition_name` call would always equate to true after enforcing that `partition_name` defaulted to `"shared"` in the data model.
[STACK-1435](https://a10networks.atlassian.net/browse/STACK-1435)
- Added check on if the vthunder != None before all other checks in the SetupDeviceNetworkMap task
- Added check on if the vthunder != None before all other checks in the WriteMemory task
- Removed `SHARED_PARTITION` constant
- Removed logic to turn `partition_name` to `shared` in the event it's `None` from the validators
N/A
- Added a …
=> [Stack 1435] - Cannot delete loadbalancers in error state; Write memory for shared partition incorrect

a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
Test leaks were causing a need for `vthunder.device_network_map = []` to be set in the SetupDeviceNetworkMap task. These leaks covered up requirements in other tests and could cause further unintended consequences down the line.
[STACK-1445](https://a10networks.atlassian.net/browse/STACK-1445)
Implemented deepcopying of constant required for testing.
N/A
N/A
*Note: Example data such as IPs and project_ids may be altered*
```
[a10_global]
devices = [ 
{   
"project_id":"4426bfb28d81417e8bb0747af919cb31",
"ip_address":"10.0.0.105",
"password":"a10",
"device_name":"thunder_1",
"device_1": { …
```
=> [STACK-1445]: Unit test constant values are being overwritten

a10_octavia/common/config_options.py
- Severity Level :**Low**
- All the template_* related configuration on a10-octavia.conf under different sections requires an existing template* name that is  present on the vthunder. Since the help() description is misleading, editing it to indicate properly.
https://a10networks.atlassian.net/browse/STACK-1461
- Modified the description for all template related configs for `listener`  `service-group` and `server` sections for a10-octavia.conf.
None
None
None
=> [BUG][STACK-1461]: Modified help description of template related configurations of a10-octavia.conf

a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
```ERROR oslo_messaging.rpc.server SubnetNotFound: subnet not found (subnet id: None).```
The above error was raised when `--subnet-id` (an optional argument) was not specified when creating members in a vlan network.
This didn't show very well that the subnet_id (an optional argument) is actually required for our members when using VLAN networks.
I’ve been back and forth on the fix for this. There are 3 options were:
1. Resolve the IP address. And if not resolvable throw an error/warning
2. Log a warning and skip
3. Log and error
https://github.com/openstack/octavia/blob/master/octavia/controller/worker/v2/tasks/network_tasks.py#L76
The above link shows similar code completed upstream. This indicates a design decision of not trying to resolve the subnet’s of members …
=> [STACK-1442]: Creating member without subnet id provided resulted in failure in vlan networks

a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_health_monitor_tasks.py
- Severity Level : **Low**
- Creating a health monitor concatenates the id to 5 characters instead of the full id on VThunder cli.
- Need to remove the unnecessary data type conversion for hm during UpdateHealthMonitor task.
https://a10networks.atlassian.net/browse/STACK-1436
https://a10networks.atlassian.net/browse/STACK-1465
- Removed Slicing of health monitor id before passing it as health monitor name, during create, update and delete
- Also added UTs for health monitor
- In UpdateHealthMonitor task, used `health_mon.update(update_dict)` instead of `health_mon.__dict__(update_dict)`.
None
-  **Create health monitor** 
Successfully creates hm on Vthunder cli. Also gets attached to the pool with same id name.
-  **Update health monitor**
Successfully update hm on Vthunder cli.
- …
=> [BUG][STACK-1436, STACK-1465]: Removed slicing of hm.id for hm name and added UTs

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py
The creation and deletion of a health monitor operations were not atomic. Also, Checked if the act of creation and deletion causes any of load balancer, the listener. pool in the pending state.
If Bug Fix:
Issue Description: The creation and deletion of a health monitor operations were not atomic. Also, Checked if the act of creation and deletion causes any of load balancer, the listener. pool in the pending state.
- https://a10networks.atlassian.net/browse/STACK-1429
- Added revert for creating and deleting health monitor.
- Tested creation of health monitor for pool.
- Tested creation flow by raising an exception on the creation of HM, and checked whole tree(load balancer- listener-pool ) to validate if those …
=> Stack 1429 - Review and correct flow & tasks for Health Monitor

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
1. Resolve an issue occurred during merge process of STACK-1426: Review and correct flow & tasks for ListenerDONE with master
2. If pool doesnt have a listener(default listener) the pool create/delete/update fails
Critical
https://a10networks.atlassian.net/browse/STACK-1475
For first part, due to unexpected merge, a line to pass single listener was missing added that one.
While testing, created a pool with no listener and code failed, Added if listeners array is greater than 0 and added check in task if listener is None.
- Create a pool with no listener, Try to delete the pool 
- Created a pool passing slb name as para
openstack loadbalancer pool create --loadbalancer slb1 --lb-algorithm ROUND_ROBIN --protocol TCP
- delete the pool
openstack loadbalancer pool delete …
=> [STACK-1475] Resolved merge issue, added condition to check listeners

a10_octavia/common/utils.py
Partial IP addresses were not being handled as expected due to generic ipv4 validation being preformed on them
[STACK-1478]
Removed unnecessary validation
N/A
N/A
The following config file was used for testing. The important section is `vrid_floating_ip` which should contain a partial IP address such as `.17` or `6.17`
```
devices = [ 
{   
"project_id": "4426bfb28d81417e8bb0747af919cb31",
"ip_address":"10.0.0.105",
"password":"password",
"device_name":"thunder_1",
"partition_name": "PartitionD",
"vrid_floating_ip": ".17"
}
]
```
The VRID floating IP is not associated until a member is created. Before creating the member the lb, listener, and pool must be created …
=> [STACK-1478]: Removed check on vrid_floating_ip

a10_octavia/controller/worker/tasks/vthunder_tasks.py
During reverts of load balancer create flows, the partition is deleted. This causes 2 issues:
1.  Side effect of deleting a fully configured partition
2. The loadbalancer is placed in error state. Delete's end on write memory tasks, but the partition does not exist causing a separate error to occur.
This PR also removes the check for the `Exists` error being thrown as the `if not axapi_client.system.partition.exists(vthunder.partition_name):` will handle this already.
[STACK-1488](https://a10networks.atlassian.net/browse/STACK-1488)
Removed HandleACOSPartitionChange revert function 
N/A
N/A
Add a `raise` expression to any task after HandleACOSPartition task in the loadbalancer create flow. Then attempt to delete the load balancer in error state. The partition …
=> [STACK-1488] Removed partition deletion on revert

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
Remove re-conversion of protocol type call from revert 
We are in-place converting listener protocol to acos compatible in execute function
Same listener object is passed in case of ACOSExceptionError to Revert function
We can skip, re-conversion of protocol in revert
Create a virtual port with ipinip and snat auto setting (To raise ACOSException)
Make sure correct API is called.
=> [STACK-1493] Quick correction in revert of virtual port

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
- Severity Level : **Critical**
- `ha_conn_mirror` configuration in `a10-octavia.conf` is not supported on listeners at all. It should be supported for TCP and UDP protocol Listeners
https://a10networks.atlassian.net/browse/STACK-1470
- Added argument for accepting `ha-conn-mirror` in listeners api read from `a10-octavia.conf` under `[listener]` section.
- Since for `TERMINATED_HTTPS` and `HTTP` openstack mapping , `ha_conn_mirror` is **not** supported, hence raised a `LOG.warning` related to same and set it as `None`.
**Note**
Since the Openstack_mapping on vthunder is as follows:
- TERMINATED_HTTPS ---> HTTPS
- HTTPS--------------------> TCP
Hence it will be observed, that `ha_conn_mirror` will not be applicable for `TERMINATED_HTTPS` but will be applicable for `HTTPS` openstack …
=> [Bug][STACK-1470]: Added ha_conn_mirror support for Listeners

a10_octavia/controller/worker/tasks/l7policy_tasks.py, a10_octavia/controller/worker/tasks/l7rule_tasks.py
Checked for pending state issues for the related components of l7 policy, accordingly added an exception and revert for the creation of l7policy. Fixed issues related to an L7 policy
Severity Level:  High
ISSUES:
- while CREATING a new l7policy, this L7 policy doesn't get attached to the listener if the listener already has l7 policy attached to it.
- updation failing when we try to update l7policy with action "REDIRECT TO pool" from any other action type.
- When creating a listener  with HTTPS port it gets created with vthunder port, and then tried to fetch vport it was failing there.
https://a10networks.atlassian.net/browse/STACK-1430
https://a10networks.atlassian.net/browse/STACK-1481
- Checked the l7policy, l7rule created flows and tasks.
- Derived test-cases on the basis of the glass …
=> STACK-1430 - Checked pending state inconsistency and fixed issues.

a10_octavia/common/config_options.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
- Severity Level : Critical
- Default value for `ha_conn_mirror` should not be False for all protocols as `ha_conn_mirror` is not applicable for `HTTP` and `TERMINATED_HTTPS`  listener protocols.
https://a10networks.atlassian.net/browse/STACK-1502
- Modified default value to `None` instead of `False`
- Added check for disabling `ha_conn_mirror` for HTTP and TERMINATED_HTTPS protocol type of listeners. In this case, if at all `ha_conn_mirror` setting is given anything (`TRUE/FALSE`) , it will throw warning and `ha_conn_mirror` will be set to None.
None
- Create listener with `--protocol` as `UDP`, `TCP`, `HTTP`, `HTTPS' passed as cli arguments, **_without_** `ha_conn_mirror` setting in `[listener]`
- Did testing with following config in `a10-octavia.conf`
```
[listener]
autosnat=True …
```
=> [Bug][STACK-1502]Modified default value for ha_conn_mirror to None

a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
- Severity Level : **Critical**
- There was a conflict between `delete_port` api called by `revert()` of `HandleVRIDFloatingIP` network task and `DeleteMemberVRIDPort` network task in a particular scenario as follows.
- When a single member is created in a project with some `vrid` setting and for some reason goes into `ERROR` state. Reverts occur where `delete_port` for neutron is called. Now, for cleaning up, we try to delete this ERRORed member, we see, the call to `delete_port` api is again made which results in `PortNotFoundClient` Exception. Even though there is no issue that occurs throughout and we anyway wanted those ports to be removed, stack trace (like below) gives a wrong impression. 
For these redundant calls, we needed to handle this scenario gracefully. …
=> [Bug][STACK-1480]: Added PortNotFoundClient neutron exception for delete_port api of Neutron

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py
- Severity Level : **Critical**
- Given a `project_id`, it should not be bound to multiple thunders when configure with one already in `a10-octavia.conf` and on  updation in `a10-octavia.conf` with different `ip_address`/ `partition_name`, it should throw Config error.
https://a10networks.atlassian.net/browse/STACK-1484
https://a10networks.atlassian.net/browse/STACK-1491
- Added Task to check if there is an existing VThunder entry of the given `project_id`. 
- If yes, checking if the configured `ip_address` and `partition_name` are different than the ones associated with existing VThunder. 
- If No, raises an Config Value exception with appropriate message.
- Also while trying to delete Error'ed LBs with no vthunder entry, was facing issue mentioned like in …
=> [BUG][STACK-1484, 1491] Ensured Sticky Partitions for Hardware Thunder config

a10_octavia/controller/worker/tasks/policy.py
When comparison type is provided as REGEX and type as file type, aflex policy was created with ends_with Comparision and with regular expression as value. 
If Bug Fix:
Severity Level: Medium
Issue Description: Relational Operator is wrong when config l7rule with --compare-type REGEX and --type FILE_TYPE
https://a10networks.atlassian.net/browse/STACK-1446
- Added code REGEX equivalent aflex script for the comparison type regex.
- Created l7rule with comparison type as REGEX and type as FILE_TYPE, value is regular expression, Checked aflex script in Thunder
` openstack loadbalancer l7rule create --compare-type REGEX --value "abc" --type FILE_TYPE policy1`
- Created l7policy with comparison type as equals_to and type FILE_TYPE, checked aflex script.
`openstack loadbalancer l7rule create …
=> [BUG][STACK-1446] - Relational Operator is wrong when config l7rule with --compare-type REGEX and --type FILE_TYPE

a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Severity Level:  **Critical**
- Issue Description: In VLAN env, we were unable to delete an LB completely that has gone into ERROR state for some reason and has no corresponding vthunder entry in db. We get following error on stack trace,
**AttributeError: 'NoneType' object has no attribute 'device_network_map'** 
https://a10networks.atlassian.net/browse/STACK-1512
- Before we try to access `vthunder.device_network_map`, we need to check if `vthunder` exist or not. Hence added them at places where `vthunder.device_network_map` is called.
None
- Normal environment : Deleting LB with status `ERROR` with no associated vthunder entry  will be successful without any error.
- VLAN Enviroment :  Deleting LB with status `ERROR` with no associated vthunder entry  will be successful without any …
=> [BUG][STACK-1512] Failed to delete an ERROR'ed LB with no associated vThunder 

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py
- Severity Level : **High**
- To ensure one Partition maps to only one tenant logic at db level, following two cases occurs: 
_**Case a)**_  : Whether for a particular `project_id` there exist a `ip_address:partition_name` already in db (active). If there is, enforce user to use that, by raising an Error. - (Already resolved in https://github.com/a10networks/a10-octavia/pull/155)
_**Case b)**_ Another case is that whether for a particular `ip_address:partition_name`, there exist a `project_id` already in db (active). If there is, enforce user to use that, by raising an Error. - (**_Resolving in this PR_**)
https://a10networks.atlassian.net/browse/STACK-1520
- Resolves _**Case (b)**_
Added new Task `CheckExistingThunderToProjectMappedEntries`, that does following : 
i) Fetch all the …
=> [BUG][STACK-1520]: Ensure one to one mapping for Hardware Thunder IP_Address:Partition_name <-->Project_id

a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py
The issue of converting "None" string to None object is not handled for pool and member components.  
https://a10networks.atlassian.net/browse/STACK-1393
- Check the instances where the components are created using templates.
- Added code to change none string to None object.
1. Created pool with none template names(none string should be converted to None object).
2. Created member with none template name.
3. Created different templates used for pool creation, and created pool.
4. Created different templates used for member, and created member.
=> [STACK-1393]: Convert none string to None object for pool and member components.

a10_octavia/controller/worker/tasks/health_monitor_tasks.py
When deleting a health monitor, health_check_disable will also get set. As per expectation, the reference of health monitor should be removed from the service group and health_check_disable attribute should be unaltered.
**Before fix behavior:**
`When attached HM is deleted        
slb service-group 8f60340f-e034-403d-83d3-006afff157e9 tcp  
health-check-disable  
member 420735bc-2a96-4b45-9be7-32b22b82f476 80  `
**After fix behavior:**
`openstack loadbalancer healthmonitor create --delay 10 --timeout 5  --max-retries 4 --type HTTP --http-method HEAD --url-path "/abc" --name hm-2 --expected-codes 208 pool-psi 
slb service-group 8d717f7d-14f6-4794-b3ff-405dc9fafc7e tcp  
health-check 959c7349-d9e9-4378-9e9e-4aea96fbfe99  
!    
openstack loadbalancer healthmonitor delete hm-2 
slb …
=> [STACK-1457]: Deleting a health monitor from pool sets pool to health-check-disable instead of just removing the hm association.

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
When creating a UDP protocol type listener, flow is trying to use template_tcp and its configuration. 
If Bug Fix:
https://a10networks.atlassian.net/browse/STACK-1448
- Added an explicit condition in creating and update listener task to check whether listener protocol type is TCP.
- Creating a listener of UDP protocol type with template-tcp added in a10-octavia.conf.
- Created listener of TCP protocol type.
=> [BUG][STACK-1448]: failed to create listener with protocol UDP when config file included :template_tcp=1

a10_octavia/common/config_options.py
When conn-resume not provided, a member is created with value as 1. As per documentation, by default, it should not get set for the member.   
Severity Level: Highest
https://a10networks.atlassian.net/browse/STACK-1549
- Changed the default value for conn-resume from 1 to None
- Tested creation of member with conn-resume not provided.
- Tested creation of member with provided some value to the conn-resume attribute.
=> [BUG][STACK-1549]: [member] will see wrong value for option: conn-resume when created member.

a10_octavia/controller/worker/tasks/a10_database_tasks.py
**_STACK-1498_**
- Severity Level: **High**
- VRID floating IP was not getting reconfigured when we set it in config, then remove it and then again set it.
**_STACK-1524_**
- Severity Level: **High**
- VRID floating ip was configured wrongly for vrid 1  when setting member  or creating new member. Setting member did not change floating-ip for vrid 1 but sets a new floating-ip under vrid 0. 
**_STACK-1525_**
- Severity Level: **High**
- VRID floating ip was not deleted for vrid=1 after delete all members and pool.
https://a10networks.atlassian.net/browse/STACK-1498
https://a10networks.atlassian.net/browse/STACK-1524
https://a10networks.atlassian.net/browse/STACK-1525
- Added delete api call in `UpdateVRIDForProjectMember`  in case `vrid_floating_ip config` is removed.
- Added updated vrid …
=> [BUG][STACK-1498][STACK-1524][STACK-1525]: VRID and VRID Floating IP proper delete and update in db

a10_octavia/common/exceptions.py
-  Severity Level: **High**
- Cosmetic changes needed for error message of `InvalidVCSDeviceCount`
- `"Number of devices in config is should be 1 when VCS is not enabled, provided 2"` ==> remove `“is"`
https://a10networks.atlassian.net/browse/STACK-1548
- Corrected Error message for `InvalidVCSDeviceCount`. Removed unnecessary `is`.
None
- On non-vcs setup, while creating an lb, we get an `InvalidVCSDeviceCount` error message properly.
**Step1:** Set  `a10-octavia.conf` as follows. The 2 vthunders that are added are **NOT** on vcs mode
```
[a10_global]
vrid_floating_ip = ".104"
use_parent_partition = False
network_type = 'vlan'
devices=[
{
"project_id": "b8a9e31710ef4babb8189a5c3d92abc7",
"ip_address": "10.0.0.91",    
"device_name": "rack_vthunder",
"username": …
```
=> [BUG][STACK-1548]: Removed 'is' from Error Message of InvalidVCSDeviceCount

a10_octavia/controller/worker/tasks/a10_network_tasks.py
- Severity Level: **High**
- Only `vrid_floating_ip` should be deleted from vthunder and not the entire `vrid`, once all members are deleted from the project.
https://a10networks.atlassian.net/browse/STACK-1588
- `DeleteMemberVRIDPort` Task had delete vrid call. Instead changed to vrid update call to set `floating_ip` to None.
- Same is handled in another case, where vrid was getting deleted  when `vrid_floating_ip` is removed from config file in `HandleVRIDFloatingIP` task.
None
Please refer Test Cases section of https://github.com/a10networks/a10-octavia/pull/164
_(make sure to manually set vrid as 1 on vthunders)_
a) Initial set `vrid_floating_ip` as `"dhcp"` and `vrid` as `1` in `a10-octavia.conf`
b) Restart `a10-controller-worker.service`
c) Create LB, Listener, Pool and Member …
=> [BUG][STACK-1588]: VRID should not get deleted after deleting all members with a project.

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py
- Severity Level : **High**
- When we create LB with `use_parent_partition` flag as `False` and `hierarchical_multitenancy` (hmt) as `enable` n `a10-octavia.conf`, it should get created in project partition/ shared partition and not in parent partition.
https://a10networks.atlassian.net/browse/STACK-1580
- By default, `hierarchical_multitenancy` (hmt) is `disable`, if not set.
- Changed if condition to be more specific, to check if hmt is set to `enable` and `use_parent_partition` as True, then only Parent partition is to be used. Otherwise for all other conditions, partition used will be either `partition_name` or `shared` (if `partition_name` is not mentioned).
_**Update**_: 
- Added log error for project having no parent or default as parent when all parent partition settings are …
=> [BUG][STACK-1580] : LB should not be created in parent partition with use_parent_partition False and hmt enabled.

README.md, a10_octavia/install/a10-controller-worker.service, a10_octavia/install/a10-health-manager.service, a10_octavia/install/a10-house-keeper.service, a10_octavia/install/install-a10-octavia, a10_octavia/install/install-a10-octavia-dev, setup.cfg
**STACK-1557**
Adding CentOS Support for a10-octavia sothat it can be installed successfully on CentOS with Packstack setup.
https://a10networks.atlassian.net/browse/STACK-1557
- For CentOS, as all the 3 services are getting installed in `/usr/bin` by default instead of `/usr/local/bin`, getting those installed services from `/usr/bin` to` /usr/local/bin` using symlink logic.
- Added logic for setting User in `a10-controller-worker.service`, `a10-health-manager.service` and `a10-house-keeper.service` to **octavia** if it exists in the system otherwise to **root** if octavia user does not exist.
- Brought support for aliases through the install script and set pip to pip2 or pip3 by it, depending on the underlying system environment.
1. Install packstack and octavia manually in a fresh …
=> STACK-1557: Added CentOS Support for a10-octavia

a10_octavia/common/exceptions.py
- Severity Level : Low
- Corrected error message to display arguments like partition_name and device_ip correctly.
https://a10networks.atlassian.net/browse/STACK-1546
- Passed in arguments to string message, which was initially missing
None
- When hmt is enabled and intended partition has been manually deleted from vthunder and not completely, on api invoking throws Error - `PartitionNotActiveError`
1) hierarchical_multitenancy": "enable"
2) create lb1, the project_id partition will be created, and then lb1 will be created in it as expected
3) from openstack delete lb1 successfully
4) on thunder, “no partition xxx id xx” to remove the partition, but not delete it completely from the system
5) create lb1, failed and get error message : 
```
Exception during message handling: …
```
=> [BUG][STACK-1546]: Corrected PartitionNotActiveError error message

a10_octavia/common/utils.py, a10_octavia/controller/worker/controller_worker.py
**STACK-1510**
- Severity Level: **High**
- If `use_parent_partition` is True, listener cannot be created under the previous loadbalancer if modify the `project_id` in `a10-octavia.conf`
- In other words, `Child2` project's listener was not getting created in parent partition when `use_parent_partition` is True, and LB is created from `Child1` project.
https://a10networks.atlassian.net/browse/STACK-1510
_(The setup tested for : there is an `admin` project and `child1` and `child2` project are its children.)_
- It was found that the listener's `project_id` comes from the LB's `project_id` it is attached to and **not** on the sourced project.
- When use_parent_partition is `True`, keeping `hmt` - enabled, when listener intended from `child2` project is fired to get attached to LB of …
=> [BUG][STACK-1510]: When ohm is enabled, child project resources gets created in parent partition of vthunder

a10_octavia/controller/worker/tasks/virtual_server_tasks.py
- Severity level: Medium
- When we set loadbalancer description to "" or " ", then the description parameter should not get attached to it i.e it should set to be **None** for the loadbalancer instead of throwing `ACOSException: 1023459374 Input string exceeds permitted length`.
https://a10networks.atlassian.net/browse/STACK-1612
https://github.com/a10networks/acos-client/pull/294
- Trimming the description given by user and then validating it.
- If description is "" or " ", then it is set to None
- Given description as "", when an lb is updated with it, the description attaching to the lb is None.
- Given description as " ", when an lb is updated with it, the description attaching to the lb is None.
Step1: Update an existing lb1 with description from "lblb1" to ""
Before update:
After …
=> [BUG][STACK-1612]: Handled validations of loadbalancer description

a10_octavia/controller/worker/tasks/server_tasks.py
When we are creating member in existing server with changes in config file, the server config (conn_limit, conn_resume) are not getting updated.
Severity Level : Critical
https://a10networks.atlassian.net/browse/STACK-1619
- Added an update call if server already exists to make config changes in it
- Adjust try...catch block to capture ACOS_ERRORS like 'connectionError' for both the API calls
1. Check config change for existing server
2. Check config change for new server
3. Check config change in between server created with same IP and different port
4. Check config change for new server with different IP
5. Check config change for SET function for pre-existing servers
Step1: Created a server with IP address 10.0.13.122 and port 81
!
slb server 67e06_10_0_13_122 10.0.13.122
port 81 tcp
! …
=> [BUG][STACK-1619] Added update call if server already exists for related config updates

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
the real port was not deleted when deleting a member  with the same port and different protocol
if deleting a member with a different port and different same protocol,  the real port will be deleted, so looks like there is a little inconsistent.
Severity Level: high
https://a10networks.atlassian.net/browse/STACK-1618
- Changed the functionality of fetch member count using IP and port to IP, port and protocol.
- Changed the related variable. 
- Tested the case mentioned in bug report.
- Tested basic cases of deleting member and pool.
=> [BUG][STACK-1618][member]: real port was not deleted when deleting a member with same port but different protocol

README.md, a10_octavia/common/config_options.py, a10_octavia/common/exceptions.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_service_group_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
*Credit to @NehaKembalkarA10 for PR info. This was pulled from the following [Feature Branch PR](https://github.com/a10networks/a10-octavia/pull/181)*
**STACK-1559**
It was not possible to attach a template from shared partition to a listener, member and pool in a l3v partition.
So now by this implementation, we can attach supported templates from shared partition to listener, member and pool in our l3v partition.
https://a10networks.atlassian.net/browse/STACK-1559
Added support for a flag variable `use_shared_for_template_lookup` in config file sothat when user tries to attach a template from shared partition to his desired components of his local partition by setting the flag to **True**, then it will get possible to do so.
**1. For listener (virtual-port):**
It supports …
=> STACK-1559: Allow templates to be used from the Shared Partition

a10_octavia/controller/worker/tasks/virtual_server_tasks.py
Resolved the issue facing while creating a loadbalancer without giving description
https://a10networks.atlassian.net/browse/STACK-1612
- Setting description to "" when it contains only spaces in it or when it is not provided.
https://github.com/a10networks/acos-client/pull/294
Following are the results for the steps mentioned in the bug by referring lb1 as lb2 and lb2 as lb3 here
1. 
2. 
3. 
4.
5. openstack loadbalancer set lb3 --description lblb3
6. openstack loadbalancer set lb2 --description test
7.  openstack loadbalancer set lb2 --description ""
=> STACK-1612: Handled case for None description while creating lb

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
Modified template key for terminated https listener sothat no terminated https listeners can be created without any issue.
https://a10networks.atlassian.net/browse/STACK-1648
- Changed the key of template_args for HTTPS listener from `template_key` to `template_client_ssl`, 
As we are not supporting shared template feature in this case, template_key is not expected to be here.
Test Case from the bug.
Created TERMINATED_HTTPS listener without getting the error specified in the bug.
=> [BUG][STACK-1648]: Resolved an issue occurred during creating Terminated HTTPS listener.

a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_service_group_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
- Severity Level : Medium
- When `use_shared_for_template_lookup` flag is set **True** while doing configs on shared partition, it was giving error for shared-templates' fields.
https://a10networks.atlassian.net/browse/STACK-1645
- When `use_shared_for_template_lookup` is to be enabled, there is a check to verify if the current partition is not shared.
- If current partition is not shared, then template_key is set to respective "{template_type}-shared" by shared_template_modifier().
- If current partition is shared, then template_key is used as it is declared before.
1. For listener:
When use_shared_for_template_lookup = True with current active partition as **l3v partition**, then:
- For template "template-virtual-port", template-virtual-port-shared is getting attached
- For template …
=> [BUG][STACK-1645]: Adding current partition check while using "use_shared_for_template_lookup" flag for attaching shared templates

a10_octavia/common/data_models.py, a10_octavia/common/utils.py
**Feature**
- Added config support for `ve_ip_address` at device level under `[hardware_thunder]`.
https://a10networks.atlassian.net/browse/STACK-1634
https://a10networks.atlassian.net/browse/STACK-1661
- Added `ve_ip_address` param to `DeviceNetworkMap` data model
- Supported `ve_ip_address` in `utils.py` and validated the partial octets. 
<pre>
[hardware_vthunder]
devices=[
{
"ip_address" : "X.X.X.X",
"device_name" : "rack_1",
"device_1": {
"vcs_device_id": 1,
"mgmt_ip_address": "10.0.0.81",
<b>"ve_ip_address": ".10",</b>
"ethernet_interfaces": [
{
"interface_num": 1,
"vlan_map": [
{"vlan_id": 12, "ve_ip" : ".23"}
]
}]
}}]
</pre>
- `[hardware_thunder]` now accepts `ve_ip_address`
None
=> [Stack-1634][Stack-1661] Added VE IP configuration support at device level.

a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
- When a listener and pool are created by enabling `use_shared_for_template_lookup` flag and then pool is deleted by disabling `use_shared_for_template_lookup`, it was throwing error due to ListenerUpdate task.
- When a listener is created by enabling `use_shared_for_template_lookup` and pool is created by disabling `use_shared_for_template_lookup`, then the shared templates attached to listener were getting replaced by the l3v templates due to ListenerUpdate after disabling the flag.
- So for resolving above 2 bugs, a new task **ListenerUpdateForPool** is added here.
https://a10networks.atlassian.net/browse/STACK-1650
https://a10networks.atlassian.net/browse/STACK-1652
- Added a new task **ListenerUpdateForPool** for updating listener only when creating and …
=> [BUG][STACK-1650][STACK-1652]: Added a new task for handling Pool delete and create in case of shared templates feature.

a10_octavia/common/utils.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/unit/common/test_config_types.py, a10_octavia/tests/unit/common/test_utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
**Bug**
- Severity Level :**Critical**
- Fixed hmt logic for LB and its sub resources. 
- Delete was showing issues, as api calls were made to wrong partitions.
- LB sub-resources should be created in LB partition regardless of use_parent_partition flag.
https://a10networks.atlassian.net/browse/STACK-1510
https://a10networks.atlassian.net/browse/STACK-1620
- Shifted hmt logic from task `GetVThunderByLoadBalancer` to db task `CreateRackVthunderEntry` ensuring correct partition_name is stored in `vthunders` table.
- Added return value to `CreateRackVthunderEntry` for writing test cases for them.
- Refactored `utils.py` module for hmt logic, modified hmt conditions
- Shifted UTs of `GetVThunderByLoadBalancer` to call `CreateRackVthunderEntry` for partitions.
- Removed …
=> [STACK-1510][STACK-1620] : Fixed hierarchical multitenancy logic when use_parent_partition is True or False

a10_octavia/controller/worker/tasks/persist_tasks.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
1. Terminated HTTPS was broken by PR#199 due to lack of protocol mapping
2. HandleSessionPersistenceDelta revert task tried to access session persistence even when it was confirmed to exist. Moving it inside of the try block allows failures to propogate
[STACK-1665](https://a10networks.atlassian.net/browse/STACK-1665)
Leveraged protocol mapping to turn "TERMINATED_HTTPS" -> "https"
N/A
N/A
```
openssl genrsa -des3 -out ca.key 1024 
openssl req -new -x509 -days 3650 -key ca.key -out ca.crt  
openssl x509  -in  ca.crt -out ca.pem 
openssl genrsa -des3 -out ca-int_encrypted.key 1024 
openssl rsa -in ca-int_encrypted.key -out ca-int.key 
openssl req -new -key ca-int.key -out ca-int.csr -subj "/CN=ca-int@acme.com" 
openssl x509 -req -days 3650 -in ca-int.csr -CA ca.crt …
```
=> [STACK-1665]: HOTFIX for PR#199

a10_octavia/controller/worker/tasks/virtual_server_tasks.py
- Removing the existing strip logic of description sothat description should not get stripped through the `virtual_server_task.py` code for now.
- Note: Even if stripping logic is removed from here, description with leading and trailing spaces are getting stripped on vThunder side as it's getting handled from somewhere else.
https://a10networks.atlassian.net/browse/STACK-1612
https://github.com/a10networks/acos-client/pull/294
- Setting description to "" if it is arrives as multiple spaces.
- Otherwise setting it to as it is arriving.
All the testcases from the bug.
Refer https://github.com/a10networks/a10-octavia/pull/191 for detailed testcases.
=> [BUG][STACK-1612]: Removed the existing strip logic added for loadbalancer's description

a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
- While updating pool with l3v templates, listener's shared templates were also getting updated with l3v ones because of disabling use_shared_for_template_lookup flag while ListenerUpdate.
So added the new task ListenerUpdateForPool in pool update flow to resolve this issue.
https://a10networks.atlassian.net/browse/STACK-1667
- Added a new task ListenerUpdateForPool for updating listener only when updating a Pool
- By this task, Listener will not be affected due to any config changes done while Pool update.
- Added unit tests for the newly added ListenerUpdateForPool task.
- Tested the test-cases specified in the bug.
=> [BUG][STACK-1667]: Added ListenerUpdateForPool task in pool-update flow to fix the issue.

a10_octavia/common/utils.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/common/test_utils.py
- If hierarchical-multitenancy is enabled, the partition should be set to the current project partition specified in config file instead of setting it to "shared".
https://a10networks.atlassian.net/browse/STACK-1670
- If hierarchical-multitenancy is enabled, set vthunder partition name to the first 14 digits of project_id present in config file.
- If hierarchical-multitenancy is enabled, partition_name of vThunder should be the first 14 digits of the project_id specified in config file.
admin has child project child2_admin.
**Step1**: Set **use_parent_partition=True** & **"hierarchical_multitenancy": "enable"**, **project_id: project_id of child2_admin**
**Step2**: Create a loadbalancer lcc1 with project child2_admin
stack@neha:~$ openstack loadbalancer create …
=> [BUG][STACK-1670]: Set partition name to current project partition when hierarchical multitenancy is enabled

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
Updated the tasks "HandleVRIDFloatingIP"  and "UpdateVRIDForLoadbalancerResource" in order to handle the multi subnet VRID FIP updates.
https://a10networks.atlassian.net/browse/STACK-1673
- Recognized the tasks need to updated in -order to handle the requirement.
- Added changes for adding changes of VRID FIP to VRID fetched from DB
- On the basis of changes from "HandleVRIDFloatingIP" changed "UpdateVRIDForLoadbalancerResource".
- Single VRID LB
- Single VRID member (same subnet)
- Muluplr member, same subnet
- SIngle VRID member (differenr subnet)
- Muluplr Member (differenr subnet)
- multiple SLB, same subnet
- multiple SLB, differenr subnet
- Delete LB scenario
- .Delete member scenario
-  
- Muliple LB, change IP static to static, update (octet IP provided)   - redo for member
-  
- …
=> [STACK-1588A]: Update UpdateVRIDForLoadbalancerResource db task for updating multiple VRIDs fetched from HandleVRIDFloatingIP.

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Allowing to create another(second) load balancer of a different project(child2_project) under same partition(parent partition) when there is already a load balancer with different project(child1_project) under same partition(parent partition) exists.
https://a10networks.atlassian.net/browse/STACK-1669
- Shifted hmt logic from task `CreateRackVthunderEntry` to task  `CheckExistingProjectToThunderMappedEntries` ensuring correct partition_name is stored for vthunder_config.
- Returning the correct `vthunder_config` from `CheckExistingProjectToThunderMappedEntries` and using it in further tasks(`CheckExistingThunderToProjectMappedEntries` and `CreateRackVthunderEntry`) by modifying the flows `get_create_rack_vthunder_load_balancer_flow` and …
=> [BUG][STACK-1669]: Fixed an issue for creating another LB on a different project under same parent partition

a10_octavia/controller/worker/tasks/virtual_server_tasks.py
- Adding quotes around the loadbalancer description sothat there will be sync between OpenStack side and vThunder side for any description with having leading or trailing spaces to it.
https://a10networks.atlassian.net/browse/STACK-1690
- If there is no description parameter provided while creating a loadbalancer, then None will be set as the description and there will not be any description associated with the loadbalancer on both sides.
- If description provided while creating a loadbalancer is "      " or "", then there will not be any description associated with the loadbalancer on both sides.
- Otherwise any other description will get associated exactly same as that of provided while loadbalancer creation, wrapped in quotes(""), on both sides. 
Testcases required for this story:
=> [STACK-1690]: Wrapping up loadbalancer description into quotes.

a10_octavia/controller/worker/tasks/a10_network_tasks.py
If VRID not present at vthunder and tried to create LB, LB state going into pending_create state.  
https://a10networks.atlassian.net/browse/STACK-1693
- Looked into the error log, checked the stack trace, and recognized the issue.
- Added the changes in revert of HandleVRIDFloatingIP
Steps: 
1.  Changed the VRID value to which the channel is not created in vThunder.
2. Created LB, checked the status, and log for error message getting displayed.
=> [STACK-1693]: [vrid] non-existed vrid will cause lb in pending_create status

a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py, tox.ini
Severity: High
Templates could not be removed during object updates. To address this problem, a replace method has been implemented on the acos-client side for objects affected by the bug.
Not all update tasks require a replace. For example, the UpdateListenerForPool shouldn't strip the templates of the listener just ensure that the pool is associated to the listener.
[STACK-1647](https://a10networks.atlassian.net/browse/STACK-1647)
[STACK-1651](https://a10networks.atlassian.net/browse/STACK-1651)
[PR 305 in acos-client](https://github.com/a10networks/acos-client/pull/305)
- Converted update calls into replace calls for Update taskss
- Added ListenerUpdateForPool to PoolUpdate flow so that listener templates are overwritten during pool update
N/A
1. Set a template for object in config
2. …
=> [STACK 1647][STACK-1651] Add replace methods to address template overwrite needs

a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Severity Level : High
- Only one ve ip is assigned from openstack dashboard port list during hmt logic or any partition specific.
- https://a10networks.atlassian.net/browse/STACK-1692
seems to be resolving [STACK-1668](https://a10networks.atlassian.net/browse/STACK-1668)
- Debugged and found that network create port logic not getting executed because interface information was not getting fetched properly from the concerned partition.
None
a) network_type = `vlan`
-  Keep `hierarchical_multitenancy` as `enabled` and `use_parent_partition` as `True` and child project id in config.
- Add vlan_map for device_1 and device_2.
- Create loadbalancer using child project id.
- Check on openstack dashboard > Network (subnet where vlan is created)> Port and observe ve_ips are all there.
Follow the …
=> [BUG][STACK-1692] : Added activate_partition logic for Blade vThunder.

a10_octavia/common/exceptions.py, a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/tests/unit/common/test_utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
1. When a VRID was specified with a partial IP of 0.0.25.105 and added to a subnet of 10.11.12.0/24 no error was thrown.
2. Only the /24 CIDR form was working as the last octet would always be fully replaced.
- ie specifying `3.45` for subnet `10.0.2.0/23` would result in `10.0.2.45` instead of `10.0.3.45`
This PR only fixed the issue for VRID. The issue is also present in VE IP; however, it was not pursued in this PR due to heavy refactor occurring in VE IP branch.
[STACK-1677](https://a10networks.atlassian.net/browse/STACK-1677)
- If a full static IP is specified for the VRID then we simply check that it is a valid IPv4 address and then check that it is in subnet range.
- If a partial IP address is provided then the following occurs:
1. The partial IP has it's …
=> [STACK-1677] Fixed VRID partial IP behavior

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Required:
STACK-1687: 
1. Admin has 2 child projects cadmin and ccadmin,  Set project as ccadmin, with HMT enabled and use parent partition 
2. Create lb “lcc1”, it will be created in admin project partition with VRID FIP as expected. 
3. Change project to cadmin, created LB "lc1" an equivalent virtual server is created but VRID FIP is not created
STACK-1691:
From STACK-1687 bug, when created LB i.e, "lc1" is deleted it removes the VRID FIP associated to subnet used to create LB "lcc1"
https://a10networks.atlassian.net/browse/STACK-1687
https://a10networks.atlassian.net/browse/STACK-1691
- Analysed the a10-octavia config file to understand the HMT and use the parent partition settings.
- Updated "GetVRIDForLoadbalancerResource" as below, 
IF HMT is "enabled" and …
=> [BUG][STACK-1687][STACK-1691]: Fixed LB component creation and deletion when HMT settings enabled.

a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_service_group_tasks.py
Severity: Critical
When using the `set` command to update an object, a replace method is called which uses the PUT operation to send a payload. The object on the device is fully overwritten by the contents of this payload, so if the reference objects aren't included then they are removed.
Ex: Virtual server vs1 has a listener l1. When a replace is called without l1 in the port list, then l1 is disassociated from vs1.
[STACK-1699](https://a10networks.atlassian.net/browse/STACK-1699)
[STACK-1703](https://a10networks.atlassian.net/browse/STACK-1703)
[PR#206 of acos-client](https://github.com/a10networks/acos-client/pull/306)
To fix the issue, a GET call is used to access the contents of the object from which the reference objects are extracted. These objects are then added to the payload …
=> [STACK-1703][STACK-1699] Replace methods cause overwrite of connected objects

a10_octavia/common/exceptions.py
Error message was wrong. It was falling back to the default instead of provided error message.
[STACK-1708](https://a10networks.atlassian.net/browse/STACK-1709)
- Changed error message from being pased as a kwarg to a positional arg
N/A
N/A
1. Set wrong vrid_floating_ip in either [a10_global] or in project
2. openstack loadbalancer create --name test_vip_2 --vip-subnet-id provider-vlan-11-subnet --project project_a
Expected Result:  VRIDIPNotInSubentRangeError: Invalid VRID floating IP specified. VRID IP <Config IP> out of range for subnet <subnet ip>
=> Changed error message from being pased as a kwarg to a positional arg

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Required: Issue: The VRID feature is not built by keeping HMT and use parent partition in mind. Previously the consideration was user mapped with project and project is mapped to partition so the VRID list from DB, LB count for the subnet and, member count subnet are fetched based on a project which caused issues when the partition is shared among projects. 
Now with this PR, we use to partition and the projects using that partition for fetching VRID list, LB count, and member count. 
https://a10networks.atlassian.net/browse/STACK-1691
- Recognized the other cases of failure like member delete, LB delete and pool delete.
- With previous PR we fixed the issue fo LB and member creation. 
- Through bug STACK-1691, we recognized the fetch VRID list, LB count, member …
=> [BUG][STACK-1691]: [vrid_floating_ip] different subnet vrid_floating_ip is deleted wrongly

a10_octavia/controller/worker/tasks/a10_network_tasks.py
1. If vThunder object is available as None in database, the VRID task fails to delete LB and POOL in error state.
2. If VRID is not configured, pool delete fails if multiple members are being deleted, as VRID_LIST is coming empty
This does not contain any bug for now, as its high priority
- Added check for vthunder object
- Added check if vrid list is empty then avoiding further flow
PART A: When deleting LB in ERROR state
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | provider |
+--------------------------------------+------+----------------------------------+-------------+----------------- …
=> Handled vthunder as None case in VRID Story

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
When using hierarchical multitenancy, objects in error state cannot be removed as a db query was returning None.
[STACK-1716](https://a10networks.atlassian.net/browse/STACK-1716)
- Removed query causing the issue. Replaced query with already present vthunder argument
- Added handling for None / empty returns expected for an object in error state
N/A
N/A
```
[a10_global]
use_parent_partition = True
use_shared_for_template_lookup = True
vrid_floating_ip = 25
[service_group]
#template_port = test_port
#template_policy = test_policy
[listener]
#template_virtual_port = none
#template_http = test_http
#autosnat = True
devices = [
{
"project_id": "0e567ea4ea824228b06fce04805c8c16", …
```
=> Added handling for removal of object in error state

a10_octavia/common/config_options.py
- Added Database connection config support to `a10-octavia.conf`.
https://a10networks.atlassian.net/browse/STACK-1717
- Registered `a10_database` section to config options.
- Added `connection_url` config support inside this section.
<pre>
[a10_database]
connection_url = mysql+pymysql://root:password@127.0.0.1:3306/a10-octavia
</pre>
- None
- None
(Note: Not able to test it since all the code is not in place.)
=> [STACK-1717] Added [a10_database] section support to a10-octavia.conf

a10_octavia/db/migration/alembic_migrations/versions/ea8bfcbd654c_modified_hmt_column_to_accept_only_.py, a10_octavia/db/models.py, tox.ini
The sqlalchemy_utils library's custom datatypes are incompatible with 
[STACK-1730](https://a10networks.atlassian.net/browse/STACK-1730)
- Modified revision to change from Boolean to String instead of Boolean to ChoiceType
N/A
N/A
Requirements: RDO on CentOS with MariaDB as the database type
```
cd a10-octavia/a10_octavia/db/migration
alembic downgrade 4028e5f7a198
```
Expected result: Downgrade successful
```
cd a10-octavia/a10_octavia/db/migration
alembic upgrade head
````
Expected result:
```
MariaDB [octavia]> show columns from vthunders;
+---------------------------+---------------+------+-----+---------+----------------+
| Field                     | Type          | Null | Key | Default | Extra          | …
```
=> [STACK-1730] Removed sqlalchemy_utils to support MariaDB

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/server_tasks.py
-  Severity Level  **Critical**
- Any set command to `member` was removing the port configuration.
https://a10networks.atlassian.net/browse/STACK-1755
- While debugging found that port setting is taken care by `service_group.member.create()` api of acos-client.
- Added api call for creating port and associating with service_group after replace call on server
None
- Required: List edge cases tested against in unit tests 
1. Create LB, Listener and pool
2. Create member with following configuration of `[server]` of `a10-octavia.conf`
```
conn_limit=11000000
conn_resume=899999
template_server=tp_server
```
`openstack loadbalancer member create --address 10.0.12.195 --subnet-id bb62cec6-6135-4066-aec5-ec59ec58c2ce --protocol-port 80 --name member1 pool1`
Output on vthunder: 
``` …
```
=> [BUG][STACK-1755] Setting member removed the ports

a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
- Issue Description: member creation failing, since for adding vrid data into table there was an issue related to id.
https://a10networks.atlassian.net/browse/STACK-1751
- Checked the code for member creation. 
- Discovered an issue while adding new VRID if vrid not present for a given subnet. we were specifically generating UUID for id of VRID object.  
- No required
- Created load balancer with subnet-1.
- Created member in subnet-2
- Created member in subnet-3
- Created member in subnet-3
[NOTE]: Was able to create members when changes checked out on centos and on development machines as well. But anyway the UUID changes were not required there.
=> [BUG][centos_member][STACK-1751]: creating member will see some database error in log.

a10_octavia/controller/worker/tasks/server_tasks.py
Whenever members are updated, the real server ports are removed from associated server objects. This has the extra effect of removing the member object from the service group.
[STACK-1755](https://a10networks.atlassian.net/browse/STACK-1755)
[STACK-1737](https://a10networks.atlassian.net/browse/STACK-1737)
- Added get call for port-list so that real server ports are obtained
- Reverted previous code change which attempted to resolve STACK-1755
[acos-client PR#308](https://github.com/a10networks/acos-client/pull/308)
N/A
N/A - No testable logic. Just a single get call more or less.
```
openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name lb1 --project project_a
openstack loadbalancer listener create --protocol HTTP --protocol-port 8080 …
```
=> [STACK-1755][STACK-1737] Obtained server ports before preforming replace to preserve them

a10_octavia/common/data_models.py, a10_octavia/db/models.py, a10_octavia/tests/unit/common/test_data_models.py
Added data models for supporting new a10-octavia database.
Main Story : https://a10networks.atlassian.net/browse/STACK-1177
https://a10networks.atlassian.net/browse/STACK-1777
https://a10networks.atlassian.net/browse/STACK-1779
https://a10networks.atlassian.net/browse/STACK-1780
https://a10networks.atlassian.net/browse/STACK-1781
https://a10networks.atlassian.net/browse/STACK-1783
- Modified data_models.py by refactoring BaseDataModel class in it.
- Set all parameters to None by default in all data models.
- Added a data model for AmphoraMeta, Partitions, Interfaces (EthernetInterface and TrunkInterface), Thunder, ThunderCluster.
- Converted old `Thunder` to `ThunderV1`.
- Added UTs for all data models.
Note: We are not touching old models , to avoid more UT failures, however as we move …
=> STACK-1714: New Data Models to support new a10-octavia database.

a10_octavia/db/api.py
Now we can get sessions from both `a10_octavia` and `octavia` db for connecting to different repositories.
This is part of a large db migration story.
https://a10networks.atlassian.net/browse/STACK-1816
- Added seperate method `get_a10_session()` to get session from `a10_octavia` db similar to `octavia`.
None
- Whenever `get_a10_session()` is called via db apis, we will get a10_octavia db session and further CRUDS operation is possible to repositories existing inside this database.
- Removed unused method.
a) Be connected to `a10_octavia` database using `[a10-database]` section config on `a10-octavia.conf`, restart the service.
b) For manual testing, I modified a file `a10_octavia/controller/worker/tasks/a10_vthunder_db.py` to use `get_a10_session()`
c) Created Class object and called …
=> [New-DB] Added support for getting engine for a10_octavia db

a10_octavia/controller/worker/flows/a10_health_monitor_flows.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_health_monitor_tasks.py
flavor and name-expr logic to health monitor
STACK-1799 Add name-expr and flavor logic to healthmonitor tasks
flavor shows below:
<pre>
<b>{
"health-monitor":{
"monitor":{
"retry":5,
"method":{
"http":{
"http-response-code":"201"
}
}
},
"name-expressions":[
{
"regex":"hm1",
"json":{
"monitor":{
"timeout":8,
"method":{
"http":{
"http-host":"my.test.com"
}
}
}
}
}
]
}
}</b>
</pre>
- health monitor global flavor
- health monitor flavor with regex
- health monitor global flavor
- health monitor flavor with regex
=> flavor and name-expr logic to health monitor

a10_octavia/common/data_models.py, a10_octavia/db/migration/alembic_migrations/versions/a6e9b9b69494_add_write_memory_protocol_port_columns.py, a10_octavia/db/models.py
Added **write_memory**, **protocol** and **port** columns in vthunders table which is required for data migration from a10-neutron-lbaas to octavia.
https://a10networks.atlassian.net/browse/STACK-1860
https://a10networks.atlassian.net/browse/STACK-1862
https://a10networks.atlassian.net/browse/STACK-1863
- Added write_memory, protocol and port fields in db/models.py.
- Created an alembic script `a6e9b9b69494_add_write_memory_protocol_port_columns.py` for adding the columns to `vthunders` table.
- Updated the Thunder data model to have the newly added columns in it.
After running `alembic upgrade head`, getting the newly added columns into vthunders table.
=> [STACK-1712][PART1]: Added new columns required for a10-neutron-lbaas data migration.

a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/unit/common/test_utils.py
- Severity Level : **Highest** 
- If `upp` is `True` and `hmt` is `enabled`, failed to create LB for a project having `default` project as its parent.
- If child project is using parent partition, issue arises if parent starts using its own partition.
- https://a10networks.atlassian.net/browse/STACK-1893
- https://a10networks.atlassian.net/browse/STACK-1894
- All projects in openstack by default has `default` as its parent project. 
- Fixed the issue by considering that when parent is `default`, the partition to use will be the project's itself.
- Also fixed  to **not** throw `ProjectInUseByExistingThunderError` error, if the existing partitions created in vthunders (currently getting used by child project)  will also be accessed by the owner (parent project), regardless of **[upp+hmt]** …
=> [STACK-1893][STACK-1894]: Fixed latest HMT behavior issues

a10_octavia/a10_config.py, a10_octavia/common/config_options.py, a10_octavia/db/migration/alembic_migrations/env.py, a10_octavia/db/migration/alembic_migrations/versions/4fa8c3867dcb_a10_device_instance_to_vthunders.py, a10_octavia/etc/defaults.py
Migrating data from a10-neutron-lbaas's a10_device_instances table to octavia's vthunders table by getting database connection of a10-neutron-lbaas through config file
https://a10networks.atlassian.net/browse/STACK-1866
https://a10networks.atlassian.net/browse/STACK-1864
https://a10networks.atlassian.net/browse/STACK-1865
https://a10networks.atlassian.net/browse/STACK-1891
- Added support for **neutron_connection_url** by adding it to `defaults.py` and `config_options.py`
- Getting **neutron_database_connection** from config to data-migration script by adding respective code for it in `a10_config.py`
- For this, added methods `get_a10_octavia_conf()` to get the `a10-octavia.conf` path and added another method `_get_neutron_db_string` to get `neutron_connection_url` from it
- Written data …
=> [Data-Migration with Config support][STACK-1866]: Data migration from a10-neutron-lbaas to octavia with config support

a10_octavia/a10_config.py, a10_octavia/common/exceptions.py, a10_octavia/db/migration/alembic_migrations/versions/4fa8c3867dcb_a10_device_instance_to_vthunders.py, a10_octavia/db/migration/cli.py
Added the support for using "a10-octavia-db-manage" utility for data migration from a10-neutron-lbaas to Octavia. This utility provides the provision to accept DB string through CLI.
https://a10networks.atlassian.net/browse/STACK-1895
- Worked on the investigation of providing DB name through CLI.
- Checked alembic doc to understand the passing of external context to migration script.
- Accessed the DB UL passed to config context.
- Used the DB URL fetched from config context to get the data from a10-neutron-lbaas DB.
Test 1: Tested the DB migration by providing DB URL in config.
Test 2: Tested the DB migration by removing DB URL from config(DB from CLI also not provided)
Test 3: Tested DB migration by providing DB URL from CLI through a10-octavia-db-manage utility.
Test 4: Tested DB …
=> [STACK-1895]: Added provision for data migration using "a10-octavia-db-manage" utility(DB string provided through CLI).

a10_octavia/cmd/a10_house_keeper.py, a10_octavia/common/config_options.py, a10_octavia/controller/housekeeping/house_keeping.py
- Added config support for Write memory thread in houseKeeper service
- https://a10networks.atlassian.net/browse/STACK-1945
- https://a10networks.atlassian.net/browse/STACK-1942
- https://a10networks.atlassian.net/browse/STACK-1941
- https://a10networks.atlassian.net/browse/STACK-1940
- https://a10networks.atlassian.net/browse/STACK-1957
- Added configs like `disable_write_memory`, `write_mem_interval`, `write_mem_expiry_time` 
```
disable_write_memory (boolean, default=False): User can set this to True, If they don’t want housekeeper to perform write memory feature. 
write_mem_interval (seconds, default and min =3600 ie 1 hour) : interval to wait before performing write memory operation on thunders. 
write_mem_expiry_time(seconds, default and min=3600 ie 1 hour) : helps in maintaining a …
```
=> [Write-Memory-Enhancement] Added write memory related configs in house_keeping service

a10_octavia/controller/worker/tasks/nat_pool_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_nat_pool_tasks.py
For given nat-pool-list flavor, NAT pool will be created on Thunder when loadbalancer is created.
https://a10networks.atlassian.net/browse/STACK-1900
- When nat-pool-list flavor or both nat-pool and nat-pool-list is passed while creating a loadbalancer:
- if the specified nat-pool with the same range does not exists on thunder, the nat-pool given in the flavor gets created.
- if the specified nat-pool with the same range exists on thunder, the nat-pool will not get created on thunder as it already
exists.
- if the specified nat-pool with the different range exists on thunder, an error will be raised with a message as "The nat-pool
already exists on thunder".
- Given a nat-pool-list flavor, when a loadbalancer is created, the nat-pool will get created on thunder if the same nat-pool does …
=> STACK-1900: Creation of nat-pools in nat-pool-list flavor

a10_octavia/controller/worker/tasks/policy.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_policy.py
- Issue Description: there is aflex command about http path on thunder, that is HTTP::path, so when we created l7rule with type PATH, QA suggest to use http::path instead of http::uri.
https://a10networks.atlassian.net/browse/STACK-1818
- Checked manual for both HTTP::path and HTTP::uri
- Replaced HTTP::uri to HTTP::path.
- created L7 rule with type as path and checked the output from ruleparser which generated l7 policy.
- Created L7rule with type PATH and checked on thunder for the equivalent aflex script.
=> [STACK-1818]: Used HTTP::path instead of HTTP::url for L7 rule creation. 

a10_octavia/cmd/a10_house_keeper.py, a10_octavia/common/a10constants.py, a10_octavia/common/config_options.py, a10_octavia/controller/housekeeping/house_keeping.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_health_monitor_flows.py, a10_octavia/controller/worker/flows/a10_l7policy_flows.py, a10_octavia/controller/worker/flows/a10_l7rule_flows.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
- Added controller worker linear flow to perform write memory when enabled.
https://a10networks.atlassian.net/browse/STACK-1947
https://a10networks.atlassian.net/browse/STACK-1948
https://a10networks.atlassian.net/browse/STACK-1958
https://a10networks.atlassian.net/browse/STACK-1959
https://a10networks.atlassian.net/browse/STACK-1946
https://a10networks.atlassian.net/browse/STACK-1950
https://a10networks.atlassian.net/browse/STACK-1951
https://a10networks.atlassian.net/browse/STACK-1952
https://a10networks.atlassian.net/browse/STACK-1953
https://a10networks.atlassian.net/browse/STACK-1954
https://a10networks.atlassian.net/browse/STACK-1955
- housekeeper will fetch "eligible" thunders after every configured write_mem_interval of time from vthunder db 
- thunders are filtered again based on …
=> [Write-Memory-Enhancement]: Added controller worker flow for write memory operation

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- As per review comment on https://github.com/a10networks/a10-octavia/pull/268/files#r549871738
Needed to lock associated ACTIVE LB's to PENDING_UPDATE before doing write_memory operation. This ensures, no other threads are performing any configuration over those LBs.
https://a10networks.atlassian.net/browse/STACK-1991
https://a10networks.atlassian.net/browse/STACK-1992
```
1. Fetch All Active LBs associated to Thunder from db
2. Set `PENDING_UPDATE` status in db for all lbs.
3. After `WriteMemoryHouseKeeper` task, set status back to `ACTIVE` for all lbs.
4. Added corresponding UTs.
```
None
- UTs.
None
=> [Write-Memory-Enhancement]: Added new tasks for locking LBs to PENDING_UPDATE

a10_octavia/common/config_options.py
Setting minimum configuration as `300` seconds for `[a10_house_keeping]` ->`write_mem_interval`
https://a10networks.atlassian.net/browse/STACK-1976
- Setting `min` value as `300` in config_options for `write_mem_interval`
<pre>
<b>write_mem_interval = 300</b>
</pre>
- Setting `write_mem_interval ` as 300 or greater than that.  - Success
- Setting `write_mem_interval `  less than 300 - Error
- Set above config in `a10-octavia.conf` and restart `a10-house-keeper.service`
- Check LOGS : `sudo journalctl -af --unit a10-house-keeper.service`
=> [STACK-1976] Set min value for write_mem_interval

a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py, test-requirements.txt
Added some template under [listener] in config file, found there is no http template bound to listener of terminated_https, but if creating http listener, the http template will be configured under vport http.
Severity Level High
https://a10networks.atlassian.net/browse/STACK-1686
- Change the sequence of condition checks 
- Given https listener in shared partition then template_http is attached.
- Given https listener in l3v partition  then template_http_shared is attached
Step 1: Manually created some templates on thunder
Step 2: Added template under [listener] in config file.
[listener]
ipinip=False
no_dest_nat=False
#ha_conn_mirror=False
template_virtual_port=tp_vport
template_tcp=tp_tcp
template_policy=tp_policy
autosnat=False
conn_limit=10980
template_http=tp_http <<<---------- …
=> [Bug][STACK-1686]:Added http template for terminated https listener

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py
fix PR review comments for https://github.com/a10networks/a10-octavia/pull/281
Feature Requirements 
- Requires SNAT Pools to be allocated from Neutron 
- Frequent changes to these pools will occur 
- Restarting configuration file is tedious and can interrupt DevOps tooling workflow 
- Shouldn’t require SNAT Pool to be pre-defined on the ACOS device 
- Adds snat pool option to flavor schema for loadbalancers and can be shared between loadbalancers 
Design Document: https://teams.microsoft.com/l/file/27F4222F-7CDD-421B-8F0C-97A5C60B2B5D?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2FSNAT%20Pools%2FSNAT%20Pools%20Design%20Document.docx&baseUrl=htt …
=> STACK-1896 Feature Source NAT flavor support

a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_health_monitor_tasks.py
1. 'method' axapi argument in flavor should not merge with other flavor (when 2 or more flavor is matched). Since different protocol and method has different axapi keys, merge them together will not work.
2. For HM flavor,  user should not need to encapsulate axapi arguments in 'monitor'. Like other slb objects, a10-octavia should do it for user.
for example:
for flavor-data
```
{
"health-monitor" : {
"monitor":{
"retry":5,
}
}
}
```
user should just use:
```
{   
"health-monitor":{
"retry":5,
}
}
```
https://a10networks.atlassian.net/browse/STACK-2009
1. For health monitor flavor, user should not need to encapsulate axapi arguments in 'monitor'. Like other slb objects, a10-octavia should do it for user.
2. Don’t for multiple matched flavors, …
=> STACK-2009 Bug hm flavor issues

a10_octavia/controller/worker/tasks/nat_pool_tasks.py
Listener creation was failing when nat-pool flavor is not used.
https://a10networks.atlassian.net/browse/STACK-2012
- Executing revert of NatPoolCreate task only when flavor-data is passed while listener creation.
Create a loadbalancer without any flavor passed to it.
openstack loadbalancer create --name v11 --vip-subnet-id provider-vlan-11-subnet
Create a listener.
openstack loadbalancer listener create --protocol http --protocol-port 80 --name l1 v11
Result:
Listener l1 created successfully.
=> [BUG][STACK-2012]: Fixed an issue during listener creation without nat-pool flavor

a10_octavia/controller/worker/tasks/policy.py, a10_octavia/tests/unit/controller/worker/tasks/test_policy.py
Previously added changes for resolving STACK-1818  are required for L7rule type "PATH" but changes were reflecting for type "FILE_TYPE". Due to this for type "FILE_TYPE" the rule string was using "[HTTP::path]" instead of "[HTTP::uri]"
Check the comments for STACK-1819,
https://a10networks.atlassian.net/browse/STACK-1819
- Checked URI specification to know about path part of URI
- Reverted the changes done for type "FILE_TYPE"
- Checked l7 rule for TYPE "FILE_TYPE" and compare type "REGEX".
- TYPE "FILE_TYPE" and compare type "EQUALS_TO"
- Created L7 rule for TYPE "FILE_TYPE" and compare type "REGEX".
- Created l7 rule for TYPE "FILE_TYPE" and compare type "EQUALS_TO"
- Created l7 rule for TYPE "PATH" and  compare type "ENDS_WITH"
=> [BUG][STACK-1819]: For L7rule type "FILE_TYPE", the rulestring is getting created with "[HTTP::path]" instead of [HTTP::uri]

a10_octavia/controller/worker/tasks/server_tasks.py
- Issue description: Created a member and real port to it by flavor including port-list to it, then set member is making real port config lost.
https://a10networks.atlassian.net/browse/STACK-1996
- Removed an api call made for creating a server-port `self.axapi_client.slb.server.port.create` , as `self.axapi_client.slb.server.create` is creating the server-port as per the configurations passed to it by flavor via server_args passed to it.  `self.axapi_client.slb.server.port.create` is trying to create the port with same port and protocol again even after the port creation is done by `self.axapi_client.slb.server.create`
- Also removing the api call made for updating the server-port `self.axapi_client.slb.server.port.update` , as it is overriding the port …
=> [BUG][STACK-1996]: Fixed issue of losing real port configurations after setting the member

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, tox.ini
Severity level: High
Issue Description: When the same partition name is used to create LB or member in different clusters, then the VRID FIP from the first cluster gets duplicated to another cluster when we create LB or member in that other cluster.
https://a10networks.atlassian.net/browse/STACK-1791
- Checked the query to fetch projects for a specific partition.
- Added IP-address to the query to fetch project for a partition.
- Tested the creation of LBs on different vthunders with the same partition name.
- Tested deletion of LBs on different vthunders with the same partition name.
- Tested creation of members in different vthunders with the same partition name.
- Tested deletion of members in different vthunders with the same partition name.
=> [BUG][STACK-1791][vrid_floating_ip for 2 thunder clusters] the vrid_floating_ip are mixed for 2 thunder clusters

a10_octavia/db/repositories.py
- Severity Level : **Highest**
- Issue Description : After deleting last LB, the corresponding `vthunders` record in db was getting deleted by Housekeeper's DB Cleanup thread unexpectedly. As a result, HouseKeeper's Write memory was not able to perform write memory on that vthunder.
https://a10networks.atlassian.net/browse/STACK-2028
- It is expected from HouseKeeper's DB cleanup thread to by default consider a `DELETED` status `vthunders` to be expired only after `7 days`, but this was not happening.
- Found that, `query` filter was getting reset while fetching `expired` vthunders in `get_all_deleted_expiring`. Fixed this
None
Configs: 
```
```
```
1. Create an LB and delete it after some time keeping above …
```
=> [Bug][STACK-2028]: Removed unwanted variable initialization for HK db cleanup thread

a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/decorators.py
- Severity Level : **Medium**
- Description: Getting `400  Bad Request : Communication error with LB process` on l3v partition while doing periodic write memory by HK.
- Also resolves `Duplicate: Atoms with duplicate names found`
https://a10networks.atlassian.net/browse/STACK-2031
https://a10networks.atlassian.net/browse/STACK-2045
- This is due to while performing `write memory partition shared` in l3v partition which doesn't allow this.
according to https://a10networks.atlassian.net/browse/STACK-2031?focusedCommentId=462195
- Hence need to switch to `shared` partition before making write memory api call
- Earlier decorator `activate_partition` based on `vthunder.partition` and return `axapi_client`. But to make explicit api call to `shared` partition despite different …
=> [Bug][STACK-2031] : Activate shared partition using use_shared_partition flag in decorator

a10_octavia/controller/worker/tasks/l7policy_tasks.py, a10_octavia/controller/worker/tasks/l7rule_tasks.py
Severity level: high
Description: When l7policy is created, the vport name will be changed to listener's name replacing listener's ID used as name.
https://a10networks.atlassian.net/browse/STACK-1754
- Changed the name to ID for axapi requests.
- Created l7 policy for listener and observed listener's name.
- Deleted the same l7 policy.
- Create l7rule for listener and observed the listener's name.
- Deleted l7rule for listener 
Note: After doing these changes, unable to delete l7 policy giving an error "ACOSException: 17039364 This aFleX is in use", fixed this issue by replacing the update to replace the call.
=> [BUG][STACK-1754] [l7poicy_listener]: creating l7policy for vport:http/http will change vport's name

a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/decorators.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
- Severity Level : **High**
- Description: If `vthunder.partition_name` is `shared`, the `housekeeper`'s `periodic write memory` is called twice on `shared` partition. Need to avoid that.
https://a10networks.atlassian.net/browse/STACK-2038
- Changed the flow sequence of Housekeeper vthunder flows to call write memory on `shared` partition first, then on custom partition if `vthunder.partition_name != 'shared'`
- In  `WriteMemoryHouseKeeper` task, changed condition to prevent calling `shared` partition twice
- Adjusted `decorator` to activate the needed partition during such cases
None
Prerequisite: Keep `use_periodic_write_memory` as `enable`
<pre>
1. Create/Update/Delete an SLB resource in shared partition and check hk-logs --> Write memory should be called only once to shared.
</pre> …
=> [Bug][STACK-2038]: Prevent calling write memory twice on shared partition by HK

a10_octavia/cmd/a10_health_manager.py, a10_octavia/controller/healthmanager/a10_health_manager.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/db/repositories.py
- Severity Level:  Critical
mysql database vthunder table is locked by a10-health-manager service. And db migration will failed and cause unexpected results. The problem cause table lock are:
1. For STANDALONE thunders, a10-octavia will not create heartbeat HM on thunders. So, last_udp_update column will never updated and will always trigger failover.
2. When failover these STANDALONE vthunders, it will failed since no standby device for it. And db session is not closed in failed case.
Another issue is: for ```A10HealthManager.health_check()```, it calls ```get_stale_vthunders()``` to get the first query result.  So, the while loop will always get the same vthunder (which is the first matched one) until  ```len(futs) == self.threads```. …
=> [Bug][STACK-2037] Fix health manger bugs

a10_octavia/common/a10constants.py, a10_octavia/controller/housekeeping/house_keeping.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Description: 
1. Detect thunder reload and mark ERROR for loadbalancers which has lost configration. (STACK-2027)
2. Fix write memroy to multiple thunders problem (STACK-2048)
3. update last_write_mem for all entries for same thunder (same ip-address, partition-name) (STACK-2041)
**See also: https://github.com/a10networks/acos-client/pull/331 for acos-client part changes**
https://a10networks.atlassian.net/browse/STACK-2027
https://a10networks.atlassian.net/browse/STACK-2041
https://a10networks.atlassian.net/browse/STACK-2048
[STACK-2027]
1. Following aXAPI can show a10lb up time, maybe we can use it to compare with update_at to find reloaded/rebooted thunders. ```/axapi/v3/miscellenious-alb/oper```
2. After find reloaded thunders, mark loadbalancers status as …
=> [Bug] [STACK-2027] [STACK-2041] [STACK-2048] thunder reload detection and bugs fix

a10_octavia/controller/housekeeping/house_keeping.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Severity Level: Low
- Issue Description: 
For last_write_mem is NULL case. When the latest config update, we can't make sure a10-octavia is in periodical write memory mode or not. So before we didn't set status to ERROR. Now, the behavior change to:
For new lb, it didn't have last_write_mem yet, so if
- it's latest update is after this service starts, then some config is not save yet. We will do relaod_check for it.
- it's latest update time is before this service starts, then we can't make sure it has config not save or not. Because     periodical write memory may not enabled at that time. We will not do reload_check for it.
https://a10networks.atlassian.net/browse/STACK-2027
1. Store the time house-keeper thread starts
2. use this thread start time to check the latest update time is …
=> [Bug][STACK-2027] For newly created lb, failed to detect config lost and set status to ERROR

a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py
The previous behavior is expected, don't need to change it.
https://a10networks.atlassian.net/browse/STACK-1975
Revert some changes from previous patch
<pre>
<b>[listener]
</b>
</pre>
- Required: List edge cases tested against in unit tests 
```
stack@ytsai-openstack:~/source/a10-octavia/STACK-1990$ openstack loadbalancer listener create --protocol TCP --connection-limit 600 --protocol-port 8000 --name vport1 vip1
+-----------------------------+--------------------------------------+
| Field                       | Value                                |
+-----------------------------+--------------------------------------+
| admin_state_up              | True                                 |
| …
```
=> [Bug][STACK-1975] revert previous patch

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
nat-pool flavor will overwirte vport flavors.
https://a10networks.atlassian.net/browse/STACK-2060
When there is a default NAT pool for listener, we should merge flavor attributes not just overwrite it.
<pre>
<b>
{
"virtual-port":{
"conn-limit":200,
"skip-rev-hash":1,
"name-expressions":[
{
"regex":"vport1",
"json":{
"pool":"pool1"
}
}
]
},
"nat-pool":{
"pool-name":"pool1",
"start-address":"1.1.1.2",
"end-address":"1.1.1.10",
"netmask":"/24",
"ip-rr":0,
"port-overload":1,
"gateway":"1.1.1.1"
}
}
</b>
</pre>
- same as QA in https://a10networks.atlassian.net/browse/STACK-2060
```shell
openstack …
```
=> [Bug][STACK-2060] nat-pool flavor overwrite virtual-port flavors

a10_octavia/controller/housekeeping/house_keeping.py
previous patch: https://github.com/a10networks/a10-octavia/pull/314/files
cause write memory can't work properly for newly created thudners/loadbalancers
https://a10networks.atlassian.net/browse/STACK-2027
In perform_memory_writes(), thunders in reload_check_list didn't mean it will failed for reload_check. We should not remove it from write_mem_list.
<pre>
<b>
</b>
</pre>
1. Normal write memory case
2. Test newly create lb
steps:
- create loadbalancers 
- reload thunder before the write memory period
- loadbalancer status should be ERROR after reload-check
3. Test normal reload/reboot cases
Steps:
- set on loadbalancers (which already have …
=> [Bug][STACK-2027] fix degrade by previous patch

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
If Bug Fix:
- Required: Severity Level HIGH
When write memory failed, we still set the last_write_mem column and cause write memory will not retry on this thunder.
https://a10networks.atlassian.net/browse/STACK-2049
Don't set the last_write_mem when write memory failed on this thunder.
<pre>
<b>[a10_house_keeping]
</b>
</pre>
- Normal write memory procedure (update laodbalancer, write memory will perform in next period)
- Connection error case as bug
step:
1. set to lb
2. disable thunder management interface
3. wait next write memory interval
4. enable the management interface again
5. next period write memory will perform on thunder
As the …
=> [Bug][STACK-2049] write memory not perform on exceptions

a10_octavia/common/utils.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/tests/unit/common/test_utils.py, tox.ini
Modified update and delete loadbalancer flows for supporting vthunder 
https://a10networks.atlassian.net/browse/STACK-2070
https://a10networks.atlassian.net/browse/STACK-2075
- For Loadbalancer update flow=> check the harware_thunder list whether empty or not.
- For Loadbalancer delete flow=> If "deleteCompute" flag is true then skip the write memory task.
- Given a loadbalancer, tested the output of "get_vrid_floating_ip_for_project" for vthunder/hardware devices.
1. Created a loadbalancer.
`openstack loadbalancer create --vip-subnet-id 19f09075-0dbd-415a-b488-e78d6260e351 --name lb1`
Result:
```
Feb 09 05:44:08 adeeb-dev a10-octavia-worker[15311]: INFO a10_octavia.controller.queue.endpoint [-] Creating load balancer '6c1b2cc9-7188-4b2b-b0dc-fc40677ab3dd'...
Feb 09 05:44:08 adeeb-dev …
```
=> STACK-2070/STACK-2075: Code update for vthunder loadbalancer update and delete flow.

a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, test-requirements.txt, tox.ini
Modified vThunder flows(a10_load_balancer_flows, a10_listener_flows and a10_member_flows) to support SNAT feature.
https://a10networks.atlassian.net/browse/STACK-2074
- Added tasks `GetFlavorData` and `NatPoolCreate` to a10_load_balancer_flows to create nat-pools during loadbalancer creation
- Added tasks `GetFlavorData` and `NatPoolCreate` to a10_listener_flows
- Added tasks `GetFlavorData`, `MemberFindNatPool`, `GetNatPoolEntry`, `ReserveSubnetAddressForMember`, `UpdateNatPoolDB` to get the nat-pool associated with the specific listener, reserve the addresses of that nat-pool for the member subnet and update the nat-pool entry in nat-pool table in db.
- Added tasks `MemberFindNatPool`, `GetNatPoolEntry`, `ReleaseSubnetAddressForMember` and `DeleteNatPoolEntry` to release the reserved …
=> STACK-2074: SNAT feature support for vThunder flows.

a10_octavia/common/utils.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/tests/unit/common/test_utils.py, tox.ini
On deleting the last load balancer, HK will try to perform write memory but it will get connection error because vthunder is already deleted. At each subsequent interval it will be get same error. 
https://a10networks.atlassian.net/browse/STACK-2077
On interval arrival; if the lb is in deleted stated and it has some compute id then count the compute id. And the on the basis of count value, set the flag, if the flag is true then do not perform write memory only update the "last_write_mem" column of vthunders table. 
1) Enable the periodic write memory
2) create a loadbalancer 
openstack loadbalancer create --vip-subnet-id 19f09075-0dbd-415a-b488-e78d6260e351 --name lb2
3) After interval write memory will be performed
```
Feb 15 12:41:44 adeeb-dev a10-house-keeper[24686]: INFO …
```
=> [Stack 2077] Updated the periodic write memory feature for deleting last lb.

a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py, tox.ini
- Issue description:
When a pool is created/updated with --session-persistence, it is creating slb template persist templates(session persistence templates) on thunder but the templates were not getting bound to virtual port.
https://a10networks.atlassian.net/browse/STACK-2083
https://a10networks.atlassian.net/browse/STACK-2095
- Getting session persistence templates, c_pers and s_pers inside ListenerUpdateForPool task.
- Passing those received templates to self.axapi_client.slb.virtual_server.vport.update call sothat the templates will get bounded to the vport when pool is created or updated with session persistence.
- Given a pool, when it is created with session persistence, the virtual port will get updated with bounding the persist templates created for the …
=> [BUG][STACK-2083][STACK-2095]: Bound session-persistence templates to virtual ports

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Required: Severity Level LOW
ip nat pools were deleted when there's still lb using this nat pool list (it happened when two child projects in parent partition).if nat pool flavor used by multiple lbs and but single project, this issue is not existed. both nat pool and nat pool list all have this issue.
https://a10networks.atlassian.net/browse/STACK-2067
For get_lb_count_by_flavor(), provide another version of API to support HMT (which count lb with same flavor in all projects with same partition_name, ip_address)
<pre>
use_parent_partition=True
devices = [
{
"project_id": "3d21c71c4e4040599933bda62a76ae2f",
"ip_address": "192.168.90.46",
"username": "admin",
"password": "a10",
"partition_name": "p7",
"device_name": …
=> [Bug][STACK-2067] NAT pool deletion check for HMT

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/db/repositories.py
Modified the a10_load_balancer_flows for marking the status(deleted) of backup vthunder after deleting the vthunder.
Modified the periodic write memory flow to fetch only MASTER and STANDALONE recently updated vthunder from vthunder table.
https://a10networks.atlassian.net/browse/STACK-2104
1) Fetch the backup vthunder corresponding to loadbalancer  then mark the status of backup vthunder deleted.
2) Update the query to only fetch master and standalone vthunder.
**Create loadbalancer objects**
```
openstack loadbalancer create --vip-subnet-id vip_subnet --name lb1
openstack loadbalancer listener create --protocol TCP --protocol-port 8080 lb1 --name listener1
openstack loadbalancer listener create --protocol UDP --protocol-port 8081 lb1 --name listener2
openstack loadbalancer listener …
```
=> [STACK-2104]: Verification of write memory feature for active standby topology

a10_octavia/db/migration/alembic_migrations/env.py, tox.ini
Before a10-octavia v1.2, a10-octavia didn’t have its own alembic version_table in database. So it overwrites the octavia alembic versions, and make octavia hard to upgrade. So, for this release a10-octaiva will have its own alembic version_table.
Story: https://a10networks.atlassian.net/browse/STACK-2066
DD: [Link](https://teams.microsoft.com/l/file/87A78E5D-FF9F-4087-8769-FA4635B6A74A?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v1.2%2Fa10%20alembic%20version%20table%2Fdesign%20document.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread. …
=> [STACK-2066] [Database Migration Enhancement] a10-octavis overwrite octavia database alembic version

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_health_monitor_flows.py, a10_octavia/controller/worker/flows/a10_l7policy_flows.py, a10_octavia/controller/worker/flows/a10_l7rule_flows.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/common.py, a10_octavia/install/install-a10-octavia, a10_octavia/install/install-a10-octavia-dev, a10_octavia/tests/unit/controller/worker/flows/test_a10_load_balancer_flows.py, requirements.txt
While setting up a10-Octavia on OpenStack victoria, the fixes required to a10-octavia according to the new Octavia(7.1.0) version.
This PR uses Amphora V1 provider driver and controller worker.
https://a10networks.atlassian.net/browse/STACK-2101
- Installed a10-octavia on victoria 
- Updated the requirements with updated versions of packages.
- While restarting the a10-controller-worker service faced import issues, fixed those issues.
##Manual Testing
- Checked create and delete operation LB, listener, pool, HM, member, L7policy, L7rule.
=> [V1][STACK-2101]: Run a10-octavia and openstack victoria, add fixes if required.

.travis.yml, a10_octavia/common/a10constants.py, a10_octavia/common/defaults.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/db/migration/alembic_migrations/env.py
- Severity Level: LOW
- Issue Description: fix tox and travis errors
see also acos-client side changes:
https://github.com/a10networks/acos-client/pull/336
https://a10networks.atlassian.net/browse/STACK-2162
Fix errors in tox py38 and pep8 for 
- API changes in octavia
- indent problems
- victoria octavia (https://pypi.org/project/octavia/7.0.0/) requires python >= 3.6, remove travis checks for python < 3.6
<pre>
<b>N/A</b>
</pre>
- sudo tox -e py38
- sudo tox -e pep8
```shell
stack@ytsai-victoria:~/source/a10-octavia/victoria$ sudo tox -e py38
py38 develop-inst-noop: /opt/stack/source/a10-octavia/victoria
py38 installed: -e git+git@github.com:ytsai-a10/a10-octavia.git@f877937f7575753452d3bcf0b31735eb0c057cbb#egg=a10_octavia,acos-client==2.6.1,alembic==1.5.5,amqp==5.0.5,aniso8601==9.0.1,ap …
```
=> STACK-2162  Fix travis and tox unit-test issues

a10_octavia/controller/worker/flows/a10_member_flows.py
Modified the a10 member flows to support  VRID VRRP-A floating IP.
https://a10networks.atlassian.net/browse/STACK-2137
https://a10networks.atlassian.net/browse/STACK-2138
https://a10networks.atlassian.net/browse/STACK-2139
https://a10networks.atlassian.net/browse/STACK-2140
https://a10networks.atlassian.net/browse/STACK-2141
Added the handle_vrid_member_flow in the member flows for vthunders.
1)Update the a10_global secton of a10-octavia.conf.
```
vrid_floating_ip = ".50" 
```
2) Restart the controller service.
3) Create loadbalancer, listener, pool and member.
_openstack loadbalancer create --vip-subnet-id vip_subnet --name lb1
openstack loadbalancer listener create --protocol HTTP --protocol-port 8082 lb1 --name listener3
openstack loadbalancer pool create  --protocol HTTP --listener …
=> [STACK-2016][vthunder support]:Added support for VRID VRRP-A floating IP

a10_octavia/api/drivers/driver.py
Add victoria missing APIs for A10 Provider driver
Add victoria missing APIs for A10 Provider driver
per https://docs.openstack.org/octavia/latest/contributor/guides/providers.html
> VIP port creation
>
> Some provider drivers will want to create the Neutron port for the VIP, and others will want Octavia to create the port instead. In order to support both use cases, the create_vip_port() method will ask provider drivers to create a VIP port. If the driver expects Octavia to create the port, the driver will raise a NotImplementedError exception. Octavia will call this function before calling loadbalancer_create() in order to determine if it should create the VIP port. Octavia will call …
=> [STACK-2099][Victoria] Add missing APIs for A10 Provider Driver

a10_octavia/api/drivers/driver.py
The flavor support for Victoria.
https://a10networks.atlassian.net/browse/STACK-2149
After fix the missing APIs problem (in another PR), the Flavor support feature works fine. So, here we just add additional checks for flavor-data.
<pre>
<b>N/A</b>
</pre>
- Test flavor support for virtual-server
- Test flavor support for virtual-port
- Test flavor support for service-group
- Test flavor support for member
- Test flavor support for health monitor 
- case 1
[cmd]
```
openstack loadbalancer flavorprofile create --name fp1 --provider a10 --flavor-data '{"virtual-server": {"vport-disable-action":"drop-packet", "name-expressions":[{"regex": "vip1", "json": {"user-tag":"test"}}]}}'
openstack loadbalancer flavor create --name f1 --flavorprofile fp1 --description "vtest" --enable
openstack …
```
=> [STACK-2149] Add additional checks for flavor-data

a10_octavia/controller/worker/tasks/a10_database_tasks.py
- Required: High
- Required: When VRID is not created, tried creating LB which fails causes LB to enter ERROR state. When we try to delete LB  an error is caused. The reason is vthunder object is not created before accessing it.
https://a10networks.atlassian.net/browse/STACK-2166
- Checked the logs for deletion of LB.
- Deletion of LB which is in error state.
=> [BUG][STACK-2166][LoadBalancer]: Unable delete LB when it is in error state.

a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_health_monitor_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
- Severity Level: Low
- Issue Description: Previous Travis failure led to it not reporting failures on github. This resulted in failing tests being merged.
[STACK-2224](https://a10networks.atlassian.net/browse/STACK-2224)
- Added copying of global variables for when they are being modified in test code or execute methods
- Added mocking of `time` module as it was causing unit tests to wait for minutes at a time
N/A
N/A
N/A
=> [STACK-2224] Repaired unit tests

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py, tox.ini
Issue Description: 1. When LB goes into an error state we cannot delete LB.
2. VRID floating IP not getting created for vthunder LB flow. while members are working fine i.e, VRID floating IP is working for vthunder member flow.
https://a10networks.atlassian.net/browse/STACK-2213
https://a10networks.atlassian.net/browse/STACK-2217
https://a10networks.atlassian.net/browse/STACK-2218
https://a10networks.atlassian.net/browse/STACK-2212
- Added checks for objects before performing any operations on those objects.
- Logic for handling VRID floating IP is added to vthunder LB create flow. Checked the delete flow it is already integrated with handle VRID logic.
- When amphorae not available for AmphoraePostNetworkUnplug.
When LB in error, we could not delete LB
- Unavailable …
=> [BUG][STACK-2213][STACK-2217][STACK-2218][STACK-2215]: When LB in error state, we could not delete LB. VRID FIP for vthunder LB not created.

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py
Issue Description: vrid floating ip in member subnet isn't cleared when delete lb --cascade
- https://a10networks.atlassian.net/browse/STACK-2236
- Added call to "get_delete_member_vrid_internal_subflow" in the cascade flow.
- Required: List of steps to manually test feature or fix 
1) Create loadbalancer and all releted objects:
```
openstack loadbalancer create --name v1 --vip-subnet-id vip_subnet
openstack loadbalancer listener create --name l1 --protocol TCP --protocol-port 8 v1
openstack loadbalancer pool create --name p1 --protocol TCP --lb-algorithm least_connections --listener l1
openstack loadbalancer member create --name p1-m1 --protocol-port 81 --address 10.0.11.101 --subnet-id provider-vlan-11-subnet p1
openstack loadbalancer healthmonitor create --delay 3 …
```
=> [STACK-2236]: delete pool members vrid floating ip while lb cascade delete

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Severity Level: Highest
- Issue description:
Sometimes while creating 2nd or 3rd loadbalancer, there was a KeyError occurring for added_ports where it should go as an empty dictionary.
https://a10networks.atlassian.net/browse/STACK-2211
- As `added_ports` are not required for the first and last call of the `EnableInterface` task in `get_new_lb_networking_subflow`, injecting the `ADDED_PORTS` as {}.
- Removed the default value for `added_ports` from `EnableInterface` task as it is being injected where it is required to be None
- Added a check for `vrid_list` in `HandleVRIDFloatingIP` task as it was breaking when `partition_project_list` is None.
- Added time.sleep(20) in `GetMasterVThunder` task as sometimes the master's VCS config takes some time after its reload  to get back as earlier …
=> [BUG][STACK-2211]: Fixed KeyError issue sometimes getting while creating LB in Active-Standby mode

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_pool_flows.py
Issue Description: data port was not deleted when deleting pool directly.
by deleting member to delete dataport is fine.
https://a10networks.atlassian.net/browse/STACK-2230
- Added interface deletion flow for pool deletion
- Create pool
openstack loadbalancer pool list
+--------------------------------------+--------+----------------------------------+---------------------+----------+--------------+----------------+
| id                                   | name   | project_id                       | provisioning_status | protocol | lb_algorithm | admin_state_up |
+--------------------------------------+--------+----------------------------------+---------------------+----------+--------------+----------------+
| 57690cb3-8b42-4c6c-82da-0c22cd7bdbc0 | pool-1 | …
=> [BUG][STACK-2230]: [vthunder_dataport] dataport was not deleted when deleting pool directly

a10_octavia/controller/worker/tasks/vthunder_tasks.py
If Bug Fix:
- Required: Medium
- Required: failed to reuse a network/subnet for member creation in demo project when it's already in admin project
https://a10networks.atlassian.net/browse/STACK-2219
- Didn't see this problem in latest code
- But when tested in QA's HC8000 server, the second LB creation is failed because vThunder booting time is too long. 
1. **We should provide the flexibility for user to control the timeout and retry for waiting vthunder booting up** (otherwise customer may have problem create LB for slow servers)
2. use ***amp_active_retries*** and ***amp_active_wait_sec*** for VThunderComputeConnectivityWait to decide vthunder booting timeout and retry.
3. **We should use another option for this, but it is close to release. It is not a good time to add new options …
=> [STACK-2219] failed to reuse a network/subnet for member creation in demo project when it's already in admin project

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Issue Description: Port assigned to lb isn't deleted successfully when lb is removed
https://a10networks.atlassian.net/browse/STACK-2229
https://a10networks.atlassian.net/browse/STACK-2243
- Added task DeallocateVIP to get_delete_load_balancer_flow for releasing the port of loadbalancer on the loadbalancer deletion.
Tested the following steps on Single as well as on Active-Standby mode
1. Create a loadbalancer with vip_subnet
openstack loadbalancer create --vip-subnet-id vip_subnet --name lb1
2. Create 2nd loadbalancer with vip_subnet2
stack@neha:~$ openstack loadbalancer create --vip-subnet-id vip_subnet2 --name lb2 …
=> [BUG][STACK-2229][STACK-2243][vThunder: Single and Active_Standby]: Release ports on loadbalancer deletion.

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py
1)Severity Level: High
Issue Description: security group and port are not deleted when deleting vthunder instance
2)Severity Level: High
Issue Description: failed to create listener for lb and get error: MissingVIPSecurityGroup: VIP security group is missing for load balancer
- https://a10networks.atlassian.net/browse/STACK-2209
- https://a10networks.atlassian.net/browse/STACK-2233
1)Added call to DeallocateVIP task in delete loadbalancer flow
2)Added call to PlugVip task in create loadbalancer flow
1) Active Standby Vthunder flow
a) Create loadbalancers
```
openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name lb1
openstack loadbalancer create --vip-subnet-id provider-vlan-12-subnet --name lb2
stack@adeeb:~$ openstack loadbalancer  list …
```
=> [BUG][STACK-2233][STACK-2209]code update for security group/port creation/deletion

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
Issue Description: [Rackflow] on deleting loadbalancer, write memory is not performed.
- https://a10networks.atlassian.net/browse/STACK-2250
- Removed the deleteCompute flag from the get_delete_rack_vthunder_load_balancer_flow method.
1) Create loadbalancer
```
openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name lb1
logs:
Apr 15 11:41:23 adeeb a10-octavia-worker[14045]: INFO a10_octavia.controller.queue.endpoint [-] Creating load balancer 'e21043f0-6e97-45ba-91c5-5e79e35edb0e'...
Apr 15 11:41:23 adeeb a10-octavia-worker[14045]: INFO a10_octavia.controller.worker.tasks.a10_database_tasks [-] Successfully created vthunder entry in database.
Apr 15 11:41:29 adeeb a10-octavia-worker[14045]: INFO a10_octavia.controller.worker.tasks.vthunder_tasks …
```
=> [BUG][STACK-2250]: Updated code for loadbalancer write-memory in rackflow

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
If Bug Fix:
- Required: Issue Description 
ve/vlan interface is not removed after loadbalancer deletion
https://a10networks.atlassian.net/browse/STACK-2238
1. In get_delete_rack_vthunder_load_balancer_flow, move DeleteInterfaceTagIfNotInUseForLB task after DeleteVirtualServerTask task otherwise the virtual server is still there when a10-octavia try to remove the ve/vlan interface (The vlan subnet still in used, so is_vlan_deletable() will return False and cause vlan/ve deletion  bypassed).
2. For vThunder flow the vlan is not supported, so remove DeleteInterfaceTagIfNotInUseForLB task from vthunder LB delete flow.
- rack flow
<pre>
<b>[a10_health_manager]
udp_server_ip_address = 10.64.28.68
bind_port = 5550
bind_ip = 10.64.28.68
heartbeat_interval = 5 …
=> [STACK-2238] remove ve interface after LB deletion

a10_octavia/controller/worker/flows/a10_member_flows.py
If Bug Fix:
When vrid_floating_ip is configured in [a10_global], member creation will failed in ACTIVE-STANDBY mode.
[Root Cause]
In current flow, we do handle_vrid_for_member_subflow() after master reload but before blade reload. So, a10-octavia try to set VRID FIP when vthunder is still as BLADE. And axapi will return failed for blade is not allow to do configuration.
https://a10networks.atlassian.net/browse/STACK-2253
Move handle_vrid_for_member_subflow() after both master and blade are reloaded. (so, the vthunder is master now and able to do configuration)
<pre>
<b>[vthunder] …
=> [STACK-2253] ACTIVE-STANDBY VRID FIP issue

a10_octavia/common/config_options.py, a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/common.py, a10_octavia/controller/worker/tasks/decorators.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
**acos-client side PR: https://github.com/a10networks/acos-client/pull/340**
**a10-octavia side PR: https://github.com/a10networks/a10-octavia/pull/363**
If Bug Fix:
- Required: Severity Level Low
- Required: Issue Description:  Failed to create LB for public-subnet
According to the audi log:
```
vThunder(NOLICENSE)#show audi
Apr 13 2021 10:46:53  [admin] axapi: [7:192.168.0.127:34384] RESP HTTP status 400  Bad Request : Failed to acquire a DHCP offer from DHCP server.
Apr 13 2021 10:46:53  [admin] axapi: [7:192.168.0.127:34384] payload section 1
{"ethernet": {"action": "enable", "ip": {"dhcp": 1}, "ifnum": "1", "name": "DataPort"}}
Apr 13 2021 10:45:50  [admin] axapi: [7:192.168.0.127:34384] POST: /axapi/v3/interface/ethernet/1
```
- **Root Cause:**
1. The acos-client timeout is 30 …
=> [STACK-2220] acos-client timeout too short

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, tox.ini
- Severity Level: Highest
- Issue Description: Listener creation is failing when a listener is created for a loadbalancer with different subnet than that of latest created loadbalancer due to the reload and role switching happening for the vThunders in ACTIVE_STANDBY topology.
https://a10networks.atlassian.net/browse/STACK-2279
- Passing **topology** in `get_create_listener_flow`.
- If the topology is **ACTIVE_STANDBY**, then `GetMasterVThunder` is called before listener creation for getting correct vMaster vThunder based on the current vcs_summary sothat the listener will be always created on vMaster without throwing the error.
1. openstack loadbalancer create --name v1 --vip-subnet-id vip_subnet
2. openstack loadbalancer create --name v2 --vip-subnet-id vip_subnet
3. openstack …
=> [BUG][STACK-2279]: Fixed an issue of failing listener creation in ACTIVE_STANDBY mode.

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Issue Description: In ACTIVE_STANDBY mode, When vcs switch over is performed after 1st LB creation and 2nd LB is created, then while deleting the 1st LB, get_delete_lb_vrid_subflow was getting performed on vBlade device throwing an error "ACOSException: 1023526144 Method not allowed"
https://a10networks.atlassian.net/browse/STACK-2270
https://a10networks.atlassian.net/browse/STACK-2282
- Moved the `get_delete_lb_vrid_subflow` after `GetMasterVThunder` task sothat in case of ACTIVE_STANDBY topology, the task will get executed on vMaster device only without throwing any error.
1. Create a loadbalancer lb1
openstack loadbalancer create --vip-subnet-id vip_subnet --name lb1
```
stack@neha:~$ openstack loadbalancer list …
```
=> [BUG][STACK-2270][STACK-2282]: Fixed an issue related to delete_lb_vrid_subflow for ACTIVE_STANDBY mode.

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, tox.ini
Severity Level: Medium
Issue: [delete_lb-cascade] ve ip of vblade was not released from dashboard when deleting by cascade
https://a10networks.atlassian.net/browse/STACK-2280
- Task _SetupDeviceNetworkMap_ was being executed multiple times in one flow thus appending multiple values in _vthunder.device_network_map_. 
Changed the location _SetupDeviceNetworkMap_ so that it runs one time per flow.
1) Create loadbalancer, listener, pool and members.
```
openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name v1
openstack loadbalancer listener create --protocol HTTP --protocol-port 8080 --name l11 v1
openstack loadbalancer pool create --protocol HTTP --lb-algorithm ROUND_ROBIN --listener l11 --name pool11
openstack loadbalancer member create --address 10.0.12.192 …
```
=> [BUG][STACK-2280]: Deleting ve ip for blade from dashboard on deleting the lb cascade

a10_octavia/cmd/a10_octavia_worker.py, a10_octavia/common/a10constants.py, a10_octavia/common/config_options.py, a10_octavia/controller/queue/consumer.py, a10_octavia/controller/queue/endpoint.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_health_monitor_flows.py, a10_octavia/controller/worker/flows/a10_l7policy_flows.py, a10_octavia/controller/worker/flows/a10_l7rule_flows.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, tox.ini
[STACK-2241][STACK-2262][STACK-2264][STACK-2284] Provide thread-safe mechanism for vthunder flow
For vThunder flow, vthunder instance may reload during 
- loadbalancer create
- loadbalancer delete
- member create
- member delete
And in these cases, if other works (or a10-octavia controller work threads) also configure something in this project. The configuration may loss on vthunder (since vthunder may be reloaded in any time). So, we need to prevent these kinds of situation.
https://a10networks.atlassian.net/browse/STACK-2241
https://a10networks.atlassian.net/browse/STACK-2262
https://a10networks.atlassian.net/browse/STACK-2264
https://a10networks.atlassian.net/browse/STACK-2284
https://a10networks.atlassian.net/browse/STACK-2293
**Add a …
=> [STACK-2241][STACK-2262][STACK-2264][STACK-2284][STACK-2293] Provide thread-safe mechanism for vthunder flow

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Severity Level High
For vThunder flow, something a10-octavia will operate on thunder without check it is ready.
https://a10networks.atlassian.net/browse/STACK-2295
In get_new_lb_networking_subflow(), when vthunder exist we will do VThunderComputeConnectivityWait task before we call EnableInterface(). But when vthunder is None there is no VThunderComputeConnectivityWait task anymore, and EnableInterface task may fail sometime (especially when system busy).
<pre>
<b>[vthunder]
amp_flavor_id = …
=> [STACK-2295] Make sure Thunder ready before operate on it

a10_octavia/common/config_options.py
config option define by wrong type, vcs_wait_sec and retry should be int not string
https://a10networks.atlassian.net/browse/STACK-2298
https://a10networks.atlassian.net/browse/STACK-2283
use IntOpt insteadd of StrOpt for amp_vcs_retries and amp_vcs_wait_sec
<pre>
<b>[vthunder]
amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4
amp_ssh_key_name = octavia_ssh_key …
=> [STACK-2283][STACK-2298] vcs retry and timeout option type error

a10_octavia/db/repositories.py
Issue Description: In active-standby mode, create 4 lb, the 4th one is from a different subnet, which causes the vrid floating IP for the 1st subnet is deleted
https://a10networks.atlassian.net/browse/STACK-2281
- The vthunders entries happen at start of create_lb_flow and those entries are according to the previous master and the backup role and there are several reloads that happen which causes the change in role for those vthunder.
- Identifying the return of task GetChildProjectsOfParentPartition.
- Added "BACKUP" for role field in a query to fetch vthunders entry from vthunder table. 
- Created 3 lbs in one subnet and 1 subnet in different subnet. 
- Checked vthunder for VRID FIP configuration.
vThunder-vBlade[1/1](NOLICENSE)#show running-config 
!Current …
=> [BUG][STACK-2281][vthunder: active-standby][DEGRADE]the vrid floating ip isn't right after adding lb from different subnet.

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
Severity Level Medium
Issue Description: [vthunder: mode switch] failed to create lb and get "AttributeError: 'NoneType' object has no attribute 'id' when change from single to active-standby
- https://a10networks.atlassian.net/browse/STACK-2261
- Limitation:
1. Don't support for changing topology when loadbalancer already created on vThunder instance.
2. Response error to user when existing vthunder has lb with differnet topology
- Added CheckExistingVthunderTopology task in a10_database_tasks.py file. This task will compare the topology from config file to the topology of existing lb in vthunder. If topology does not match then exception will be raised.
- Added test_CheckExistingVthunderTopology_execute_raised_exception in test_a10_database_tasks.py file
1) Create lbs in active standby …
=> [BUG][Stack 2261]: [vthunder mode switch] Return error response when vthunder has loadbalancer with topology

a10_octavia/common/config_options.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py
If Bug Fix:
- Severity Level High
When vthunder instance busy, a10-octavia will just raise instance busy error. But it is better we queue the CLI request and wait the instance free.
https://a10networks.atlassian.net/browse/STACK-2294
https://a10networks.atlassian.net/browse/STACK-2241
https://a10networks.atlassian.net/browse/STACK-2262
https://a10networks.atlassian.net/browse/STACK-2264
https://a10networks.atlassian.net/browse/STACK-2271
https://a10networks.atlassian.net/browse/STACK-2284
https://a10networks.atlassian.net/browse/STACK-2293
- add a new option ***amp_busy_wait_sec*** 
- and if instance is busy, controller worker will wait amp_busy_wait_sec before raise instance busy error
Notice: the better way is send the command back to the controller queue, but this …
=> [STACK-2294] queue openstack commands when instance busy

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Severity Level Critical
For reload/reboot, vcs reload, vcs configuration sync, a10-octavia will sleep for 20 or 30 seconds. But a10-octavia should check both active and standby are up and vcs ready after the sleep or we will have problem for slow server.
https://a10networks.atlassian.net/browse/STACK-2262
https://a10networks.atlassian.net/browse/STACK-2283
In active-standby mode, after reload/reboot, vcs reload or vcs configuration sync. check device is up and vcs ready after sleep.
<pre>
<b>[vthunder] …
=> [STACK-2262][STACK-2283] active-standby stabilize

a10_octavia/controller/worker/flows/a10_member_flows.py
- Required: On creating member with the new subnet, interface is not adding on vblade machine
- https://a10networks.atlassian.net/browse/STACK-2269
Updated the create_member_flow similiar to new_LB_net_subflow of loadbalancer create flow.
Added one more reload so that interface can be added to vblade.
**SINGLE TOPOLOGY**
1) Create loadbalancer, listener,pool,member.
```
openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name v1
openstack loadbalancer listener create --name l2 --protocol HTTP --protocol-port 80 v1
openstack loadbalancer pool create --name p2 --protocol HTTP --listener l2 --lb-algorithm least_connections
openstack loadbalancer member create --address 10.0.12.192 --subnet-id provider-vlan-12-subnet --protocol-port 80 --name mem1 p2 …
```
=> [STACK-2269]: Interface is not adding on vblade while creating member

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Severity Level: Highest
- Issue Description: Only sometimes VCS reload is switching roles of the vThunders and then the next subsequent reload(last reload) is getting happened on an incorrect vThunder at that time, which should actually happen on another one for getting blade's 2nd interface. 
Due to this case, ifnum_backup is being passed None to EnableInterface of backup and thus not able to enable it.
**Removal of the VCSReload task is not affecting any of the EnableInterface task(master/backup) now.**
And due to this final role switching is not happening.
The bug is getting reproduced only in the case when roles of vThunders are not getting changed than that of previous ones at the end on an LB creation with different subnet.
https://a10networks.atlassian.net/browse/STACK-2242
- …
=> [BUG][STACK-2242]: Removed non-required VCS Reload which is causing issues sometimes.

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_health_monitor_flows.py, a10_octavia/controller/worker/flows/a10_l7policy_flows.py, a10_octavia/controller/worker/flows/a10_l7rule_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py
- Severity Level Critical
In Active-Standby mode, when master is handover a10-octavia can't configure vthunder correctly for all SLB objects.
https://a10networks.atlassian.net/browse/STACK-2302
Get Master vThunder for all SLB flows (some are already done in other PR)
<pre>
<b>[vthunder]
amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4
amp_ssh_key_name = octavia_ssh_key
workers = 2
amp_active_retries = …
=> [STACK-2302] Get Master vThunder for SLB flows

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Severity Level Critical
In Active-Standby mode, when master is handover a10-octavia can't configure vthunder correctly for all SLB objects.
https://a10networks.atlassian.net/browse/STACK-2302
Get Master vThunder for all SLB flows (some are already done in other PR)
<pre>
<b>[vthunder]
amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4
amp_ssh_key_name = octavia_ssh_key
workers = 2
amp_active_retries = …
=> [STACK-2302] active-standby mode LB cascade delete failed after failover

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
- Severity Level High
When multiple networks are specified in amp_boot_network_list, a10-octavia should:
- still able to create slb object correctly.
- when LB vip subnet already in this list, create LB will not need to reload/reboot during creation
- when member subnet already in this list. create member will not need to reload/reboot during creation.
https://a10networks.atlassian.net/browse/STACK-2241
https://a10networks.atlassian.net/browse/STACK-2282
https://a10networks.atlassian.net/browse/STACK-2307
Go through our flow to make sure multiple networks in amp_boot_network_list can works as expected.
<pre>
<b>[a10_controller_worker]
...
amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4, 61305531-6e3a-44b4-8e67-05e93363dddc, …
=> [STACK-2307][STACK-2241][STACK-2282] multiple network in amp_boot_network_list

a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Issue Description: Sometimes during configuring vrrp sync on backup vThunder, the vThunder is not ready yet and thus Configuration of VRRP sync gets failed.
https://a10networks.atlassian.net/browse/STACK-2308
- Added attempts=amp_active_retries for the ConfigureVRRPSync task. 
- Added waits=amp_active_wait_sec if we get any ACOSException for the configSynch untill we complete all given attempts
Used following config:
```
[a10_global]
network_type = "flat"
vrid_floating_ip = "dhcp"
[vthunder]
amp_image_owner_id = 9ef5e94c53c940239a66dbe4a1058eee
amp_secgroup_list = e8d58350-a82a-407a-8a4e-e87b8d106ca2
amp_flavor_id = …
```
=> [BUG][STACK-2308]: Make sure vThunder is UP and ready while configuring VRRP sync.

a10_octavia/controller/worker/controller_worker.py, a10_octavia/db/repositories.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py, a10_octavia/tests/unit/network/drivers/neutron/test_a10_neutron_driver.py
1. If we delete all LB together, vthunder instance will be deleted unexpectedly when some of LB are not deleted yet.
2. Also fix LB created failed issue, which degrade by https://github.com/a10networks/a10-octavia/pull/390
https://a10networks.atlassian.net/browse/STACK-2319
1. For the logic to check deleteCompute is not correct, vthunders may in pending or error state and still running. We should not just count ACTIVE thunders.
2. I assume we still need to remove security group for ports not allowed by OCTAVIA. otherwise security group can't be deleted.
<pre>
<b>N/A</b>
</pre>
create 3 LB and delete them together.
```
openstack loadbalancer create --vip-subnet-id …
```
=> [STACK-2319] instance deleted when all LB in pending state

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py
1. loadbalancer delete failed for rack flow single topology
2. but the issue described in STACK-2328 can't reproduce, asked JiYen to help for reproduce it.
https://a10networks.atlassian.net/browse/STACK-2328
1. Only run backup related tasks in ACTIVE-STANDBY mode.
<pre>
<b>[vthunder]
#amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4
amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4, …
=> [STACK-2328] rack flow degrades

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/decorators.py
If Bug Fix:
1. check the journal log on QA's server, when a10-octavia try to plug interface and reload on backup vthunder (i.e. AmphoraePostVIPPlug()), the backup vthunder is not up (maybe reloaded by configuration sync. or vcs). So, acos-client failed to connect ot vthunder and raise ConnectionError.
Journal log:
```shell
May 10 18:22:50 qa-109 a10-octavia-worker[28974]: DEBUG acos_client.v30.axapi_http [-] axapi_http: POST url = /axapi/v3/auth {{(pid=29014) request_impl /opt/stack/acos-client/acos_client/v30/axapi_http.py:76}}
May 10 18:22:50 qa-109 a10-octavia-worker[28974]: DEBUG acos_client.v30.axapi_http [-] axapi_http: params = {
May 10 18:22:50 qa-109 …
```
=> [STACK-2313] backup plug interface failed because of reloading

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py
- Severity Level: Highest
- Issue Description: Whenever one of the previously deleted BACKUP vThunder entry is having its status as ACTIVE in DB, then while creating 2nd loadbalancer, that vThunder entry is fetched instead of actual ACTIVE vThunder and thus its compute_id is got from GetComputeForProject and throws ComputeGetException at the task ComputeActiveWait.
https://a10networks.atlassian.net/browse/STACK-2320
https://a10networks.atlassian.net/browse/STACK-2325
- Created a new task ValidateComputeForProject for validating the compute_id got from GetComputeForProject, before passing the compute_id to ComputeActiveWait.
- In ValidateComputeForProject, getting a list of all vThunders in a particular project with respect to their roles and then checking if the fetched vThunders are …
=> [BUG][STACK-2320][STACK-2325][vthunder:active_standby]: Fixed ComputeGetException issue getting for 2nd loadbalancer creation.

a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
- Severity Level: HIGH
- Issue Description: Unable to delete the load balancer created in the DEMO project. The issue also exists for CASCADE delete.
[vthunder: active-standby] failed to create lb in demo project and get AxapiJsonFormatError: 1 vMaster not found in vcs-summary, new error WrappedFailure. New error 1 vBlade not found in vcs-summary 
https://a10networks.atlassian.net/browse/STACK-2318
- The list ports were getting fetched according to the project, which caused demo project ports to be left out.
-  Removed the filtering criteria for list port so that all ports get fetched irrespective of project.
- Created LB in DEMO project, and checked the delete operation for the created LB.
- Created LB, listener, pool, and member and checked the cascade delete operation.
- Created LB in …
=> [BUG][STACK-2318][vthunder: active-standby > security group] failed to delete lb --cascade in demo project

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py
If Bug Fix:
network in amp_boot_network_list is deleted by DeallocateVIP when LB deletion.
https://a10networks.atlassian.net/browse/STACK-2342
- For LB count for subnet, when the subnet is in amp_boot_network_list we should +1 on the counter to prevent interface port deleted by neutron.
```
amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4, 61305531-6e3a-44b4-8e67-05e93363dddc, a66685db-31ee-46c6-928a-ac034d87dc63, ec33a88d-3290-4ad6-95cc-226fcd2a4458
```
- do following commands and then check interface on vthunder
```
openstack loadbalancer create --vip-subnet-id tp92 --name vip2
openstack loadbalancer delete vip2
```
```
stack@openstack-4:~/source/a10-octavia/vThunder$ openstack …
```
=> [STACK-2323][STACK-2342] do not delete amp_boot_network_list ports when DeallocateVIP

a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
- Issue Description:  When 3 LBs with different subnets are created with no waits in between them, then interface of 2nd LB is not getting enabled. But only 1st and 3rd LB's interfaces were getting enabled with all 3 LBs present there on vThunder.
Due to no wait, at the time of 2nd LB creation, the interfaces of both 2nd and 3rd LBs are getting detected as 3rd LB is also in "PENDING_CREATE" state at that moment. And hence the ifnum holds only last got disabled interface i.e 3 and enabling only interface 3 instead of enabling interfaces 2 and 3.
https://a10networks.atlassian.net/browse/STACK-2343
- Storing and providing the interfaces which are in disabled state into a list in `GetVThunderInterface` task
- Enabling each interface present in the interface list by …
=> [BUG][STACK-2343]: Port missed when created multiple LBs with no wait in between them in active_standby mode

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py
If Bug Fix:
In Active-Standby mode, when create 2 or more LB without wait, first virtual-server lost.
This is because 2'nd LB creation will reload vMaster, but vcs configuration sync. is not finished. So, when vMaster is reloading the vBlade didn't have the virtual-server configuration and become vMaster. So, the virtual-server is lost.
https://a10networks.atlassian.net/browse/STACK-2348
- Add new task WaitVirtualServerReadyOnBlade() to make sure LB is on vBlade. So, the VCS sync. is ready and no more reload on vBlade.
<pre>
<b>[vthunder]
amp_image_owner_id = …
=> [STACK-2348]wait blade sync. in LB creation flow

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/db/migration/alembic_migrations/versions/9bfc38df2582_updated_vrid_table_to_use_a_uuid_for_.py, a10_octavia/db/models.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
When deploying in ACTIVE_STANDBY mode and using VRID floating IPs, packets were not being forwarded as the vNIC ports did not have the VRID Floating IP added as an allowed address pair. Furthermore, a distinction does not exist between regular ports and vrid fips in the current implementation.
- [STACK-2321](https://a10networks.atlassian.net/browse/STACK-2321)
*Assumes that the vrid floating ip has been set in the config file*
- Create a VRID floating IP port in the DOWN state and it's IP as an allowed address pair on the vNIC whenever a loadbalancer is created in a new subnet
- Create a VRID floating IP port in the DOWN state and it's IP as an allowed address pair on the vNIC whenever a member is created in a new subnet
- Refactor HandleVRIDFloatingIP code to reduce …
=> [STACK-2321] VRID Floating IP Traffic Issue

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
- Issue Description: When deleting a loadbalancer or a member, while deletion of vrid FIP associated to it, `_remove_allowed_address_pair_from_port` is getting called in which aap_ips is a list of dictionaries in which each dictionary is having 2 key-value pairs(ip_address and mac_address). Due to these 2 key value pais, the call `aap_ips.remove({'ip_address': ip_address})` is getting failed throwing `ValueError: list.remove(x): x not in list`.
https://a10networks.atlassian.net/browse/STACK-2355
- For removing the allowed_address_pair of vrid FIP port in `_remove_allowed_address_pair_from_port`, using `updated_aap_ips = [aap_ip for aap_ip in aap_ips if aap_ip['ip_address'] != ip_address]` instead of `aap_ips.remove({'ip_address': ip_address})`  as the aap_ips is a …
=> [BUG][STACK-2355]: Fixed an issue ValueError: list.remove(x): x not in list while deleting loadbalancer and member

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py
If Bug Fix:
- Required: Severity Level Critial
LB cascade failed, degraded by: https://github.com/a10networks/a10-octavia/pull/406/files
https://a10networks.atlassian.net/browse/STACK-2365
Fix problems in  https://github.com/a10networks/a10-octavia/pull/406/
<pre>
<b>N/A</b>
</pre>
- test with following commands:
```
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name vport1 vip1
openstack loadbalancer pool create --protocol HTTP --lb-algorithm ROUND_ROBIN --listener vport1 --name sg1
openstack loadbalancer member create --address 192.168.90.132 --subnet-id tp90 --protocol-port 80 --name srv1 sg1
openstack loadbalancer delete vip1 --cascade
```
Result:
``` …
```
=> [STACK-2365] LB cascade delete error

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
- Issue Description: When a loadbalancer/member is created in L3V partition and a VRID floating IP is also present in shared partition, then the VRID FIP of shared partition is getting mixed with the current VRID FIP created in L3V partition.
https://a10networks.atlassian.net/browse/STACK-2372
- For vrid in vrid_list, appending `vrid.vrid_floating_ip` in vrid_floating_ips[] only when the subnet of the vrid is same as that of lb_resource(newly added vrid fip) or the vrid.vrid_floating_ip is already present on vthunder(previously present vrid fip) sothat correct VRID FIPs will be passed to `_update_device_vrid_fip()` method to create VRID FIPs on vthunder.
- Modified the call of HandleVRIDFloatingIP task in a10_member_flows as per the modified task.
- Given a vrid …
=> [BUG][STACK-2372]: [device flavor] the vrid floating ip is mixed for shared and l3v partitions

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Required: Medium
- Required: Interfaces are not getting configured when LB are created in shared and parent partion.
https://a10networks.atlassian.net/browse/STACK-2370
https://a10networks.atlassian.net/browse/STACK-2362
https://a10networks.atlassian.net/browse/STACK-2363
1. Update "SetupDeviceNetworkMap" task to accept device configuration using device name.
- Created lb2 for rack device in shared partition, check the equivalent vthunder configurations.
**master device:**
blade device
2. Delete LB lb2 from shared partition.
3. Creating LB  lb2 with HMT and UPP settings on.
master device:
4. Delete lb2, created with HMT and up settings on.
=> [BUG][STACK-2370][STACk-2362][STACK-2362]:  Interface ve isn't configured when create lb in shared and parent partition.

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/db/repositories.py
- Issue Description: When we delete a member using the same subnet as a Loadbalancer, its associated floating ip is also getting removed with the member though LB is using the floating ip.
https://a10networks.atlassian.net/browse/STACK-2368
- Modified a DB method **get_lb_by_subnet()** to consider LBs in **PENDING_UPDATE** state as well so that the Loadbalancer in current execution also get considered as it enters into PENDING_UPDATE state during taking LB count by subnet 
- Shifted a task **DeleteMemberInDB** after **get_delete_member_vrid_subflow()** so that during calculating member_count_by subnet member stays in PENDING_DELETE state 
Step 1: Create a Loadbalancer 
```
stack@openstack-2:~$ openstack loadbalancer create --name v1 --vip-subnet-id …
```
=> [BUG][STACK-2368][vthunder: vrid floating ip][negative] vrid floating ip is deleted unexpectedly

a10_octavia/controller/worker/tasks/decorators.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Issue Description: When a loadbalancer goes into ERROR state while its creation and then if we try to delete it, then the loadbalancer remains in PENDING_DELETE state for a long time instead of simply deleting it.
https://a10networks.atlassian.net/browse/STACK-2378
- As vthunder will be None in the case where LB goes into ERROR state, so returning None from GetMasterVThunder task if vthunder is None at GetMasterVThunder task else returning the master vthunder.
- If vthunder is None, then returning from VCSSyncWait task without executing it further.
1. Create a loadbalancer and wait till it is ACTIVE and vThunder is ready
stack@neha:~$ openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name lb1
``` …
```
=> [BUG][STACK-2378]: [vthunder] LB is in PENDING_DELETE for 30+ minutes even when the amp_busy_wait_sec=100

a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
- Issue Description: When a loadbalancer/member is deleted in L3V partition and a VRID floating IP is also present in shared partition, then the VRID FIP of shared partition is getting mixed into the L3V partition after the deletion.
https://a10networks.atlassian.net/browse/STACK-2372
- In `DeleteVRIDPort` and `DeleteMultipleVRIDPort` tasks, fetching existing vrid FIPs from vThunder.
- Checking if the vrid.vrid_floating_ip is already exists on vThunder i.e in `existing_fips[]` before appending it into `vrid_floating_ip_list[]` sothat shared partition FIP will not get mixed into the l3v partition.
1. openstack loadbalancer flavorprofile create --name fp_35 --provider a10 --flavor-data '{"device-name": "device1"}'
openstack loadbalancer flavor create --name f_35 …
=> [BUG][STACK-2372]: [device-flavor] The VRID FIP is mixed for shared and l3v partition after loadbalancer/memebr deletion in l3v partition

a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
- Issue Description: [vthunder][negative] same nat pool name in flavor, when create lb will get error: Exception during message handling: Exists: 1
Here Interface from vthunder gets removed.
- https://a10networks.atlassian.net/browse/STACK-2382
- Revert flow of PlugVIP task was detaching the interface from amphorae.
PlugVIP==>revert==>unplug_vip==>unplug_aap_port==>unplug_network.
So, Copied the _unplug_aap_port_ method from Octavia into A10 neutron driver and removed the code which was detaching the port from instance. Earlier all entries were removed from port's AAP, added __remove_allowed_address_pair_from_port_ for removing specific VIP address.
1) Create flavor profile, flavor and loadbalancer.
```
openstack loadbalancer flavorprofile create --name fp_natpool_1 …
```
=> [STACK-2382]: Updated the revert flow so that interface didn't removed from vthunder

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Severity Level: Low
- Issue Description: [vthunder]: Failed to create lb and member on latest code
https://a10networks.atlassian.net/browse/STACK-2392
- Change the position of vthunder_conf and device_dict variable.
- Added dependencies as None for vthunder flow
- Removed SetupDeviceNetworkMap task from delete lb for vthunder.
1) Create lb, listener, pool and member
```
openstack loadbalancer create --name v1 --vip-subnet-id private-a-subnet
openstack loadbalancer listener create --name l1 v1 --protocol tcp --protocol-port 80
openstack loadbalancer pool create --name p1 --protocol tcp --lb-algorithm LEAST_CONNECTIONS --listener l1
openstack loadbalancer member create --address 10.0.0.199 --subnet-id private-a-subnet --protocol-port 80 --name m1 p1
stack@adeeb:~/adeeb/a10-octavia$ …
```
=> updated the code for vthunder flows

a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/tests/common/a10constants.py, a10_octavia/tests/unit/controller/worker/tasks/test_health_monitor_tasks.py
The hm name in a10-neutron-lbaas was set to a length of 28 characters, but the hm name in a10-octavia is set to 32.
- [STACK-2340](https://a10networks.atlassian.net/browse/STACK-2340)
- Added a call to get the hm before performing and update or a delete
- Skip if not found during delete
N/A
- Confirm _get_hm_name can return full uuid if hm name is full uuid
- Confirm _get_hm_name can return char of uuid if hm name is 28 chars
- Confirm _get_hm_name raises NotFound if not found
**Requires a10-nlbaas2oct env setup**
```
neutron lbaas-loadbalancer-create --name lb1 private-subnet
neutron lbaas-listener-create --protocol HTTP --protocol-port 80 --name l1-80 --loadbalancer lb1
neutron lbaas-pool-create --lb-algorithm ROUND_ROBIN --protocol http --name p1-80 --listener …
```
=> [DO NOT MERGE][a10-octavia-v1.3][STACK-2340] Fix for backwards compatibility issue with hm name 

a10_octavia/controller/worker/tasks/a10_network_tasks.py
- Issue Description: When a loadbalancer is created for a child project of admin with use_parent_partition=True and vrid FIP of the LB's subnet is already present there on the same parent partition(admin partition) on a different vthunder, then the VRID FIP is not getting created on the parent partition(admin partition) of the vthunder on which the LB is being created.
https://a10networks.atlassian.net/browse/STACK-2384
- Setting a flag **parent_vrid_fip_flag** as True if `hierarchical_multitenancy == 'enable' and use_parent_partition=True` in case of hardware thunders.
- If VRID FIP of the LB which is being created on parent partition is already present on parent partition on another vthunder, then `_replace_vrid_port()` will not get called as the …
=> [BUG][STACK-2384]: [device flavor] Should not block VRID floating ip between different vthunder partitions

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py
Issue Description: Create one lb but it failed due to TagInterface. Then the lb is in ERROR, but floating ip is assigned and configured on thunder, expect the vrid floating ip will be revoked, otherwise the floating ip will be kept there even the error lb deleted
https://a10networks.atlassian.net/browse/STACK-2394
1. Handle VRID flow added after TagInterface flow.
2. Since VRID_LIST is a mutable object, hence the VRID_LIST object is getting updated in handle VRID flow which causes revert flow receiving  updated VRID_LIST.
3. Added revert for updateVRIDDB.
- Create LB lb-1 with error.
openstack loadbalancer create --name l1 --vip-subnet-id provider-vlan-11-subnet
Check vthunder:
> !Section configuration: 125 bytes       
!
vrrp-a common 
device-id 2 
set-id 1 
enable …
=> [BUG][device flavor][STACK-2394]L vrid floating ip should not be assigned if lb is failed to be created.

a10_octavia/controller/worker/flows/vthunder_flows.py
Issue Description: Blade-params priority getting set in vrid 1, we could use vrid 0 for setting blade-param priority. 
https://a10networks.atlassian.net/browse/STACK-2278
Observations:
-  Default blade-param priority i.e, 150 does not get reflected on vthunder VRID 0.
-  While setting FIP the blade-param priority automatically set with default values, we can observe this in response to VRID FIP operations.
Changes:
- Removed the  config blade param priority in VRID 1 code from vthunder flow.
Need to check the reason the default blade-param priority not showing up in VRID 0.
- Create LB lb1 for vthunder flow, inspect call for VRID FIP operation
> stack@rahul:~/rahul/a10-octavia$ openstack loadbalancer list
+--------------------------------------+------+----------------- …
=> [BUG][vthunder: active-standby][STACK-2278]: the vrid 1 is used instead of vrid 0

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
If Bug Fix:
Issue Description: openstack loadbalancer set will failed, since loadbalancer_update flow missing parameters in store for HandleVRIDFloatingIP task.
https://a10networks.atlassian.net/browse/STACK-2399
- Provide proper a10constants.VTHUNDER_CONFIG and a10constants.USE_DEVICE_FLAVOR for vthunder update flow.
- create vrid if it is not exist on thunder.
<pre>
vrid=7
#use_parent_partition=True
[listener]
post_data = "abc=1"
#use_periodic_write_memory = 'enable'
devices = [
{ …
=> [STACK-2399] Fix set Loadbalancer error

a10_octavia/controller/worker/tasks/vthunder_tasks.py
optimize LB creation time
https://a10networks.atlassian.net/browse/STACK-2375
- task VCSSyncWait didn't exit the while loop when vMaster/vBlade are present.
<pre>
<b>[vthunder]
slb_no_snat_support = True
#amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4
amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4, 61305531-6e3a-44b4-8e67-05e93363dddc, a66685db-31ee-46c6-928a-ac034d87dc63, ec33a88d-3290-4ad6-95cc-226fcd2a4458
amp_ssh_key_name = …
=> [STACK-2375] optimize LB creation/deletion time

a10_octavia/api/drivers/driver.py, a10_octavia/api/drivers/flavor_schema.py, a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/network/drivers/neutron/a10_octavia_neutron.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
Added L2DSR flavor support.
https://a10networks.atlassian.net/browse/STACK-2387
https://a10networks.atlassian.net/browse/STACK-2388
https://a10networks.atlassian.net/browse/STACK-2389
- Added deployment schema in flavor_schema.py and added schema validation for deployment flavor in driver.py
- Added _AllowL2DSR_ task in create loadbalancer flow.
- Updated _AllowL2DSR_ api; when loadbalancer is created with deployment flavor and value of dsr_type is l2dsr_transparent then it will call  _allow_use_any_source_ip_on_egress_ for adding 0.0.0.0/0 in AAP for each amphora.
- Created _remove_any_source_ip_on_egress_ for removing 0.0.0.0/0 from interface's AAp.
- Created _DeleteL2DSR_; when last loadbalancer with deployement flavor will be removed then it call _remove_any_source_ip_on_egress_. …
=> [STACK-2385]: Added L2DSR Support

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py, requirements.txt
Don't allow device-name flavor use devices with project_id in configuration file
https://a10networks.atlassian.net/browse/STACK-2413
Don't allow device-name flavor use devices with project_id in configuration file
<pre>
<b>[hardware_thunder]
devices = [
{
"project_id": "3d21c71c4e4040599933bda62a76ae2f",
"ip_address": "192.168.90.45",
"username": "admin",
"password": "a10",
"device_name": "admin"
},
{
"project_id": "2aae8b6e8ddd4e2991b6c342824056b0",
"ip_address": "192.168.90.46",
"username": "admin",
"password": "a10",
#"hierarchical_multitenancy": "enable",
"device_name": "dev2",
"device_1": {
"mgmt_ip_address": "192.168.90.46",
"ethernet_interfaces": [{
"interface_num": 4,
"vlan_map": [
{"vlan_id": 3, "ve_ip": "192.168.190.61"},
{"vlan_id": 4, "ve_ip": …
=> [STACK-2413] device-flavor only allow devices without project_id

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
As the log, exception raise while getting the LB creation flow. The ctx counters are already increased, but since flow never run. So, flow_notification_handler can't be triggered to reduce the counter. So, counter never decreased.
```
File "/opt/stack/a10-octavia/a10_octavia/controller/worker/controller_worker.py", line 410, in create_load_balancer
load_balancer_id, topology=topology, listeners=lb.listeners)
File "/opt/stack/a10-octavia/a10_octavia/controller/worker/flows/a10_load_balancer_flows.py", line 100, in get_create_load_balancer_flow
lb.project_id)
```
https://a10networks.atlassian.net/browse/STACK-2356
- fix LB creation raise exception in revert flow issue.
- in control_worker.py, if ctx counter already increased (i.e. …
=> [STACK-2356] get_create_load_balancer_flow get lb failed in revert flow

a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
- Issue Description: When deleting lb(which is in ERROR state), it was removing interface from vthunder.
- https://a10networks.atlassian.net/browse/STACK-2382
- On creating lb with same nat pool name flavor, as expected it will go in error state. On reverting, new vthunder entry will be removed from vthunder repo. While deleting the same lb, the vthunder value returned from databases will be none, then lb_count_subnet will be 0, it causes to delete all ports. So changed the conditions for deleting the ports.
**1)Interface will not remove in revert flow.** 
a)Create lbs 
```
openstack loadbalancer flavorprofile create --name fp_natpool_1 --provider a10 --flavor-data '{"nat-pool":{"pool-name":"test","start-address":"1.1.1.2","end-address":"1.1.1.4","netmask":"/24"}}' …
```
=> [STACK-2382]: On deleting error state loadbalancer, interface will not be removed from vthunder.  

a10_octavia/controller/worker/tasks/nat_pool_tasks.py
NAT pool deleted unexpected when snat flavor use same pool name with different ip range in different flavor.
**Notice: this bug priority is low, because even pool is deleted. It will still be created when creating listener with the pool**
https://a10networks.atlassian.net/browse/STACK-2513
- In NatPoolCreate revert flavor, only delete NAT pool which created in execute().
<pre>
<b>N/A</b>
</pre>
- same as QA
```
openstack loadbalancer flavorprofile create --name fp_snat --provider a10 --flavor-data '{"nat-pool":{"pool-name":"pool1", "start-address":"192.168.90.201", "end-address":"192.168.90.210", "netmask":"/24" }}'
openstack loadbalancer flavor create --name f_snat --flavorprofile fp_snat
openstack loadbalancer flavorprofile create --name fp_snat1 …
```
=> [STACK-2513] NatPoolCreate revert flow only delete pools it created

a10_octavia/controller/worker/controller_worker.py
- Severity Level: Low
When device flavor is used, we will treat it as rack flow even there is not devices in configuration file.
https://a10networks.atlassian.net/browse/STACK-2517
rack/vthunder flow should decided according to the configuration file only. Even with device-name flavor.
<pre>
<b>[vthunder]
slb_no_snat_support = True
#amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4
amp_boot_network_list = …
=> [STACK-2517] check rack/vthunder via config file only

a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
- Issue Description:  [vThunder] Cleanup VIP port and security group for loadbalancers on fixed_subnets when deletion
- https://a10networks.atlassian.net/browse/STACK-2519
- While using fixed_networks, increase the lb_count_subnet so that only vip port get deleted.
1) When multiple network is in amp_network_list.
amp_boot_network_list = 01402810-aa7b-4a9d-a201-7b1df5f4bce3, 36dc5caf-cec1-4e34-befa-d6eafef39938, 2ee882b9-64f1-453c-9c61-b51a0e83ea7a
a) Create multiple lbs.
```
openstack loadbalancer create --name vs1 --vip-subnet-id private-a-subnet
openstack loadbalancer create --name vs2 --vip-subnet-id private-a-subnet
openstack loadbalancer create --name vs3 --vip-subnet-id private-b-subnet
openstack loadbalancer create --name vs4 --vip-subnet-id private-b-subnet …
```
=> [STACK-2519]: Fix for deleting vip ports and security groups in case of fixed_subnets

a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Severity Level - Medium
- Issue Description - [vthunder l2dsr] there's no 0.0.0.0/0 added in aap when create lb with l2dsr_support = True in a10-octavia.conf
https://a10networks.atlassian.net/browse/STACK-2527
- Add code for adding 0.0.0.0/0 in AAP when l2dsr_support = True in a10_config file 
<pre>
<b>
[vthunder]
</b>
</pre>
- Similar to QA
1) Create lb.
```
stack@adeeb:~/adeeb/a10-octavia$ openstack loadbalancer list
+--------------------------------------+------+----------------------------------+-------------+---------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | …
```
=> []STACK-2527]: Fix for adding 0.0.0.0/0 in interface AAP when a10_config file has l2dsr_support = True 

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py
When project_id is not in configuration, a10-octavia will use vThunder flow even the device flavor is specified.
https://a10networks.atlassian.net/browse/STACK-2526
When device flavor is specified and the device is in configuration. Use rack flow instead.
<pre>
vrid=7
#use_parent_partition=True
[listener]
post_data = "abc=1"
#use_periodic_write_memory = 'enable'
devices = [
{
"project_id": "a3ad21c71c4e4040599933bda62a76ae2f",
#"project_id": …
=> [STACK-2526] fix _is_rack_flow for device flavor

a10_octavia/controller/worker/controller_worker.py
- Severity Level : Medium
- Description: [vthunder] failed to set member and get error: MissingDependencies: 'execute' method on 'a10_octavia.controller.worker.tasks.a10_database_tasks.
- https://a10networks.atlassian.net/browse/STACK-2524
- Added _a10constants.VTHUNDER_CONFIG_ and _a10constants.USE_DEVICE_FLAVOR_  in store for _get_update_member_flow_ in controller worker.
- Similar to QA.
1) Create lb and other objects then set the member.
```
openstack loadbalancer create --name vs3 --vip-subnet-id private-a-subnet
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name l1 vs1
openstack loadbalancer pool create --protocol HTTP --lb-algorithm ROUND_ROBIN --listener l1 --name p1
openstack loadbalancer member create --address 10.0.0.90 --subnet-id private-a-subnet …
```
=> [STACK_2524]: [vthunder]Fix missing dependency issue for member set command

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py
- Severity Level: Critical
In taskflow flows some parameter is missing and cause openstack command not work.
https://a10networks.atlassian.net/browse/STACK-2530
https://a10networks.atlassian.net/browse/STACK-2533
provide the parameters properly.
<pre>
vrid=7
#use_parent_partition=True
[listener]
post_data = "abc=1"
#use_periodic_write_memory = 'enable'
devices = [
{
"project_id": "a3ad21c71c4e4040599933bda62a76ae2f",
#"project_id": "3d21c71c4e4040599933bda62a76ae2f",
"ip_address": …
=> [STACK-2530][STACK-2533] parameter missing in some flow

a10_octavia/controller/worker/controller_worker.py
Severity Level: Medium
Issue Description: [RACKFLOW] Failed to create a Healthminitor and LB got stuck in PENDING_UPDATE state
- https://a10networks.atlassian.net/browse/STACK-2539
- Add retry decorator in create_health monitor and create_listener API.
Similar to QA
1) Create lb, listener, pool and health monitor.
```
openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --flavor f23 --name lb23
openstack loadbalancer listener create --protocol TCP --protocol-port 8022 --name lt1_lb23 lb23
openstack loadbalancer pool create --protocol TCP --lb-algorithm SOURCE_IP --listener lt1_lb23 --name pl1_lt1_lb23
openstack loadbalancer healthmonitor create --delay 7 --timeout 6 --max-retries 3 --type TCP --name hm1_pl1_lt1_lb23 pl1_lt1_lb23
stack@adeeb:~/adeeb/a10-octavia$ openstack …
```
=> [STACK-2539]: Fix for fetching healthmonitor and listener object from db

a10_octavia/controller/worker/tasks/a10_network_tasks.py
when using device-name flavor, global vrid-floating-ip can't be applied.
https://a10networks.atlassian.net/browse/STACK-2486
When device didn't specify FIP, use global FIP config.
<pre>
#use_parent_partition=True
[listener]
post_data = "abc=1"
#use_periodic_write_memory = 'enable'
devices = [
{
"project_id": "3d21c71c4e4040599933bda62a76ae2f",
"ip_address": "192.168.90.45",
"username": "admin",
"password": "a10",
"vrid_floating_ip" : "dhcp",
"device_name": "admin"
},
{ …
=> [STACK-2486] fix device flavor can not use global floating-ip config

a10_octavia/network/drivers/neutron/a10_octavia_neutron.py
Deletion of instance port would result in inability to delete loadbalancer.
[STACK-2339](https://a10networks.atlassian.net/browse/STACK-2339)
- Added exception handler around show port 
N/A
N/A
Example Config
```
[a10_global]
vrid_floating_ip = ".9" <---- Required
[vthunder]
default_vthunder_username = admin
default_vthunder_password = a10
default_axapi_version = 30
....
loadbalancer_topology = ACTIVE_STANDBY   <--- Required
```
`openstack loadbalancer create --name lb1 --vip-subnet-id private-subnet`
Add breakpoint to line 433 of the a10_octavia_neutron network driver
```sudo systemctl restart a10-c*```
`openstack loadbalancer delete lb1`
When the breakpoint is hit, use rpdb to print the `port_id` variable contents. Use the output to execute …
=> [STACK-2339] Removal of AAP locks lb in error state during delete

a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Issue Description: [vthunder] 0.0.0.0/0 is delete wronlgy when delete one l2dsr lb created by flavor while another l2dsr is still there which is created by config file
- https://a10networks.atlassian.net/browse/STACK-2531
- Added condition when l2dsr_support mentioned in a10_config file then not to delete 0.0.0.0/0 from AAP
<pre>
<b>
[vthunder]
</b>
</pre>
- Required: List of steps to manually test feature or fix 
Similar to QA
1) Create lbs
```
openstack loadbalancer create --name v1 --vip-subnet-id private-11-subnet ( config file will be attached)
openstack loadbalancer flavorprofile create --name fpdsr --provider a10 --flavor-data …
```
=> [STACK-2531]: Fix for not deleting 0.0.0.0/0 from AAP if l2dsr_support= True mentioned in config

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
Added support for objects using l3v partitions which have been migrated from Neutron LBaaS to Octavia
[STACK-2341](https://a10networks.atlassian.net/browse/STACK-2341)
- Migrated HMT handling in CheckExistingProjectToThunderMappedEntries task to HandleACOSPartitionChange task
- Executed HandleACOSCPartitionChange task before vthunder repo create to ensure proper partition name usage
- Added extra get request to try with 13 char if 14 char hmt partition is not found
Backwards compatibility is handled by checking if the partition name exists with it being at most 14 char. If it does not exist and HMT is enabled, then a check is done against 13 char.
N/A
- Added test that a previously existing hmt partition with 13 chars is used instead of creation for 14 char partition
- Migrated other test …
=> [STACK-2341] Backwards compatibility for partition name

a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/db/migration/alembic_migrations/versions/1722c3166462_vrid_table_extend_owner_size.py, a10_octavia/db/repositories.py
- Severity Level :High
For vrid db table, we use device-name as owner. 
But when using device-name and the device configured with HTM and use-parent-partition. Then the device and partition is not 1 to 1 anymore. (the device-name may configured on different partitions)
And for this case, we need more database entry in vrid table for different partition. So, we can't just use device-name as owner.
https://a10networks.atlassian.net/browse/STACK-2488
User "device-name + partition_name" as owner in vrid table.
<pre>
use_parent_partition=True
[listener]
post_data = …
=> [STACK-2488] device flavor use device and partition as owner

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/repositories.py
- Required: Severity Level Low
-STACK-2552/2553, we raise exception for project_id in device flavor device even in delete/update flow.
- STACK-2563, this should not happen. We only check topology in vThunder flow, but QA's test case should be rack flow. I think QA make some mistake in configuration.
https://a10networks.atlassian.net/browse/STACK-2552
https://a10networks.atlassian.net/browse/STACK-2553
https://a10networks.atlassian.net/browse/STACK-2563
- STACK-2552/2553: in delete flow don't raise exception when project_id is in device flavor device.
<pre>
<b>[hardware_thunder]
devices = [
{
"project_id": "3d21c71c4e4040599933bda62a76ae2f",
"ip_address": "192.168.90.45",
"username": "admin",
"password": "a10",
"vrid_floating_ip" : "dhcp", …
=> [STACK-2552][STACK-2553][STACK-2563] check topology only on amphora vthunder

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
We never remove 0.0.0.0/0 from AAP when use configuration to deploy l2dsr.
https://a10networks.atlassian.net/browse/STACK-2572
Add logic to remove 0.0.0.0/0 from AAP when L2DSR deploy by configuration.
<pre>
<b>[vthunder]
slb_no_snat_support = True
#amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4
amp_boot_network_list = 7f8ddd7f-c5c3-463a-b1c3-596f988480a4, 61305531-6e3a-44b4-8e67-05e93363dddc, …
=> [STACK-2572] remove AAP for L2DSR via configuration

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Issue Description: [device flavor] member side floating ip will be leftover if configured same subnet members on 2 different devices
- https://a10networks.atlassian.net/browse/STACK-2541
- In case of device_flavor, get the pool list available on thunder device. then count the pool which has given subnet.
<pre>
<b>
devices = [
{
"ip_address":"10.0.0.55",
"password":"a10",
"partition_name":'p1',
"device_name":"AX35",
"vrid_floating_ip" : "dhcp"
},
{
"ip_address":"10.0.0.50",
"password":"a10",
"partition_name":'p1',
"device_name":"AX45",
"vrid_floating_ip" : "dhcp"
}
]
</b>
</pre>
Similar to QA.
1) Create lbs and other objects
```
openstack loadbalancer flavorprofile create --name fp_natpool --provider a10 …
```
=> [STACK-2541]: Fix for deleting member side floating ip when configured same subnet members on 2 different devices[device_flavor]

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Issue Description: [device flavor] member is kept on device if use same member on 2 devices
- https://a10networks.atlassian.net/browse/STACK-2542
- In case of device_flavor, get the pool list available on thunder device. then count pool by ip in pool_list.
<pre>
devices = [
{
"ip_address":"10.0.0.55",
"password":"a10",
"partition_name":'p1',
"device_name":"AX35",
"vrid_floating_ip" : "dhcp"
},
{
"ip_address":"10.0.0.50",
"password":"a10",
"partition_name":'p1',
"device_name":"AX45",
"vrid_floating_ip" : "dhcp"
}
]
</pre>
- Similar to QA.
1) Create lbs and other objects
```
openstack loadbalancer flavorprofile create --name fp_natpool --provider a10 --flavor-data  '{
"device-name": "AX35",
"nat-pool":{ …
```
=> [STACK-2542]: [device flavor]Fix for deleting members when members created with same IP on two devices

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_pool_flows.py
- Issue Description: [device flavor]failed to delete pool and get MissingDependencies
- https://a10networks.atlassian.net/browse/STACK-2580
- Added missing dependency in delete pool flow 
1) Create lb and other objects
```
openstack loadbalancer flavorprofile create --name fp_natpool --provider a10 --flavor-data  '{
"device-name": "AX35",
"nat-pool":{
"pool-name":"pool1",
"start-address":"10.0.11.111",
"end-address":"10.0.11.115",
"netmask":"/24"
}
}'
openstack loadbalancer flavor create --name f_natpool --flavorprofile fp_natpool
openstack loadbalancer create --name 3dsr --flavor f_natpool --vip-subnet-id provider-vlan-13-subnet
openstack loadbalancer listener create --name l3dsr 3dsr --protocol tcp --protocol-port 80
openstack loadbalancer pool create --name …
```
=> [STACK-2580]: [device flavor]failed to delete pool and get MissingDependencies

a10_octavia/controller/worker/tasks/server_tasks.py
If the server name cannot be found, the flow enters the except block which logs an debug message. However, this results in the `server_name` variable not being defined later in the flow. This does not affect other tasks as the log is the last operation to occur.
[STACK-2628](https://a10networks.atlassian.net/browse/STACK-2628)
Added return after location of server name has failed.
N/A
N/A
```
openstack loadbalancer create --vip-subnet-id public-subnet --name lb1
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name l1 lb1
openstack loadbalancer pool create --protocol HTTP --lb-algorithm ROUND_ROBIN --listener l1 --name pool1
openstack loadbalancer member create --subnet-id private-subnet --name mem1 pool1
```
```
mysql> use octavia; …
```
=> [STACK-2628] Added return when server name is not found

a10_octavia/controller/worker/tasks/utils.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
Verify vThunder flow basic functionalities for ACTIVE_STANDBY mode
https://a10networks.atlassian.net/browse/STACK-2354
- In Python3 it is expected to provide the name of exception in except block which inherits directly or indirectly from your base class Exception. So when we do specify exceptions by clubbing into a method it treats it as a method of the object and not the class that inherits from the Exception.
- To resolve this removed call for **thunder_busy_exceptions()** and raised those exceptions specified in **thunder_busy_exceptions()** directly in **except** block
- Create/update/Delete a LB, Listener, Pool, Member, HM, L7Policy and L7rule
**Create a LB**
```
stack@sana:~$ openstack loadbalancer create --vip-subnet-id vip_subnet --name lb1 …
```
=> [STACK-2354] Active-Standby Mode Test

a10_octavia/controller/worker/tasks/vthunder_tasks.py
Enable write memory and create lbs with different networks, then on interval, lbs were going into error state except the last lb.
- https://a10networks.atlassian.net/browse/STACK-2173
- After write memory operation the updating the last_write_memory column of vthunder.
<pre>
write_mem_interval = 1200
</pre>
1) Create lbs with different networks.
```
stack@victoria:~/adeeb/a10-octavia$ openstack loadbalancer create --name vs1 --vip-subnet-id private-a-subnet
| availability_zone   | None …
```
=> [STACK-2173]: [Vthunder][Enable write memory] Loadbalancer was going in ERROR state while performing write memory.

a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py
Severity: Low
Handling of the backwards compatibility of real server naming only extends towards the update and delete tasks. However, servers can be used by multiple members. Therefore, the backwards compatibility should also occur in the member create.
- [STACK-2639](https://a10networks.atlassian.net/browse/STACK-2639)
N/A
- Updated old test cases to reflect changes in update logic
- Renamed revert test to match intent
- Added create test for multi port 
```
neutron lbaas-loadbalancer-create --name lb1 provider-vlan-11-subnet
neutron lbaas-listener-create --protocol http --protocol-port 5 --name l1 --loadbalancer lb1
neutron lbaas-pool-create --lb-algorithm ROUND_ROBIN --protocol …
```
=> [STACK-2639] Added multi-port compatability with migrated neutron-lbaas servers

a10_octavia/common/a10constants.py, a10_octavia/common/exceptions.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Required: Severity Level: Critical
The a10-nlbaas2oct will use device-name flavor and configuration file will have project_id in device-name flavor device. This hit the limitation of a10-octavia:
**STACK-2413: ​The device-name flavor can only specify devices that didn’t specify project_id in configuration file.**
https://a10networks.atlassian.net/browse/STACK-2601
https://a10networks.atlassian.net/browse/STACK-2606
For the limitation in a10-octavia:
- For the Remove the code to raise the error
- Update the RN and move this limitation as a known Issue (as below)
> STACK-2413: ​For device-name flavor with VRID Floating-ip configured; If user create loadbalancer by both project_id and device-name flavor, the loadbalancer creation may failed or VRID Floating-IP …
=> [STACK-2601][STACK-2606] remove cannot have project_id attribute in device-name flavor devie limitation

a10_octavia/common/utils.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
Used vthunder's ip_address and partition_name as ip_partition as a owner in vrid table for handling correct vrid FIP creation and deletion cases among different partitions on same and different vthunders
https://a10networks.atlassian.net/browse/STACK-2575
- Stored vthunder.ip_address + "_"+ vthunder.partition_name as owner in vrid table for all cases(device_flavor as well as non device_flavor cases)
- Modified `GetMembersOnThunder()` task to get members on currently active partition on a thunder device. 
openstack loadbalancer flavorprofile create --name fp_35 --provider a10 --flavor-data '{"device-name": "device1"}'
openstack loadbalancer flavor create --name f_35 --flavorprofile fp_35
openstack loadbalancer flavorprofile create --name fp_45 --provider a10 --flavor-data '{"device-name": …
=> [STACK-2575]: Refined vrid table to use vthunder's ip+partition as owner.

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_server_tasks.py
- Add unset operation support for load balancer and listener in Rack and Automated flow 
**Design Document:**
https://teams.microsoft.com/l/file/FB58C9F5-594E-4EBB-BF00-72E1406DC12B?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v2.0%20-%20Victoria%20Support%2FUnset%20Operation%20Support%2F%5BDD%5D%20Unset%20Operation%20Support.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb
https://a10networks.atlassian.net/browse/STACK-2663
https://a10networks.atlassian.net/browse/STACK-2664 …
=> [STACK-2663][STACK-2664][STACK-2665]unset option for loadbalancer rack/vthunder flow

a10_octavia/controller/worker/tasks/persist_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_persist_tasks.py
Add support for the pool Unset and member unset operation in both Rack flow and Automated flow.
**Design Document**
https://teams.microsoft.com/l/file/FB58C9F5-594E-4EBB-BF00-72E1406DC12B?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v2.0%20-%20Victoria%20Support%2FUnset%20Operation%20Support%2F%5BDD%5D%20Unset%20Operation%20Support.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb
https://a10networks.atlassian.net/browse/STACK-2666
https://a10networks.atlassian.net/browse/STACK-2667 …
=> [STACK-2666][STACK-2667][STACK-2668][STACK-2669]unset option for pool rack flow 

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Features story: https://a10networks.atlassian.net/browse/STACK-2322
- design document: https://teams.microsoft.com/l/file/8ACCF57A-2CEF-4E5E-A767-93EDC0ED77DD?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v2.0%20-%20Victoria%20Support%2FvThunder%20VCS%20issues%20Enhancement%2F%5BDD%5D%20vThunder%20VCS%20issues%20Enhancement.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb
acos-client side changes: https://github.com/a10networks/acos-client/pull/351 …
=> [a10-octavia v2.0] Feature/vcs negotiate state

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
Added support for Dynamic Interface Detection Enhancement for ACTIVE_STANDBY mode with respect to 5.2.1-p2 ACOS image.
https://teams.microsoft.com/l/file/8ACCF57A-2CEF-4E5E-A767-93EDC0ED77DD?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v2.0%20-%20Victoria%20Support%2FvThunder%20VCS%20issues%20Enhancement%2F%5BDD%5D%20vThunder%20VCS%20issues%20Enhancement.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb
https://github.com/a10networks/acos-client/pull/354 …
=> [STACK-2322][STACK-2709]: Dynamic Interface Detection Enhancement for loadbalancers and members

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/persist_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_persist_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_port_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_virtual_server_tasks.py
Add Unset Operation support for automated and rack flow 
**Design Document:** 
https://teams.microsoft.com/l/file/FB58C9F5-594E-4EBB-BF00-72E1406DC12B?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v2.0%20-%20Victoria%20Support%2FUnset%20Operation%20Support%2F%5BDD%5D%20Unset%20Operation%20Support.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb
https://a10networks.atlassian.net/browse/STACK-2359
- Updated the objects of Loadbalancer and Listener to get current values specified on …
=> [2359]PR to Merge Unset Operation support feature/unset branch into experimental/victoria_ff branch

README.md, a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/virtual_server_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/repositories.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_vthunder_tasks.py
Merged the latest master branch into experimental/victoria_ff branch
https://a10networks.atlassian.net/browse/STACK-2723
https://github.com/a10networks/acos-client/pull/356
- Resolved the merge conflicts.
Tested Dynamic Interface Detection Enhancement feature for ACTIVE_STANDBY mode after the merging of master branch into experimental/victoria_ff branch
**1. Create a loadbalancer in subnet provider-vlan-11-subnet**
stack@neha-victoria:~$ openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name lb1
```
| availability_zone …
```
=> [STACK-2723]: Merge the latest master branch into experimental/victoria_ff branch

a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/server_tasks.py
Failed to set member disable/enable for the 1st  time
**Severity Level :** Medium
https://a10networks.atlassian.net/browse/STACK-2776
- Updated the object of a **member**  as per the current values specified on Openstack CLI.
- Used **update_dict** for getting current values from Openstack CLI and to update the member object.
**Automated flow:**
**1. Create a loadbalancer**
```
stack@sana:~$ openstack loadbalancer create --name v4 --vip-subnet-id vip_subnet
| availability_zone   | None                                 |
| created_at …
```
=> [STACK-2776][vthunder member] failed to set member disable/enable for the 1st  time

a10_octavia/controller/worker/tasks/virtual_server_tasks.py
- Issue Description: Character length limit is 63 for virtual-servers.
Merge this fix in to release/v1.3.2
- https://a10networks.atlassian.net/browse/STACK-2762
- Added a warning if the description limit exceeds the character limit.
- Trim the description length to 61 characters. So that after adding double quotes ("") , it does not exceeds 63 characters.
Please look PR#491 for more details.
=> [STACK-2762]: Trim the description length of virtual server to 61 characters; merge it to release v1_3_2

a10_octavia/controller/worker/tasks/virtual_port_tasks.py
- Issue Description: Connection Limit Config Error
- https://a10networks.atlassian.net/browse/STACK-2765
- Raised the exception if connection limit is out of bound
1) Create lb and create listener and pass --connection-limit 0 in the create listener command.
openstack loadbalancer listener create --name l1 v2 --protocol http --protocol-port 8081 --connection-limit 0
```
stack@victoria:~/addeb2/a10-octavia$ openstack loadbalancer list
+--------------------------------------+------+----------------------------------+-------------+---------------------+------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | operating_status | provider | …
```
=> [STACK-2765]: Raised exception if connection limit is out of bound

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/repositories.py
- Issue Description :[vthunder][l2dsr_support & slb_no_snat_support] only work when creating vthunders
- https://a10networks.atlassian.net/browse/STACK-2620
- On running set command for lb/member, adding and removing  0.0.0.0/0 from allowed address pair based on the value of l2dsr_support and slb_no_snat_support in a10_config file.
1) Create lb and other objects.
```
a10_config file:
[vthunder]
#l2dsr_support = True
#slb_no_snat_support=True
stack@victoria:~/addeb2/a10-octavia$ openstack loadbalancer  list
+--------------------------------------+------+----------------------------------+-------------+---------------------+------------------+----------+
| id …
```
=> [STACK-2620]: Updating allowed address pair while running set command for loadbalancer/member

a10_octavia/cmd/a10_health_manager.py
If Bug Fix:
- Required: Severity Level: High
Failed to restart health manager service. The health monitor stop takes long and 5550 port is never released after service restart.
https://a10networks.atlassian.net/browse/STACK-2794
The stats periodical works seems didn't shutdown after restart. reference octavia code to shutdown it when restart:
https://github.com/openstack/octavia/blob/5c8f60614e97b76d95b7f9b90bc142de4dea1cdd/octavia/cmd/health_manager.py#L53
<pre>
<b>[a10_health_manager]
udp_server_ip_address = 192.168.0.200
bind_port = 5550
bind_ip = 192.168.0.200
heartbeat_interval = 20
health_check_timeout = 3
health_check_max_retries = 5
heartbeat_key = insecure
heartbeat_timeout = 30
failover_timeout = 600
health_check_interval = 10
</b>
</pre>
sudo …
=> [STACK-2794] shutdown health manager executor threads

a10_octavia/common/config_options.py, a10_octavia/common/exceptions.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
Added support for **default_flavor_id** config option so that users working with a limited feature set don't have to specify as much information during loadbalancer create.
https://teams.microsoft.com/l/file/18D8570C-E48A-4177-A841-7F1F19168BD3?tenantId=91d27ab9-8c5e-41d4-82e8-3d1bf81fcb2f&fileType=docx&objectUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack%2FShared%20Documents%2FDevelopment%2FResearch%20%26%20Design%2Fa10-octavia%20v1.3.2%20Default%20Flavor-ID%20Support%2FDefault%20flavor-ID%20configuration%20option%20support.docx&baseUrl=https%3A%2F%2Fa10networks.sharepoint.com%2Fsites%2FOpenstack&serviceName=teams&threadId=19:0f1acbb173d74758b05ee8bacb000d68@thread.tacv2&groupId=37bbf3ad-c05a-4e67-b0cc-12bcd1479beb
https://a10networks.atlassian.net/browse/STACK-2764 …
=> [Feature][STACK-2764]: Global flavor ID configuration option support

a10_octavia/common/a10constants.py, a10_octavia/common/config_options.py, a10_octavia/common/exceptions.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
Merged global flavor ID configuration option feature to release/v1_3_2 branch and tested it on stein version.
https://a10networks.atlassian.net/browse/STACK-2845
- Added a config option default_flavor_id in a10_global section of a10-octavia.conf file.
- In GetFlavorData() task, assigning default_flavor_id to flavor_id iff a flavor with --flavor parameter is not passed during the loadbalancer creation.
- If flavor with the default_flavor_id is not present in flavor table of octavia DB, then raising an exception FlavorNotFound.
- Created FlavorNotFound exception which will give a message as " Flavor <flavor_id> specified in the configuration file is unable to locate, Please create the flavor in advance."
- In create_load_balancer() method of controller_worker.py, if lb.flavor_id is None and …
=> [STACK-2845]: Merge global flavor ID configuration option support feature to release/v1_3_2 branch

a10_octavia/controller/worker/tasks/utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_utils.py
- Issue Description: Facing an error when slb objects are created using a flavor with name-expression is used in the flavor and without specifying `--name` parameter during their creation.
https://a10networks.atlassian.net/browse/STACK-2891
- When `--name` is not specified during slb objects creation but flavor with name-expression is used, then the name is getting passed as None to `parse_name_expressions()` method and this is causing an error at `re.search()` call in it as name is a NoneType object here.
- So checking whether name is not None before calling this `re.search()` method.
- If it is None, then flavor_data will be returned as {}
N/A
Given a loadbalancer, when it is created without --name parameter, then it should get created without attaching …
=> [STACK-2891][For release/v1_3_2]: Create slb objects without specifying --name parameter failed with name-expression is used in the flavor

a10_octavia/controller/worker/tasks/utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_utils.py
- Issue Description: Facing an error when slb objects are created using a flavor with name-expression is used in the flavor and without specifying `--name` parameter during their creation.
https://a10networks.atlassian.net/browse/STACK-2891
- When `--name` is not specified during slb objects creation but flavor with name-expression is used, then the name is getting passed as None to `parse_name_expressions()` method and this is causing an error at `re.search()` call in it as name is a NoneType object here.
- So checking whether name is not None before calling this `re.search()` method.
- If it is None, then flavor_data will be returned as {}
N/A
Given a loadbalancer, when it is created without --name parameter, then it should get created without attaching …
=> [STACK-2891][For victoria]: Create slb objects without specifying --name parameter failed with name-expression is used in the flavor

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py
If Bug Fix:
It goes to vthunder flow when use device-name flavor in default_flavor_id.
https://a10networks.atlassian.net/browse/STACK-2933
https://a10networks.atlassian.net/browse/STACK-2934
In controller_worker.py create_load_balancer(), 
- a10-octavia didn't get the default flavor when no flavor is specified for the loadbalander. Therefore, 
- _is_rack_flow() can't get the device-name flavor and think it is vthunder flow.
Also add some code in ValidateComputeForProject task to provide more information in log. In case customer didn't configure properly.
<pre>
<b>[vthunder]
amp_image_owner_id = …
=> [STACK-2933] device-name flavor failed in default_flavor_id option

a10_octavia/controller/worker/tasks/a10_database_tasks.py
If Bug Fix:
It goes to vthunder flow when use device-name flavor in default_flavor_id.
https://a10networks.atlassian.net/browse/STACK-2933
https://a10networks.atlassian.net/browse/STACK-2934
In controller_worker.py create_load_balancer(), 
- a10-octavia didn't get the default flavor when no flavor is specified for the loadbalander. Therefore, 
- _is_rack_flow() can't get the device-name flavor and think it is vthunder flow.
Also add some code in ValidateComputeForProject task to provide more information in log. In case customer didn't configure properly.
<pre>
<b>[vthunder]
amp_image_owner_id = …
=> [STACK-2933] update for review comments

a10_octavia/api/drivers/driver.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
Added support for batch update members feature for rack flows in a10-octavia.
https://a10networks.atlassian.net/browse/STACK-2932
https://a10networks.atlassian.net/browse/STACK-2900
https://a10networks.atlassian.net/browse/STACK-2901
https://a10networks.atlassian.net/browse/STACK-2926
https://a10networks.atlassian.net/browse/STACK-2927
https://a10networks.atlassian.net/browse/STACK-2943
https://a10networks.atlassian.net/browse/STACK-2928
- Implemented `member_batch_update()` API in driver.py
- Implemented `batch_update_members()` method specific to rack_flows in controller_worker.py 
- Created a flows `get_rack_vthunder_batch_update_members_flow()` in a10_member_flows for batch member update feature.
- Added tasks for handling member creation, deletion and updation upon triggering …
=> [STACK-2811]: Batch Member Update support for rack flows.

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_compute_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Issue Description: [vthunder: active-standby] the lb is failed to be deleted if the vthunder pair get damaged
- https://a10networks.atlassian.net/browse/STACK-2235
- Check the status of amphora whether it is active or not.
- On the value of status of amphora, check the Vthuder connectivity and VCSSyncWait
- N/A
- Added _test_compute_amphora_status_active_, _test_compute_amphora_status_shutoff_ and _test_get_backup_vthunder_by_loadbalancer_ unit test cases. 
Case 1: shutdown the master node and delete lb
1) Create lbs
```
openstack loadbalancer create --name v1 --vip-subnet-id private-a-subnet
openstack loadbalancer create --name v2 --vip-subnet-id private-a-subnet
stack@victoria:~/addeb2/a10-octavia$ openstack loadbalancer list …
```
=> [STACK-2235][Active-Standby]: Support for deleting lb when one node is shutdown in active-standby

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_member_flows.py
Added basic support for batch update members feature for vthunder flows.
https://a10networks.atlassian.net/browse/STACK-2925
https://a10networks.atlassian.net/browse/STACK-2902
https://a10networks.atlassian.net/browse/STACK-2903
https://a10networks.atlassian.net/browse/STACK-2904
https://a10networks.atlassian.net/browse/STACK-2917
- Added suport for **get_batch_update_members_flow** in controller_worker.py
- Created a flow **get_batch_update_members_flow** in a10_member_flows for batch member update.
- Added tasks for handling member create, delete and update operation inside  **get_batch_update_members_flow**.
- Added support for the active standby topology as well.
- Added support for VRID and NAT POOL configuration
**Single topology:**
**Create a loadbalancer, listener, pool and …
=> [STACK-2930] Batch Member Update Support for vthunder flow

a10_octavia/controller/healthmanager/a10_health_manager.py, a10_octavia/db/repositories.py
If Bug Fix:
Prevent failover process running on hardware thunders
https://a10networks.atlassian.net/browse/STACK-2920
For hardware thunder, the amphora_id will be NULL in vthunders table. So, we can use this difference to prevent failover on hardware thunders.
<pre>
<b>stack@ytsai-victoria1:~/source/a10-octavia$ sed -e '/^#/d' /etc/a10/a10-octavia.conf  | grep -Ev "^$"
[vthunder]
amp_image_owner_id = 4b670176da5046e188aa0a503fd4cebb
amp_secgroup_list = d93900d4-44b5-4ac1-a80b-a80901595b54
amp_flavor_id = 1d0915fe-76e4-486f-a9b0-185ed0a57a47
amp_boot_network_list = …
=> [STACK-2920] Prevent failover process hardware thunder

a10_octavia/controller/worker/tasks/a10_compute_tasks.py
If Bug Fix:
For paused vthunder, health manager will still failover for it.
https://a10networks.atlassian.net/browse/STACK-2944
The try/except was added for the task, but it will cause the a10_exceptions.FailoverOnPausedCompute() exception be ignore. So, for a10_exceptions.FailoverOnPausedCompute raise it to stop the failover for paused vthunder.
<pre>
<b>[vthunder]
amp_image_owner_id = 4b670176da5046e188aa0a503fd4cebb
amp_secgroup_list = d93900d4-44b5-4ac1-a80b-a80901595b54
amp_flavor_id = 1d0915fe-76e4-486f-a9b0-185ed0a57a47
amp_boot_network_list = …
=> [STACK-2944] Fix failover for paused vthunder

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Issue Description: Missing Dependency error on deleting lb which is in Error state
- https://a10networks.atlassian.net/browse/STACK-2961
- Added a10constants.MASTER_AMPHORA_STATUS with default value in controller_worker.py
- N/A
- N/A
- Similar to QA
1) Delete the lb which is in Error state
```
stack@victoria:~/addeb2/a10-octavia$ openstack loadbalancer list
+--------------------------------------+------+----------------------------------+-------------+---------------------+------------------+----------+
| id                                   | name | project_id                       | vip_address | provisioning_status | operating_status | provider |
+--------------------------------------+------+----------------------------------+-------------+------------------ …
```
=> [STACK-2961]: Fixed missing dependency error

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py
- Severity Level: Medium 
- Issue Description: Able to create a member successfully though provided **ip_address** from one subnet and specified different subnet for the **subnet_id** parameter.
https://a10networks.atlassian.net/browse/STACK-2973
- Added a task **ValidateSubnet** for validating the **ip_address** belongs to a specified **subnet** or not
- If IP is not in the range of specified subnet raised a custom exception **IPAddressNotInSubentRangeError**.
- Added **ValidateSubnet** task in the **get_create_member_flow**, **get_rack_vthunder_create_member_flow**, **get_rack_vthunder_batch_update_members_flow** and **get_batch_update_members_flow**
**Rack Flow:**
```
stack@automation-1:~#openstack loadbalancer list
+--------------------------------------+------+------------------------ …
```
=> [BUG][STACK-2973][Rack Flow] Can able to create member when address and subnet_id are conflict

a10_octavia/controller/worker/tasks/a10_network_tasks.py
Added a check for subnet_id in ValidateSubnet task to resolve an issue for member creation without specifying subnet_id to it.
https://a10networks.atlassian.net/browse/STACK-2962
Added a check for subnet_id in ValidateSubnet task to resolve an issue for member creation without specifying subnet_id to it.
Refer PR https://github.com/a10networks/a10-octavia/pull/529
=> [STACK-2962]: Added a check for subnet_id in ValidateSubnet task

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py
**Severity Level:** Medium
**Issue Description:** Able to update a member successfully though provided ip_address from one subnet and specified different subnet for the subnet_id parameter.
https://a10networks.atlassian.net/browse/STACK-2988
- Added **ValidateSubnet** task in the **get_update_member_flow**, **get_rack_vthunder_update_member_flow**, **get_rack_vthunder_batch_update_members_flow** and **get_batch_update_members_flow**.
**Rack Flow:**
- Create a LB, listener and pool
```
stack@automation-1:~#openstack loadbalancer list
+--------------------------------------+------+----------------------------------+---------------+---------------------+----------+
| id                                   | name | project_id                       | vip_address   | provisioning_status | …
```
=> [BUG][STACK-2988][Rack Flow] when try to update member with when address and subnet id is different

a10_octavia/controller/worker/controller_worker.py, a10_octavia/db/repositories.py
- Severity Level : High
- Issue Description: Only entry for the vMaster device is present in listener_statistics table and entry for the vBlade device is not present 
https://a10networks.atlassian.net/browse/STACK-2937
- Previously we use to ignore blade device while fetching vthunders, used query which fetches all vthunder devices. 
```
stack@rahul:~/rahul/a10-octavia$ openstack loadbalancer listener list
+--------------------------------------+-----------------+-----------+----------------------------------+----------+---------------+----------------+
| id                                   | default_pool_id | name      | project_id                       | protocol | protocol_port | admin_state_up |
+--------------------------------------+-----------------+-----------+-------------------- …
```
=> [BUG][STACK-2937][Loadbalancer statistics][Automated Flow] Loadbalancer statistics for the vBlade device is not present in MYSQL 

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py
If Bug Fix:
Loadbalancer becomes pending_update after created. 
https://a10networks.atlassian.net/browse/STACK-2941
This should be happen because a10-octavia using the spare vthunder that is not ready yet.
So, for spare vthunder creation. a10-octavia will set the status to booting intead now. And set to ready until the creation flow is finished.
<pre>
<b>stack@ytsai-victoria1:~/source/a10-octavia$ sed -e '/^#/d' /etc/a10/a10-octavia.conf  | grep -Ev "^$"
[vthunder]
amp_image_owner_id = 4b670176da5046e188aa0a503fd4cebb
amp_secgroup_list = …
=> [STACK-2941] Prevent create LB in booting spare vthunder

a10_octavia/controller/worker/flows/vthunder_flows.py
If Bug Fix:
Task name duplicated.
https://a10networks.atlassian.net/browse/STACK-2999
Add subflow name in the task name
<pre>
<b>N/A</b>
</pre>
openstack loadbalancer create --vip-subnet-id tp92 --name vip2
The issue if fixed, but see another error.
Which is get_glm_license_subflow() subflow can't get AMPHORA in the flow store. Will pass this problem to Hunter.
=> [STACK-2999] add task name with subflow name

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/vthunder_flows.py
When a second loadbalancer is created in the same project, the glm tasks are not ignored. This occurs because the glm tasks are not added directly to the create amphora flow which the decider is controlling. The decider is set to the flow level so any subsequent flows will not be ignored.
```
amp_for_lb_flow.link(allocate_and_associate_amp, map_lb_to_vthunder,
decider=self._allocate_amp_to_lb_decider,
decider_depth='flow')
amp_for_lb_flow.link(allocate_and_associate_amp, create_amp,
decider=self._create_new_amp_for_lb_decider,
decider_depth='flow')
```
- [STACK-2999](https://a10networks.atlassian.net/browse/STACK-2999?focusedCommentId=493386)
- Used the splat operator to add the list of tasks from the linear flow directly to the create amphora flow
N/A
N/A
**GLM …
=> [STACK-2999] GLM tasks aren't ignored during second loadbalancer create

a10_octavia/api/drivers/flavor_schema.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_compute_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_database_tasks.py
- Issue Description: [FlavorProfile]: Getting error while valiating flavorrprofile
- https://a10networks.atlassian.net/browse/STACK-3009
- Changed the type from "bool" from "boolean" in flavor_schema.
- Removed unused import from test_a10_compute_tasks.py
- Updated the _test_update_listeners_stats_with_statistics_ test case as deleting of listener stats is removed from UpdateListenerStats task.
- N/A
- N/A
1) Create Flavor profile
```
stack@adeeb-victoria:~/adeeb/a10-octavia$ openstack loadbalancer flavorprofile create --name fp_persistcookie --provider a10 --flavor-data '{"virtual-server":{"stats-data-action":"stats-data-disable","extended-stats":1,"disable-vip-adv":1,"enable-disable-action":"disable-when-all-ports-down","arp-disable":1},"virtual-port":{"auto":1," …
```
=> [BUG][STACK-3009]: Fix for validating flavor schema by changing type from bool to boolean

a10_octavia/controller/worker/tasks/persist_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_persist_tasks.py
- Issue Description :[unset pool session_persistence] slb template persist isn't removed when unset pool's session persistence
- https://a10networks.atlassian.net/browse/STACK-2758
- Change the position of the "if statement" so that it can remove the existing persistence template.
- N/A
- Changed _test_handle_session_persistence_with_app_cookie_with_no_sess_pers_type_ ,  _test_handle_session_persistence_with_source_ip_with_no_sess_pers_ and _test_unset_session_persistence_.
1) Create lb, listener and pool
```
openstack loadbalancer create --name v1 --vip-subnet-id private-11-subnet
openstack loadbalancer listener create --name l80 v1 --protocol http --protocol-port 80
openstack loadbalancer pool create --name p80 --protocol http --lb-algorithm LEAST_CONNECTIONS …
```
=> [BUG][STACK-2758]: Updated code for removing existing persistence template

a10_octavia/common/a10constants.py, a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py
Loadbalancers will stay in pending update when failover is failed.
https://a10networks.atlassian.net/browse/STACK-3022
Set the loadbalancers in loadbalancer list to ERROR state in revert flow
<pre>
<b>stack@ytsai-victoria:~/source/a10-octavia$ sed -e '/^#/d' /etc/a10/a10-octavia.conf  | grep -Ev "^$"
[vthunder]
amp_image_owner_id = ecc2542be2644881b049636b719ca536
amp_secgroup_list = 5a83254b-7a99-4684-a4e5-94ed75d505c9
amp_flavor_id = ba761d2f-a08c-42eb-a53e-e3a0fa646590
amp_boot_network_list = 9558e757-f279-4120-9e61-540a91be9c10, 0aab2734-6a42-4ef9-acd6-527956b3dadc
amp_ssh_key_name = …
=> [STACK-3022] Set LBs to ERROR when failover failed

a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Issue Description: Getting an error when creating/updating a member without specifying subnet_id by member_batch_update script.
https://a10networks.atlassian.net/browse/STACK-3122
- Added checks for member's subnet_id wherever required.
N/A
1. Create a loadbalancer, listener and pool.
stack@neha-victoria:~$ openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name lb1
```
| availability_zone   | None                                 |
| created_at          | 2021-10-29T11:42:26                  |
| …
```
=> [BUG][STACK-3122]: Resolved issues for member creation/updation when subnet_id is not specified during member_batch_update.

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/tasks/a10_compute_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_compute_tasks.py
- Issue Description: An unexpected error encountered when LB is created without specifying `amp_boot_network_list` or `amp_mgmt_network` in config file.
https://a10networks.atlassian.net/browse/STACK-3050
- Created a custom exception `NetworkNotFoundToBootAmphora()` which will be raised if there is no any mgmt_net specified while creating a loadbalancer.
- Raising the exception when mgmt_net is None.
Following config is used:
```
[a10_global]
network_type = 'flat'
vrid_floating_ip = "dhcp"
[vthunder]
[glm_license]
primary_dns = 8.8.8.8
secondary_dns = 8.8.4.4
flexpool_token = A10b9c2d136d
allocate_bandwidth = 100
amp_image_owner_id = …
```
=> [BUG][STACK-3050]: Raising an exception when management network is not specified while loadbalancer creation.

a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/flows/a10_pool_flows.py
Added support for handle_vrid config option sothat manually configured VRID FIP will not get removed on loadbalancer and member creation/deletion/updation.
https://a10networks.atlassian.net/browse/STACK-3120
- Added handle_vrid config option in a10_global section with default value as True.
- Added checks for this oprion in a10_loadbalancer_flows, a10_member_flows and a10_pool_flows, wherever vrid creation and deletion is getting called.
- vrid related flows will get executed when handle_vrid option is True, otherwise they will get skipped.
```
[a10_global]
handle_vrid = <True/False>
```
vThunder flows cases:
1. Create a loadbalancer without setting handle_vrid option in the config.
stack@neha-victoria:~/neha/a10-octavia$ openstack loadbalancer create --vip-subnet-id …
=> [STACK-3120]: Added support for handle_vrid config option in victoria

a10_octavia/contrib/scripts/a10_setup_provider_no_dns, a10_octavia/controller/worker/tasks/glm_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_glm_tasks.py
Severity: High
Multiple flexpool usage issues were detected due to a keyword 'subnet' not being used to access the subnet dictionary from the returned payload prior to looking up the `dns-nameserver` keyword.
Severity: Critical
Exception encountered when deleting a loadbalancer when a connection cannot be established with the GLM. This prevents loadbalancers from being deleted
Severity: Low
Error occurs when attempting to enable burst when using a burst license
https://github.com/a10networks/acos-client/pull/365
- [STACK-3055](https://a10networks.atlassian.net/browse/STACK-3055)
- [STACK-3056](https://a10networks.atlassian.net/browse/STACK-3056)
- [STACK-3071](https://a10networks.atlassian.net/browse/STACK-3071)
- [STACK-3110](https://a10networks.atlassian.net/browse/STACK-3110)
- …
=> [STACK-3055/3056/3071/3110/3126] Various flexpool fixes

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/glm_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_compute_tasks.py
Due to the lack of validation in the MembersController (https://github.com/openstack/octavia/blob/stable/victoria/octavia/api/v2/controllers/member.py#L319) it is possible for the driver agent and subsequently the controller worker to receive members with duplicate member ids.
This becomes problematic as it leads duplicate atoms in the flow which cause the taskflow engine to throw an irrecoverable error.
As the SLB objects (loadbalancer, pool, member) are put into PENDING_UPDATE by the MembersController, the entire SLB tree becomes "permanently" immutable. (Still possible to destroy everything in db and ACOS device and recover, but tedious).
Since the update to the Octavia member database table happens in the MembersController, one of the duplicates will have it's …
=> [STACK-3121] Duplicate members in batch update causes pending state freeze of SLB tree

a10_octavia/controller/worker/tasks/l7policy_tasks.py
- Issue Description: When l7policy is there in the SLB tree and cascade deletion of a loadbalancer in the SLB tree is performed, then nat-pool port is not getting deleted on the cascade deletion.
https://a10networks.atlassian.net/browse/STACK-3129
- Passing source nat-pool to source_nat_pool argument in the self.axapi_client.slb.virtual_server.vport.replace() call in DeleteL7Policy() task if virtual-port associated to the policy is having a source nat-pool attached to it.
- Otherwise passing None by default to the source_nat_pool.
None
1. Create a loadbalancer
stack@ytsai-victoria:~$ openstack loadbalancer create --vip-subnet-id tp92 --name lb
```
| Field               | Value …
```
=> [BUG][STACK-3129]: Nat-pool port is not getting deleted on cascade deletion of loadbalancer.

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/l7policy_tasks.py
1. When l7policy is there in the SLB tree and cascade deletion of a loadbalancer in the SLB tree is performed, then nat-pool port is not getting deleted on the cascade deletion.
2. Duplicate members in batch update causes pending state freeze of SLB tree
https://a10networks.atlassian.net/browse/STACK-3165
- Passing source nat-pool to source_nat_pool argument in the self.axapi_client.slb.virtual_server.vport.replace() call in DeleteL7Policy() task if virtual-port associated to the policy is having a source nat-pool attached to it.
- Otherwise passing None by default to the source_nat_pool.
- Combined member definitions into hashmap with counts of member ids encountered
- Performed a check that none of the member definitions are observed more than …
=> [STACK-3165]: [v1.3.3] Porting STACK-3121 and STACK-3129 to a10_octavia_1_3_3-d branch

a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py
- Moved health monitor from **service group** to **slb server** and attached listener port to health monitor 
https://a10networks.atlassian.net/browse/STACK-3171
https://a10networks.atlassian.net/browse/STACK-3172
https://a10networks.atlassian.net/browse/STACK-3173
https://a10networks.atlassian.net/browse/STACK-3174
https://a10networks.atlassian.net/browse/STACK-3175
https://a10networks.atlassian.net/browse/STACK-3176
https://a10networks.atlassian.net/browse/STACK-3169
- Removed the association between **health-monitor** and **service-group**.
- Added **health_check**  parameter in axapi call of **create** and **update** slb server operations to attach healthmonitor  to slb server.
- Modified **delete_pool_flow** to execute **self._get_delete_member_vthunder_subflow** before …
=> [STACK-3171] Health Monitor on target server ports

README.md, a10_octavia/common/config_options.py, a10_octavia/controller/worker/tasks/server_tasks.py
This change adds a global option which causes new loadbalancer members to be created with the same nomenclature used by the neutron a10 driver. This is useful if using neutron lbaas and octavia concurrently since octavia members created with the alternative nomenclature can't be reused as neutron members.
=> global option to use neutron lbaas member names

a10_octavia/api/drivers/driver.py
The previous rpc call can open multiple connections to rabbitMQ causing a runaway socket descriptor issue, where the socket descriptor limit is hit quickly in a large environment.  This update uses octavia.common.rpc to change the driver behavior to a singleton. 
Bug Fix:
This change calls the octavia.common.rpc function built into openstack/octavia to use a singleton as documented here: https://review.opendev.org/c/openstack/octavia/+/636428/12/octavia/common/rpc.py#65
This fixes the connection leaking issue seen in the a10-octavia/api/drivers/driver.py functionality. 
```
from octavia.common import rpc
self.target = messaging.Target(
namespace=constants.RPC_NAMESPACE_CONTROLLER_AGENT,
topic='a10_octavia', version='1.0', fanout=False
)
self.client = …
```
=> [BUG] Update driver rpc to singleton

a10_octavia/common/config_options.py, a10_octavia/controller/worker/flows/a10_member_flows.py
This config option allows for an A10 Octavia operator to disable the validate subnet functionality.  This is useful in cases where developers may be using kubernetes with the legacy Openstack provider they're not able to specify a different subnet for the load balancer object and member servers. Example code: 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/openstack/openstack_loadbalancer.go#L448
- A boolean config option was added to allow operators to skip the validate subnet check when adding members. 
<pre>
<b>    
cfg.BoolOpt('validate_subnet', default=True,
help=_('Allow for members and VIPs to exist in the same '
' subnet (for use with kube cloud provider)')),
</b>
</pre>
=> Allow for disabling validate subnet

a10_octavia/common/exceptions.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
If Bug Fix:
In hardware thunder flow, a10-octavia create loadbalancer failed if the vlan network configure an IPv6 Subnet (and this subnet is the first one i.e.  network.subnets[0]).
- Required: Add links to tickets closed here](https://a10networks.atlassian.net/browse/STACK-3242)
- a10-octavia didn't support IPv6 for now. So, when select subnet for specified vlan_id only select the IPv6 subnet.
<pre>
<b>[vthunder]
amp_image_owner_id = ecc2542be2644881b049636b719ca536
amp_secgroup_list = 5a83254b-7a99-4684-a4e5-94ed75d505c9
amp_flavor_id = …
=> [STACK-3242] Fix a10-octavia failed with IPv6 subnet in network

a10_octavia/controller/worker/tasks/a10_database_tasks.py
Bug Fix: 
- Medium
- As a user, if I create a member without a subnet_id, the member is unable to be deleted from Octavia. It requires an Openstack operator to clean up the database and manually remove the member from the A10 Thunder device. 
- N/A, External Contributor. 
- Similar to other tasks within the a10_database_tasks, this change evaluates if a subnet is present when running CountMembersOnThunderBySubnet and simply returns 0 if the value is not set. 
```
openstack loadbalancer create \
--vip-subnet-id vip-supnet \
--name lb1
openstack loadbalancer listener create \
--name listener1 \
--protocol TCP \
--protocol-port 80 \
lb1
openstack loadbalancer pool create \
--name pool1 \
--lb-algorithm ROUND_ROBIN \
--listener listener1 \
--protocol TCP 
openstack loadbalancer member create …
```
=> CountMembersOnThunderBySubnet return 0 if no subnet_id for member

a10_octavia/common/config_options.py
If Bug Fix:
Severity Level: Low,
Issue Description: 
The post_data option is required when POST health monitor is used. But we can add a default value to prevent user forget to provide the post_data.
https://a10networks.atlassian.net/browse/STACK-3365
Provide a default value to prevent user forget to provide the post_data.
<pre>
<b>N/A</b>
</pre>
- run the script below:
```
#!/bin/sh
set -e
subnet_id=$(openstack subnet show tp91 -c id -f value)
TOKEN=$(openstack token issue -f value -c id)
OCTAVIA_BASE_URL=$(openstack endpoint list --service load-balancer --interface public -c URL -f value)
cat <<EOF > tree.json
{
"loadbalancer": {
"name": "vip1",
"vip_subnet_id": "$subnet_id",
"provider": "a10",
"listeners": [
{
"name": "vport1",
"protocol": "TCP",
"protocol_port": 80,
"default_pool": { …
```
=> [STACK-3365] add default valuss for post_data option

a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_health_monitor_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py
- Required: Severity Level: Critical
- Required: Issue Description:
Health Monitor will not configured on slb servers if Health Monitor creation command is after the member creation commands.
This is introduced after: https://github.com/a10networks/a10-octavia/pull/560/files
Previously we have logic to update service-group health monitor. But when move hm from service-group to slb server. We didn't implement the logic for membre.
https://a10networks.atlassian.net/browse/STACK-3375
For CreateAndAssociateHealthMonitor(), we need to update members in the pool with the health monitor.
<pre>
<b>N/A</b>
</pre>
- verify commands:
```
openstack loadbalancer listener create --protocol HTTP --protocol-port 80 --name vport1 vip1 …
```
=> [STACK-3375] Fix health monitor missing when HM configured after member

a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_health_monitor_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_server_tasks.py
- Description:
vthunder flow cascade deletion failed for octavia failed to update security group rule at:
https://github.com/openstack/octavia/blob/stable/victoria/octavia/network/drivers/neutron/allowed_address_pairs.py#L219
- Root Cause:
- In _get_cascade_delete_pools_listeners_flow(), listeners_delete_flow is an unordered flow so multiple listener are deleting and calling UpdateVIPForDelete() at the same time.
- But the loadbalancer (and loadbalancer.listener) parameter didn't updated and sync with database. So, it always generate the same add/del rules. And neutron return failed for rule already existed.
https://a10networks.atlassian.net/browse/STACK-3372
1. update loadbalancer before calling UpdateVIPForDelete()
2. we only need  to call UpdateVIPforDelete() to …
=> [STACK-3372] Fix cascade delete failed with multiple listeners

a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/cert_tasks.py
- Required: Severity Level: High
For openstack loadbalancer listener set command, if the --default-tls-container-ref is not changed do not delete the secret.
[**This is optional if you are an external contributor**
- Required: Add links to tickets closed here](https://a10networks.atlassian.net/browse/STACK-3392)
In ClientSSLTemplateUpdate task, if the cert/key is not changed. Do not delete then in ACOS side.
<pre>
<b>N/A</b>
</pre>
1. configure loadbalancer and listener with secret
2. use same secret to update listener
```
openstack loadbalancer create --vip-subnet-id tp91 --vip-address 192.168.91.56 --name vip1
openstack loadbalancer listener create --protocol TERMINATED_HTTPS --protocol-port 443 --default-tls-container-ref="$(openstack secret container list …
```
=> [STACK-3392] Fix listener update SSL failed

a10_octavia/api/drivers/driver.py, a10_octavia/controller/worker/flows/a10_listener_flows.py, a10_octavia/controller/worker/tasks/cert_tasks.py, a10_octavia/controller/worker/tasks/utils.py, a10_octavia/tests/unit/controller/worker/tasks/test_cert_tasks.py
Fixed TERMINATED_HTTPS listener update and delete issues
https://a10networks.atlassian.net/browse/STACK-3395
- For resolving update issue. Passed **update_dict** and updated the listener as per to the parameters present in the update dictionary
- Updated **listener_update** In driver.py to fetch value of updated **default_tls_container_ref**
- Skipped the delete operation in **SSLCertDelete** and  **SSLKeyDelete**  if the **cert_data** is **None** (If default_tls_container_ref is not found in Openstack secret container )
- Create listener, Update listener, delete listener
**Testing Rack flow with 4.x vThunder version:**
```
stack@qa45:~#openstack loadbalancer create --vip-subnet-id 172.16.0.0 --name lb10
+---------------------+-------------------------------------- …
```
=> [STACK-3395] Case # 00349171 FW: A10 Octavia Driver and Certificate Updates Case Reference ID: ref:_00D301Kns._5004z1khY3x:ref

a10_octavia/cmd/a10_house_keeper.py, a10_octavia/common/config_options.py, a10_octavia/controller/housekeeping/house_keeping.py, a10_octavia/controller/worker/controller_worker.py, a10_octavia/controller/worker/tasks/a10_database_tasks.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/glm_tasks.py, a10_octavia/controller/worker/tasks/health_monitor_tasks.py, a10_octavia/controller/worker/tasks/l7policy_tasks.py, a10_octavia/controller/worker/tasks/l7rule_tasks.py, a10_octavia/controller/worker/tasks/nat_pool_tasks.py, a10_octavia/controller/worker/tasks/server_tasks.py, a10_octavia/controller/worker/tasks/service_group_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/db/repositories.py, requirements.txt
Sometimes execution of A10-octavia can get failed during slb objects’ creation/updation/deletion due to some interrupting situations and then the slb objects may stay in PENDING status. 
There is no way to delete these PENDING objects from OpenStack side and thus those PENDING objects also remain as it is in database. 
This feature will let the a10-octavia to cleanup all the pending resources along with their ports and security groups(in case of LB and member) after a specific interval of time.
https://a10networks.atlassian.net/browse/STACK-3420
- Added support for `pending_resource_cleanup` and `resource_cleanup_interval` config options in `[a10_house_keeping]` section.
- Implemented a method `pending_resource_cleanup()` for cleaning up the pending resources in a specified interval of …
=> [Feature][STACK-3420] Pending Resource Cleanup

a10_octavia/controller/worker/flows/vthunder_flows.py, a10_octavia/controller/worker/tasks/cert_tasks.py, a10_octavia/controller/worker/tasks/utils.py
SSL template aXAPIs has been changed in ACOS version 5.2.1, due to which we are facing some issues for importing/updating/deleting pki certs and keys on ACOS 5.2.1 corresponding to client-ssl template configured while creating/updating/deleting a TERMINATED_HTTPS listener.
By this feature, correct SSL APIs for appropriate ACOS versions will get called by checking the version before calling them.
https://a10networks.atlassian.net/browse/STACK-3431
- Added a task `UpdateAcosVersionInVthunderEntry` for updating acos-version in vthunders table during loadbalancer creation for rack flows.
- Added some methods for comparing current acos version with a specific provided version in utils.py
- Modified task GetSSLCertData() to check whether the current acos-version is greater than or equal to …
=> [STACK-3431]: ACOS 5 SSL aXAPI support

a10_octavia/controller/worker/flows/a10_load_balancer_flows.py
- Issue Description: Getting Atoms with duplicate name found issue while performing fully populated loadbalancer creation.
https://a10networks.atlassian.net/browse/STACK-3589
- Added a name for the issuing task in the a10_load_balancer_flow.
N/A
1. Create fully populated IPv6 loadbalancer with all other slb objects  with rack flows.
2. Create fully populated IPv4 loadbalancer with all other slb objects  with rack flows
For IPv6:
Perform following fully_populated_loadbalancer creation script for IPv6 LB creation:
```
#!/bin/sh
set -e
subnet_id=$(openstack subnet show ipv6_subnet_vlan_11 -c id -f value)
TOKEN=$(openstack token issue -f value -c id)
OCTAVIA_BASE_URL=$(openstack endpoint list --service load-balancer --interface public -c URL -f value)
cat <<EOF > …
```
=> [STACK-3589] Resolved Atoms with duplicate name issue for Fully populated loadbalaner feature.

a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Issue Description: When we try to delete an ERROR loadbalancer, getting an error like "IndexError: list index out of range".
https://a10networks.atlassian.net/browse/STACK-3596
- Added a check for vthunder before computing amphora_id wherever calculated.
N/A
- Create a loadbalancer such that it goes into ERROR state.
- Delete the loadbalancer.
```
stack@neha-victoria:~$ openstack loadbalancer create --vip-subnet-id ipv6_subnet_vlan_11 --name vip1                                     +---------------------+--------------------------------------+
| availability_zone   | None …
```
=> [STACK-3596]: Fixed issue of deleting ERROR state IPv6 loadbalancer.

a10_octavia/controller/worker/flows/a10_pool_flows.py, a10_octavia/controller/worker/tasks/virtual_port_tasks.py
- Issue Description: aflex policy was getting deleted from listener when pool is deleted.
https://a10networks.atlassian.net/browse/STACK-3592
- Added a flag `clear_aflex` for deciding whether to remove aflex from listener on deleting pool.
N/A
- Create a loadbalancer, listener, pool, member, healthmonitor, l7policy and l7rule.
- Delete the pool.
- Check vThunder configurations. 
- Delete l7rule and l7policy.
- Check vThunder configurations.
1.  Create a loadbalancer, listener, pool, member, healthmonitor, l7policy and l7rule.
```
stack@neha-victoria:~$ openstack loadbalancer create --vip-subnet-id provider-vlan-11-subnet --name vip1 …
```
=> [STACK-3592]: Resolved issue of aflex deletion on vThunder happening on pool deletion.

a10_octavia/common/exceptions.py, a10_octavia/common/utils.py
- Issue Description: It is expected to get an exception or warning if we don’t specify ipv6 address for a network specified in amp_boot_network_list or for a subnet used for creating a loadbalancer. But got an error in this case.
https://a10networks.atlassian.net/browse/STACK-3603
- Created a custom exception `IPv6AddressNotFoundInConfig`  in exceptions.py
- Raising the exception if `final_address_list` is empty calculated in `get_ipv6_address_from_conf()`.
N/A
- Create a loadbalancer with ipv6 subnet with not specifying ipv6 address for that subnet in `subnet_ipv6_addresses` in config file.
- Check the logs for exception.
- Create a loadbalancer with 2 networks in `amp_boot_network_list` in config file - 1 management and another ipv6 n/w, and don't add the ipv6 n/w …
=> [STACK-3603]: Raised exception if ipv6 address not found in config file

a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
- Issue Description: While using static vrid_floating_ip, getting an error while creating a loadbalancer or member with different subnet than that of an existing loadbalancer.
https://a10networks.atlassian.net/browse/STACK-3442
-  In case of static or patched vrid_floating_ip, calling `a10_utils.get_patched_ip_address()` only when vrid.vrid_floating_ip is None i.e calling it for a loadbalancer or member that is getting created but not for existing LBs or members to avoid the `VRIDIPNotInSubentRangeError` 
N/A
Case 1: vThunder flows
- Create a LB with ipv6 subnet1 and static vrid_floating_ip.
- Create an another LB with ipv6 subnet2 and static vrid_floating_ip.
- Create a member with ipv6 subnet3 and static vrid_floating_ip.
- Check vThunder configurations.
Case 2: …
=> [STACK-3442]: Fixed issue of Static VRID floating IP configurations.

a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Severity Level: Critical
Create ipv4 LB failed without ipv6_subnet_list option in configuration file.
https://a10networks.atlassian.net/browse/STACK-3635
Add list empty check before use it.
Same as the configuration in bug ticket.
```
openstack loadbalancer create --vip-subnet-id tp91 --vip-address 192.168.91.56 --name vip1
```
Result:
```
stack@ytsai-victoria:~/a10-octavia$ openstack loadbalancer list
+--------------------------------------+------+----------------------------------+---------------+---------------------+------------------+----------+
| id                                   | name | project_id                       | vip_address   | provisioning_status | operating_status | provider |
+--------------------------------------+------+---------------------- …
```
=> [STACK-3635] Create ipv4 LB failed without ipv6_subnet_list option

a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/a10_network_tasks.py, a10_octavia/controller/worker/tasks/nat_pool_tasks.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py, a10_octavia/tests/unit/controller/worker/tasks/test_a10_network_tasks.py
- Severity Level: Critical
Use IPv6 network in amp_boot_network_list, a10-octavia failed to create LB in vthunder flow.
root cause: In get_ipv6_address(), the nic.network_id is network id not subnet id. get_ipv6_address_from_conf() can only works for subnet_id.
https://a10networks.atlassian.net/browse/STACK-3636
- Implement get_network_ipv6_address_from_conf() to get ipv6 address for network_id.
- In get_ipv6_address(), skip ipv4 nics.
<pre>
amp_boot_network_list = 9558e757-f279-4120-9e61-540a91be9c10, f7c66e14-6eb1-456b-a677-65ce525d175e, 338ab9a6-520e-4804-8225-dc17c4db442d
[a10_global]
subnet_ipv6_addresses = [{"c8556731-9316-480c-b7f3-15c7521416c4": "2400:8500:2002:1270::56/64"}]
</pre>
Same as bug ticket
with 
openstack loadbalancer create …
=> [STACK-3636] Failed with IPv6 network in amp_boot_network_list

a10_octavia/controller/worker/tasks/vthunder_tasks.py
- Severity Level: Critical
- IPv6 interfaces not enabled
- Failed to configure IPv6 interface for member/LB delete case.
acos-client changes: https://github.com/a10networks/acos-client/pull/387
https://a10networks.atlassian.net/browse/STACK-3637
https://a10networks.atlassian.net/browse/STACK-3639
1. enable ipv6 interfaces
2. Clear all unmatched ipv6 addresses for all interfaces before configure ipv6 address.
Please check bug tickets
```
openstack loadbalancer listener create --protocol TCP --protocol-port 80 --name vport1 vip1
openstack loadbalancer pool create --protocol TCP --lb-algorithm ROUND_ROBIN --listener vport1 --name sg1
openstack loadbalancer member create --address 192.168.92.24 --subnet-id …
```
=> [STACK-3637][STACK-3639] vthunder IPv6 interface and address issues

a10_octavia/common/utils.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
Use port IPv6 address
https://a10networks.atlassian.net/browse/STACK-3640
Get IPv6 address from port and configure to ACOS interface
Use no subnet_ipv6_addresses in a10-octavia.conf
- STANDALONE
```
openstack loadbalancer create --vip-subnet-id 2002 --name vip2
openstack loadbalancer listener create --protocol TCP --protocol-port 80 --name vport2 vip2
openstack loadbalancer pool create --protocol TCP --lb-algorithm ROUND_ROBIN --listener vport2 --name sg2
openstack loadbalancer member create --address 2003::24 --subnet-id 2003 --protocol-port 80 --name srv21 sg2
openstack loadbalancer member create --address 2004::24 --subnet-id 2004 --protocol-port 80 --name srv22 sg2
```
- Active-standby
```
openstack loadbalancer create --vip-subnet-id 2002 --name vip2 …
```
=> [STACK-3640] ACOS interface use port IPv6 address

a10_octavia/common/utils.py, a10_octavia/controller/worker/flows/a10_load_balancer_flows.py, a10_octavia/controller/worker/flows/a10_member_flows.py, a10_octavia/controller/worker/tasks/vthunder_tasks.py
For batch member update, we have multiple subnets and we are not able to pass all subnet to GetIPv6Addr().
But actually we don't need the subnet information, since we need to get all plugged interface addresses not just the updated LB/member subnet.
https://a10networks.atlassian.net/browse/STACK-3647
For batch member update, we have multiple subnets and we are not able to pass all subnet to GetIPv6Addr().
But actually we don't need the subnet information, since we need to get all plugged interface addresses not just the updated LB/member subnet
- **SINGLE**
- **Active-Standby**
- With or without **amp_boot_network_list** and **subnet_ipv6_addresses**
- SINGLE
- add all ipv6 subnet to boot networks
- Configure LBs and members
- delete LB/member
- …
=> [STACK-3647] Batch Member Update Regression

a10_octavia/common/config_options.py, a10_octavia/common/utils.py
Add use_subnet_ipv6_addresses_only option for:
- False: configure both subnet_ipv6_addresses and DHCPv6 addresses for interface.
- True: configure only subnet_ipv6_addresses addresses for interface.
https://a10networks.atlassian.net/browse/STACK-3648
Add use_subnet_ipv6_addresses_only option for:
- False: configure both subnet_ipv6_addresses and DHCPv6 addresses for interface.
- True: configure only subnet_ipv6_addresses addresses for interface.
N/A
- SINGLE
- add all ipv6 subnet to boot networks
- Configure LBs and members
- delete LB/member
- ACTIVE-STANDBY
- add all ipv6 subnet to boot networks
- Configure LBs and members
- delete LB/member
Testing still ongoing
=> [STACK-3648] Add use_subnet_ipv6_addresses_only option
